### ISSUE TITLE
Loading config flow

### ISSUE THREAD

**Issue by basbruss** [Tasshack/dreame-vacuum#1]
Hi,

Love your development for the dreame vacuums!

When I add your integration to my setup (fresh install) it will not be able to load the config flow.
<img width="513" alt="image" src="https://user-images.githubusercontent.com/68892092/194518003-b77a1a1d-dc76-484a-a4e2-899c9de9a4b1.png">

It returns this error in the logs:
```
Logger: homeassistant.config_entries
Source: config_entries.py:809
First occurred: 10:34:45 (2 occurrences)
Last logged: 11:10:58

Error occurred loading configuration flow for integration dreame_vacuum: Error relocating /usr/local/lib/python3.10/site-packages/cv2/cv2.abi3.so: cblas_dgemm: symbol not found
```

**Comment by basbruss** [comment]
@Tasshack The proposed solution did not help. I also spun up a dev-container in vscode by manually installing `opencv-python-headless`; `tzlocal` and `construct` I was able to load the config flow. Unfortunately this did not work on my main system that runs HaOS in a proxmox VM.

**Comment by rbforelle** [comment]
I can also confirm this issue after updating the HA docker image to the latest version. 

Before I have also tried to configure Dreame Vacumms with an older version 2022.08.02 and I got this:
```
Logger: homeassistant.util.package
Source: util/package.py:98
First occurred: 13:23:49 (3 occurrences)
Last logged: 13:24:20

Unable to install package numpy==1.23.2: ERROR: Cannot install numpy==1.23.2 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```
```
Logger: aiohttp.server
Source: requirements.py:267
First occurred: 13:24:20 (1 occurrences)
Last logged: 13:24:20

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 145, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 70, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 222, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 240, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 791, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 362, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 49, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 168, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 183, in _async_process_integration
    await self.async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 236, in async_process_requirements
    await self._async_process_requirements(name, missing)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 267, in _async_process_requirements
    raise RequirementsNotFound(name, list(failures))
homeassistant.requirements.RequirementsNotFound: Requirements for dreame_vacuum not found: ['numpy==1.23.2'].
```

**Comment by yjamal01** [comment]
> @basbruss is it possible you to manually update the manifest.json file and try again.
> 
> ```
> {
>   "domain": "dreame_vacuum",
>   "name": "Dreame Vacuum",
>   "config_flow": true,
>   "documentation": "https://github.com/tasshack/dreame-vacuum",
>   "issue_tracker": "https://github.com/Tasshack/dreame-vacuum/issues",
>   "codeowners": [ "@tasshack" ],
>   "requirements": [
>     "voluptuous",
>     "pillow",
>     "opencv-python-headless==4.5.1.48",
>     "pybase64",
>     "requests",
>     "pycryptodome"
>   ],
>   "version": "0.4.1",
>   "iot_class": "local_polling"
> }
> ```

I gave this a try and while I don't get the same error, it hangs at "Please wait, starting configuration wizard for Dreame Vacuum"

**Comment by rbforelle** [comment]
> @basbruss @rbforelle @yjamal01 i have just released a new version which do not uses OpenCV for fixing the config flow issue. This change adds a little bit of render time but the image actually looks better now.

The config flow works for me with the newest release. Thanks a lot for you work! It's really great to have so many options of the app now in HA.

But I still have some problems with the map. Camera related entities are not generated automatically on my side.

Also, the names of the mopping related entities are not correct. I will open an issue later about this.

**Comment by basbruss** [comment]
I can also confirm that the problems with the config flow do not occur anymore on the latest release of HA 🚀
