### ISSUE TITLE
Dreame D9 max (dreame.vacuum.p2259) gives lots of warnings/errors, integration makes robot unusable (buttons and in App)

### ISSUE THREAD

**Issue by dierochade** [Tasshack/dreame-vacuum#127]
Dreame D9 max (dreame.vacuum.p2259) gives lots of warnings/errors, integration makes robot unusable (buttons and in App)

**Describe the bug**
I can add the vacuum and perform all kind of actions (like map import and updating, call services, get status info (consumables, charging) etc
But the vacuum gives me all kind of warnings/Errors in the logs. See below.
Moreover it seems that the integration impairs the device‘s software. E.g. after giving a clean command, sometimes the robot leaves the dock, but seems „confused“ afterwards, turns for 30 degrees or so, waits some seconds, turns again, waits, again, and eventually goes to pause. Or it starts normally but after some time it just aborts the task and sits still, going to sleep.
When the integration is deactivated, the vacuum works as expected. 
For completeness: I did get warnings at the beginning (only in the xiaomi app): poor wifi signal and package loss (up to 20%!). But after a factory reset of the device, new network setup and a new cloud account that doesnt show up anymore. The signal should be perfect normally, cause the robot is in line of sight to the AP and less then 3m distance. Got no other Wifi problems, too.  
![FireShot Capture 043 - Settings – Home Assistant - 192 168 100 56](https://user-images.githubusercontent.com/125600882/234097049-4597d298-2660-4765-affc-bb90c1bf3ea3.png)

**To Reproduce**
All the time when integration is activated

**Expected behavior**
No warnings, no errors, normal behaviour of the robot.

**Additional Information**
 - Model Name:
Dreame D9 max (dreame.vacuum.p2259)
- Firmware Version [e.g. 1156]:
Firmware: 3.5.8_1004
 - Home Assistant Version: 	
Home Assistant 2023.4.5
Supervisor 2023.04.0
Operating System 10.0
Frontend 20230411.1 - latest
 - Configuration Type [With or without map support]:
With map support, credentials via mi.com account

**Errors or warnings shown in the HA logs (if applicable):**
Full logs upoad:
https://zeebi.dedyn.io:30000/s/K7e4YqFJsPSEX3r
- newer log: exteneded logging, errors as in screenshot, starting about 21:15:24
- Older log: normal debug level, errors as shown below
 
Logger: aiohttp.server
Source: /usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py:403
First occurred: April 21, 2023 at 7:12:59 AM (11 occurrences)
Last logged: 6:44:32 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"

This error originated from a custom integration.

Logger: custom_components.dreame_vacuum.dreame.map
Source: custom_components/dreame_vacuum/dreame/map.py:465
Integration: Dreame Vacuum (documentation, issues)
First occurred: April 21, 2023 at 8:51:48 PM (107 occurrences)
Last logged: April 22, 2023 at 8:13:27 PM

Send request map failed: No response from the device
Getting map_data from cloud failed

This error originated from a custom integration.

Logger: miio.miioprotocol
Source: custom_components/dreame_vacuum/dreame/protocol.py:518
Integration: Dreame Vacuum (documentation, issues)
First occurred: April 21, 2023 at 8:51:48 PM (137 occurrences)
Last logged: April 22, 2023 at 8:13:27 PM

Got error when receiving: timed out

This error originated from a custom integration.

Logger: custom_components.dreame_vacuum
Source: helpers/update_coordinator.py:348
Integration: Dreame Vacuum (documentation, issues)
First occurred: April 21, 2023 at 8:52:33 PM (4 occurrences)
Last logged: April 22, 2023 at 8:12:30 PM

Error requesting dreame_vacuum data: No response from the device
Error requesting dreame_vacuum data: Unable to discover the device 192.168.100.39

This error originated from a custom integration.

Logger: custom_components.dreame_vacuum.dreame.device
Source: custom_components/dreame_vacuum/dreame/device.py:694
Integration: Dreame Vacuum (documentation, issues)
First occurred: April 21, 2023 at 8:52:06 PM (16 occurrences)
Last logged: April 22, 2023 at 8:12:21 PM

Update failed, retrying 2: Unable to discover the device 192.168.100.39
Update failed, retrying 3: Unable to discover the device 192.168.100.39
Update failed, retrying 1: No response from the device
Update failed, retrying 2: No response from the device
Update failed, retrying 3: No response from the device

This error originated from a custom integration.

Logger: custom_components.dreame_vacuum.dreame.protocol
Source: custom_components/dreame_vacuum/dreame/protocol.py:238
Integration: Dreame Vacuum (documentation, issues)
First occurred: April 22, 2023 at 5:46:24 AM (2 occurrences)
Last logged: April 22, 2023 at 12:12:37 PM

Error while executing request: https://de.api.io.mi.com/app/user/get_user_device_data ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

Logger: homeassistant.components.recorder.db_schema
Source: components/recorder/db_schema.py:585
Integration: Recorder (documentation, issues)
First occurred: April 21, 2023 at 8:16:37 AM (1 occurrences)
Last logged: April 21, 2023 at 8:16:37 AM

State attributes for persistent_notification.dreame_vacuum_error_2 exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored

Logger: homeassistant
Source: runner.py:137
First occurred: April 21, 2023 at 6:47:01 AM (1 occurrences)
Last logged: April 21, 2023 at 6:47:01 AM

Error doing job: Task was destroyed but it is pending!

**Comment by dierochade** [comment]
Hej. Thanks for the reply!

I think you refer to "Xiaomi Miot For HomeAssistant"? via hacs repository?
I do not use the integration and i did not have it installed in the past. 
I did use xiaomi vacuum card, but its just a card though?

I tried to use the vacuum without map, too. However, I still get a lot of warnings, although i noticed not that many.

I have seen that my logs are spammed wiht zha debug logging. Sorry fot that, i did not realise it was active at this time. I can create new logs if necessary.
