### ISSUE TITLE
Integration fails to set up Dreame Bot Z10 Pro with AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

### ISSUE THREAD

**Issue by hdiessner** [Tasshack/dreame-vacuum#131]
**Describe the bug**
Integration fails to set up Dreame Bot Z10 Pro with error after update to HA 2023.5.2
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**To Reproduce**
Updated HA to latest version 2023.5.2, error occurs.

**Expected behavior**
Integration is loaded and Dreame Bot Z10 Pro is set up

**Additional Information (please complete the following information)**
 - Model Name [e.g. dreame.vacuum.p2028]:
 - Firmware Version [e.g. 1156]:
 - Home Assistant Version: 
     Home Assistant 2023.5.2
     Supervisor 2023.04.1
     Operating System 10.1
     Frontend 20230503.3 - latest
 - Configuration Type [With or without map support]: with
 - Errors or warnings shown in the HA logs (if applicable):
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/dreame-vacuum/__init__.py:30
Integration: dreame-vacuum
First occurred: 11:04:15 AM (1 occurrences)
Last logged: 11:04:15 AM

Error setting up entry Dreame Bot Z10 Pro for dreame_vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/dreame-vacuum/__init__.py", line 30, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by hdiessner** [comment]
Proposed change :

__init__.py - line 30

Replace with - await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
