### ISSUE TITLE
DreameBot X10 Error setting up entry

### ISSUE THREAD

**Issue by tieppm** [Tasshack/dreame-vacuum#152]
**Describe the bug**
Error setting up entry DreameBot X10 for dreame_vacuum

**To Reproduce**
install HACS 

**Expected behavior**

**Screenshots**

**Additional Information (please complete the following information)**
 - Model Name : dreame.vacuum.r2215
 - Firmware Version : 4.3.6_1411
 - Home Assistant Version: core-2022.7.6
 - Configuration Type [With or without map support]: both
 - Errors or warnings shown in the HA logs (if applicable):
Logger: homeassistant.config_entries
Source: custom_components/dreame_vacuum/__init__.py:30
Integration: Dreame Vacuum (documentation, issues)
First occurred: 4:13:27 PM (1 occurrences)
Last logged: 4:13:27 PM

Error setting up entry DreameBot X10 for dreame_vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/dreame_vacuum/__init__.py", line 30, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setups'
![image](https://github.com/Tasshack/dreame-vacuum/assets/42457105/ea27fde5-ce8a-40ef-9e45-3bd869b53dfc)

**Comment by tieppm** [comment]
Is there a way to not update hass and still be able to use it? this is the latest hass version of my box. My vacuum cleaner is the domestic version.  it was locked.  and hass is the only way to control it.  please help me.  Thank you very much

**Comment by tieppm** [comment]
yes.
Supported version for X10 is version Dec 18, 2022
, v0.16.1. 
This version needs Hassio version?
