### ISSUE TITLE
Failed setup, will retry since the last update?

### ISSUE THREAD

**Issue by Reudo** [Tasshack/dreame-vacuum#161]
**Describe the bug**
I have two dreame vacuums since about 4 months and the integration worked flawlessly since then.
Sadly now the integration tells me "failed setup, will retry" every few days.
I can fix that by turning the vacuums off and on again but they can also be controled via the Xiaomi Home App at all times.

So for me that is a problem with the integration?

**To Reproduce**
Not sure. Sometimes it is only one of the two and other times both at the same time.

**Additional Information (please complete the following information)**
 - Model Name [e.g. dreame.vacuum.p2028]: Z10 pro and L10s Ultra
 - Firmware Version [e.g. 1156]: Z10 Pro: 4.1.8_1156 , L10s Ultra: 4.3.3_2303
 - Home Assistant Version: Home Assistant 2023.7.2
 - Configuration Type [With or without map support]: with map support
 - Errors or warnings shown in the HA logs (if applicable):

 ```2023-07-16 22:25:45.667 ERROR (MainThread) [custom_components.dreame_vacuum] Update failed: Traceback (most recent call last):
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 314, in _async_update_data
    await self.hass.async_add_executor_job(self.device.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 995, in update
    self.connect_device()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 725, in connect_device
    self.info = DreameVacuumDeviceInfo(self._protocol.connect())
                                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 486, in connect
    response = self.send("miIO.info", retry_count=retry_count)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 518, in send
    return self.device.send(method, parameters=parameters, retry_count=retry_count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 161, in send
    self.send_handshake()
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 74, in send_handshake
    raise DeviceException("Unable to discover the device %s" % self.ip)
miio.exceptions.DeviceException: Unable to discover the device 192.168.1.184

2023-07-16 22:27:11.890 ERROR (MainThread) [custom_components.dreame_vacuum] Update failed: Traceback (most recent call last):
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 314, in _async_update_data
    await self.hass.async_add_executor_job(self.device.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 995, in update
    self.connect_device()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 725, in connect_device
    self.info = DreameVacuumDeviceInfo(self._protocol.connect())
                                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 486, in connect
    response = self.send("miIO.info", retry_count=retry_count)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 518, in send
    return self.device.send(method, parameters=parameters, retry_count=retry_count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 161, in send
    self.send_handshake()
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 74, in send_handshake
    raise DeviceException("Unable to discover the device %s" % self.ip)
miio.exceptions.DeviceException: Unable to discover the device 192.168.1.184

2023-07-16 22:28:37.395 DEBUG (Thread-106507) [custom_components.dreame_vacuum.dreame.map] Map update: 5
2023-07-16 22:28:37.408 DEBUG (Thread-106506) [custom_components.dreame_vacuum.dreame.device] Device update: 5
2023-07-16 22:28:37.849 ERROR (MainThread) [custom_components.dreame_vacuum] Update failed: Traceback (most recent call last):
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 314, in _async_update_data
    await self.hass.async_add_executor_job(self.device.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 995, in update
    self.connect_device()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 725, in connect_device
    self.info = DreameVacuumDeviceInfo(self._protocol.connect())
                                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 486, in connect
    response = self.send("miIO.info", retry_count=retry_count)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 518, in send
    return self.device.send(method, parameters=parameters, retry_count=retry_count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 161, in send
    self.send_handshake()
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 74, in send_handshake
    raise DeviceException("Unable to discover the device %s" % self.ip)
miio.exceptions.DeviceException: Unable to discover the device 192.168.1.184

2023-07-16 22:28:40.706 DEBUG (SyncWorker_1) [custom_components.dreame_vacuum.dreame.device] STATUS not supported: None
2023-07-16 22:28:40.706 DEBUG (SyncWorker_1) [custom_components.dreame_vacuum.dreame.device] STATUS not supported: None
2023-07-16 22:28:40.706 DEBUG (SyncWorker_1) [custom_components.dreame_vacuum.dreame.device] CHARGING_STATUS not supported: None
2023-07-16 22:28:40.707 DEBUG (SyncWorker_1) [custom_components.dreame_vacuum.dreame.device] CHARGING_STATUS not supported: None
2023-07-16 22:28:40.707 DEBUG (SyncWorker_1) [custom_components.dreame_vacuum.dreame.device] TASK_STATUS not supported: None
2023-07-16 22:28:40.707 DEBUG (SyncWorker_1) [custom_components.dreame_vacuum.dreame.device] STATUS not supported: None
2023-07-16 22:28:40.707 DEBUG (SyncWorker_1) [custom_components.dreame_vacuum.dreame.device] CHARGING_STATUS not supported: None
2023-07-16 22:28:40.708 DEBUG (SyncWorker_1) [custom_components.dreame_vacuum.dreame.device] CHARGING_STATUS not supported: None
2023-07-16 22:28:40.708 DEBUG (SyncWorker_1) [custom_components.dreame_vacuum.dreame.device] Device update: 5
2023-07-16 22:28:41.660 INFO (SyncWorker_1) [custom_components.dreame_vacuum.dreame.device] Connecting to device
2023-07-16 22:28:42.397 DEBUG (Thread-106508) [custom_components.dreame_vacuum.dreame.map] Map update: 5
2023-07-16 22:28:42.548 DEBUG (Thread-106509) [custom_components.dreame_vacuum.dreame.device] Device update: 5
2023-07-16 22:28:46.672 ERROR (MainThread) [custom_components.dreame_vacuum] Update failed: Traceback (most recent call last):
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 314, in _async_update_data
    await self.hass.async_add_executor_job(self.device.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 995, in update
    self.connect_device()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 725, in connect_device
    self.info = DreameVacuumDeviceInfo(self._protocol.connect())
                                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 486, in connect
    response = self.send("miIO.info", retry_count=retry_count)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 518, in send
    return self.device.send(method, parameters=parameters, retry_count=retry_count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 161, in send
    self.send_handshake()
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 74, in send_handshake
    raise DeviceException("Unable to discover the device %s" % self.ip)
miio.exceptions.DeviceException: Unable to discover the device 192.168.1.184

2023-07-16 22:28:46.676 DEBUG (MainThread) [custom_components.dreame_vacuum] Finished fetching dreame_vacuum data in 5.971 seconds (success: False)
2023-07-16 22:28:46.676 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Saugroboter EG' for dreame_vacuum integration not ready yet: Unable to discover the device 192.168.1.184; Retrying in background
2023-07-16 22:28:47.398 DEBUG (Thread-106510) [custom_components.dreame_vacuum.dreame.map] Map update: 5
2023-07-16 22:28:47.670 DEBUG (Thread-106511) [custom_components.dreame_vacuum.dreame.device] Device update: 5 ```

**Comment by Reudo** [comment]
Alright thank you for the response.
My router always shows a good connection and the ip is also static.

Not sure what else I can do at this moment but ty anyway.
