### ISSUE TITLE
Map render Failed

### ISSUE THREAD

**Issue by r-jean-pierre** [Tasshack/dreame-vacuum#166]
**Describe the bug**
Just switched to core-2023.8.0b0 and the map->image capability disappeared 

**To Reproduce**
Install core-2023.8.0b0

**Expected behavior**
Before everything was working fine, I even had on top to the map the real-time path of the vacuum displayed (+ capabity to select zones etc)

**Screenshots**
![image](https://github.com/Tasshack/dreame-vacuum/assets/9727894/d29da10e-17cd-4048-a88c-d5844138bb50)

**Additional Information (please complete the following information)**
 - Model Name [e.g. dreame.vacuum.p2028]: dreame.vacuum.p2009
 - Firmware Version [e.g. 1156]: 4.1.8_1132
 - Home Assistant Version: core-2023.8.0b0
 - Configuration Type [With map support]:
 - Errors or warnings shown in the HA logs (if applicable):

```
2023-07-27 00:21:33.113 ERROR (MainThread) [custom_components.dreame_vacuum.dreame.map] Map render Failed: Traceback (most recent call last):
File "/config/custom_components/dreame_vacuum/dreame/map.py", line 3744, in render_map
image = self.render_objects(
^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dreame_vacuum/dreame/map.py", line 3938, in render_objects
self._layers[MapRendererLayer.SEGMENTS][k] = self.render_segment(
^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dreame_vacuum/dreame/map.py", line 4624, in render_segment
tw, th = draw.textsize(text, text_font)
^^^^^^^^^^^^^
AttributeError: 'ImageDraw' object has no attribute 'textsize'
2023-07-27 00:21:33.195 ERROR (MainThread) [custom_components.dreame_vacuum.dreame.map] Map render Failed: Traceback (most recent call last):
File "/config/custom_components/dreame_vacuum/dreame/map.py", line 3744, in render_map
image = self.render_objects(
^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dreame_vacuum/dreame/map.py", line 3938, in render_objects
self._layers[MapRendererLayer.SEGMENTS][k] = self.render_segment(
^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dreame_vacuum/dreame/map.py", line 4624, in render_segment
tw, th = draw.textsize(text, text_font)
^^^^^^^^^^^^^
AttributeError: 'ImageDraw' object has no attribute 'textsize'
```

**Comment by jpconfessor** [comment]
Same problem here... after upgrading to Home Assistant 2023.8.0

**Comment by adamfeldman** [comment]
I additionally got `AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'`. Disabling `AI Obstacle` in addition to [these](https://github.com/Tasshack/dreame-vacuum/issues/166#issuecomment-1653429690) fixed it for me.

```
2023-08-04 17:18:21.723 ERROR (MainThread) [custom_components.dreame_vacuum.dreame.map] Map render Failed: Traceback (most recent call last):
File "/config/custom_components/dreame_vacuum/dreame/map.py", line 3744, in render_map
image = self.render_objects(
^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dreame_vacuum/dreame/map.py", line 4179, in render_objects
self._layers[MapRendererLayer.OBSTACLES] = self.render_obstacles(
^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dreame_vacuum/dreame/map.py", line 5003, in render_obstacles
(size * scale * scale, size * scale * scale), Image.ANTIALIAS)
^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```

**Comment by Filipe-PT** [comment]
Hi, the same thing happens here.


    Model name : dreame.vacuum.p2009

    Firmware Version: 4.1.8_1132

    Home assistant version: 2023.8.1
    Supervisor: 2023.07.1 
    Operating System: 10.4

 Configuration type [with map support]: Yes

    Errors:
 Logger: custom_components.dreame_vacuum.dreame.map
Source: custom_components/dreame_vacuum/dreame/map.py:3769
Integration: Dreame Vacuum (documentation, issues)
First occurred: 23:36:53 (3 occurrences)
Last logged in: 23:39:07
Map render Failed: Traceback (most recent call last): File "/config/custom_components/dreame_vacuum/dreame/map.py", line 3744, in render_map image = self.render_objects( ^^^^^^^^^^^ ^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/map.py", line 3938, in render_objects self._layers[MapRendererLayer.SEGMENTS][k] = self.render_segment( ^^^^ ^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/map.py", line 4624, in render_segment tw, th = draw.textsize(text, text_font) ^ ^^^^^^^^^^^^ AttributeError: 'ImageDraw' object has no attribute 'textsize'

Warnings:
dreame_vacuum::DreameVacuum is extending the deprecated base class VacuumEntity instead of StateVacuumEntity, this is not valid and will be unsupported from Home Assistant 2024.2. Please report it to the author of the 'dreame_vacuum' custom integration
  +
 Logger: custom_components.dreame_vacuum.dreame.protocol
Source: custom_components/dreame_vacuum/dreame/protocol.py:525
Integration: Dreame Vacuum (documentation, issues)
First occurred: 23:42:07 (1 occurrences)
Last logged in: 23:42:07
Error while executing request: https://de.api.io.mi.com/app/v2/home/rpc/521101217 HTTPSConnectionPool(host='de.api.io.mi.com', port=443): Read timeout. (read timeout=3)

Greeting

**Comment by z1022** [comment]
Can I hidden the highlighed items ?
<img width="331" alt="Screenshot 2023-08-06 002843" src="https://github.com/Tasshack/dreame-vacuum/assets/1883855/a047316f-4cbe-4a9b-b6d9-25fdc279f085">

**Comment by aviadlevy** [comment]
I can confirm that #175  solved the issue

**Comment by mkennel** [comment]
I'm having this same issue. My model is d10 plus.

**Comment by Guirigall** [comment]
> Looks like textsize function of the Pillow has depreciated on v10.0.0 which latest version of the HA requires. You can disable `Room Order` and `Room Name` (if you have custom named room) objects rendering from the integration configuration settings to get around this issue until I fix it.

That did the trick for me too. I guess that the zone operation will remain out of order until you fix it, right?

Thanks a lot for your work!

Jordi

**Comment by altmenorg** [comment]
Tried to disable Room Names and Room Order, but to no avail...
I'll have to wait for the update of the integration to upgrade HA, I guess !
@Tasshack : thanks for the wonderfull work, by the way ;)

**Comment by nisalvato** [comment]
> Same problem here... after upgrading to Home Assistant 2023.8.0 disabling Room Order and Room Name fixed for now ;)

I'm new to home assistants and have the same bug you fixed. Could you tell me how you disabled Room Order and Room Name?
Thank you

**Comment by Guirigall** [comment]
> > Same problem here... after upgrading to Home Assistant 2023.8.0 disabling Room Order and Room Name fixed for now ;)
> 
> I'm new to home assistants and have the same bug you fixed. Could you tell me how you disabled Room Order and Room Name? Thank you

You can do it pressing the "Configure" button of the device under the integration menu. The last selectable entry "Map objects":

 
![dreame_config](https://github.com/Tasshack/dreame-vacuum/assets/61776585/b044a392-a2ea-4c6f-8a09-78a3bf9394ae)

**Comment by nisalvato** [comment]
oh. Tks. it worked!

**Comment by rehashedsalt** [comment]
Can confirm, works as of `v1.0.0`
