### ISSUE TITLE
No connection with new firmware: 4.3.6_3015

### ISSUE THREAD

**Issue by stony2k** [Tasshack/dreame-vacuum#167]
I have read about the new firmware with the new edge mopping features, so I deleted the robot from the Mi Home App, resetted the WIFI and added it to the Dreame Home app. With only resetting the WIFI, the settings won't be deleted. Than I upgraded the firmware, deleted the robot vom the Dreeme Home app and added it back to the Mi Home app. There is no wifi issue, I can fully control the robot from the MI home app. I added my L10s ultra with the Xiaomi Miot Auto integration and have access to the robot with my Xiaomi Account.

But I have no luck with your integration with the new firmware. There where new issues before. Since I am new to Home Assistant, which logs (and where to find them) can I provide to analyze the problem? There is no general connection issue as described above. I also didn't finde any solution for a firmware downgrade.

<details><summary>Logfile</summary>
<p>

2023-07-29 12:00:38.825 ERROR (SyncWorker_4) [miio.miioprotocol] Got error when receiving: timed out
2023-07-29 12:00:38.832 ERROR (MainThread) [custom_components.dreame_vacuum] Update failed: Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 193, in send
data, addr = s.recvfrom(4096)
^^^^^^^^^^^^^^^^
TimeoutError: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 193, in send
data, addr = s.recvfrom(4096)
^^^^^^^^^^^^^^^^
TimeoutError: timed out
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/custom_components/dreame_vacuum/coordinator.py", line 314, in _async_update_data
await self.hass.async_add_executor_job(self.device.update)
File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dreame_vacuum/dreame/device.py", line 995, in update
self.connect_device()
File "/config/custom_components/dreame_vacuum/dreame/device.py", line 733, in connect_device
self._request_properties()
File "/config/custom_components/dreame_vacuum/dreame/device.py", line 262, in _request_properties
result = self._protocol.get_properties(props[:15])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 525, in get_properties
return self.send("get_properties", parameters=parameters, retry_count=retry_count)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 518, in send
return self.device.send(method, parameters=parameters, retry_count=retry_count)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 233, in send
return self.send(
^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 241, in send
raise DeviceException("No response from the device") from ex
miio.exceptions.DeviceException: No response from the device
2023-07-29 12:00:38.833 WARNING (MainThread) [homeassistant.config_entries] Config entry 'DreameBot L10s Ultra' for dreame_vacuum integration not ready yet: No response from the device; Retrying in background
2023-07-29 12:00:44.456 ERROR (SyncWorker_4) [miio.miioprotocol] Got error when receiving: timed out
2023-07-29 12:00:44.459 ERROR (MainThread) [custom_components.dreame_vacuum] Update failed: Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 193, in send
data, addr = s.recvfrom(4096)
^^^^^^^^^^^^^^^^
TimeoutError: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 193, in send
data, addr = s.recvfrom(4096)
^^^^^^^^^^^^^^^^
TimeoutError: timed out
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/custom_components/dreame_vacuum/coordinator.py", line 314, in _async_update_data
await self.hass.async_add_executor_job(self.device.update)
File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dreame_vacuum/dreame/device.py", line 995, in update
self.connect_device()
File "/config/custom_components/dreame_vacuum/dreame/device.py", line 733, in connect_device
self._request_properties()
File "/config/custom_components/dreame_vacuum/dreame/device.py", line 262, in _request_properties
result = self._protocol.get_properties(props[:15])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 525, in get_properties
return self.send("get_properties", parameters=parameters, retry_count=retry_count)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 518, in send
return self.device.send(method, parameters=parameters, retry_count=retry_count)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 233, in send
return self.send(
^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 241, in send
raise DeviceException("No response from the device") from ex
miio.exceptions.DeviceException: No response from the device
<details><summary>Details</summary>

</p>
</details>

**Comment by stony2k** [comment]
Tried this twice, logged in every time again. No luck so far. Would you
mind update your Dreame L10s (do you have one?) and test it for yourself?

Tasshack ***@***.***> schrieb am Sa. 29. Juli 2023 um 18:44:

**Comment by stony2k** [comment]
I can not add the device at all.

Tasshack ***@***.***> schrieb am Sa. 29. Juli 2023 um 23:15:

**Comment by stony2k** [comment]
The local IP has not changed, I confirmed it in my router settings and with a ping from the HA terminal to my local device IP. Both devices are on the same network. Everything worked fine before the firmware update. I would like to provide you further information for investigation.

I deleted the integration again, logged in with my credentials. My Dreame was selected, I had to choose which notification I would like to see, the map color scheme and card symbol. If I use the cloud connection, everything works (this explains why the Xiaomi Miot Auto integration works, it uses the cloud connection).

**Comment by saucedge** [comment]
Crud, wish I had checked this out before updating my l10s.  The standing advice is to hard reset the vacuum?  @stony2k did that work for you?

**Comment by stony2k** [comment]
A reset did not work. I switched to the beta version of this HA integration and used the Dreamehome login feature. This works without issues for me.
