### ISSUE TITLE
v2 b1 map unavailabe

### ISSUE THREAD

**Issue by tungmeister** [Tasshack/dreame-vacuum#192]
I've just migrated to the dreame login setup with my L10s ultra however the map is showing as unavailable, as is the current room:
![image](https://github.com/Tasshack/dreame-vacuum/assets/127809/90f5028d-7868-4665-9572-984e03e2c81d)
otherwise all functionality appears to be working as expected.

**Comment by tungmeister** [comment]
Sorry, was half asleep when I posted this:

```
Map data decompression failed: Error -5 while decompressing data: incomplete or truncated stream
Map update Failed: Traceback (most recent call last): File "/config/custom_components/dreame_vacuum/dreame/map.py", line 1196, in update self._request_current_map() File "/config/custom_components/dreame_vacuum/dreame/map.py", line 449, in _request_current_map return self._request_i_map(map_request_time) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/map.py", line 348, in _request_i_map self._add_map_data_file(object_name, self._last_robot_time) File "/config/custom_components/dreame_vacuum/dreame/map.py", line 699, in _add_map_data_file self._add_raw_map_data(response.decode(), timestamp, key) File "/config/custom_components/dreame_vacuum/dreame/map.py", line 702, in _add_raw_map_data return self._add_map_data(self._decode_map_partial(raw_map, timestamp, key)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/map.py", line 855, in _add_map_data ) = DreameVacuumMapDecoder.decode_map_data_from_partial( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/map.py", line 2985, in decode_map_data_from_partial saved_map_data = DreameVacuumMapDecoder.decode_saved_map( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/map.py", line 2642, in decode_saved_map return DreameVacuumMapDecoder.decode_map(raw_map, vslam_map, rotation)[0] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/map.py", line 2634, in decode_map return DreameVacuumMapDecoder.decode_map_data_from_partial( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/map.py", line 2976, in decode_map_data_from_partial wifi_map_data = DreameVacuumMapDecoder.decode_saved_map( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/map.py", line 2642, in decode_saved_map return DreameVacuumMapDecoder.decode_map(raw_map, vslam_map, rotation)[0] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^ TypeError: 'NoneType' object is not subscriptable
Send request map failed: Unable to discover the device over cloud
```

**Comment by scobby** [comment]
Maybe this is related and helps:

Logger: custom_components.dreame_vacuum.dreame.map
Source: custom_components/dreame_vacuum/dreame/map.py:3769
Integration: Dreame Vacuum ([documentation](https://github.com/Tasshack/dreame-vacuum), [issues](https://github.com/Tasshack/dreame-vacuum/issues))
First occurred: 23. August 2023 um 08:17:47 (8 occurrences)
Last logged: 08:22:18

Map render Failed: Traceback (most recent call last): File "/config/custom_components/dreame_vacuum/dreame/map.py", line 3744, in render_map image = self.render_objects( ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/map.py", line 3938, in render_objects self._layers[MapRendererLayer.SEGMENTS][k] = self.render_segment( ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/map.py", line 4624, in render_segment tw, th = draw.textsize(text, text_font) ^^^^^^^^^^^^^ AttributeError: 'ImageDraw' object has no attribute 'textsize'

**Comment by pannal** [comment]
I have something similar, using v1.0.0 while the vacuum is charging (without being done with the current run):
![image](https://github.com/Tasshack/dreame-vacuum/assets/1359593/a1c245f0-c9d3-4264-b721-774cb54f5a7d)

```
2023-08-25 12:25:04.904 WARNING (Thread-25335) [custom_components.dreame_vacuum.dreame.map] Send request map failed: No response from the device
2023-08-25 12:25:15.549 WARNING (Thread-25341) [custom_components.dreame_vacuum.dreame.protocol] Error while executing request: https://sg.api.io.mi.com/app/user/get_user_device_data HTTPSConnectionPool(host='sg.api.io.mi.com', port=443): Read timed out. (read timeout=3)
2023-08-25 12:25:15.549 WARNING (Thread-25341) [custom_components.dreame_vacuum.dreame.map] Getting object_name from cloud failed
```

Seems like a coincidence that the server is down during the first run using v1.0.0.
