### ISSUE TITLE
Dreame D10s Plus failed setup (list index out of range) in beta v2.0.0b1

### ISSUE THREAD

**Issue by DavideBoschi** [Tasshack/dreame-vacuum#196]
**Describe the bug**
Dreame D10s Plus failed setup (list index out of range) in beta v2.0.0b1

**To Reproduce**
When I tried to add my dreame d10s plus via dreamehome account, the procedure failed and I got the following message: Failed setup, will retry

![Screenshot 2023-08-25 181954](https://github.com/Tasshack/dreame-vacuum/assets/128826158/bd64fcca-a5f2-48fa-896a-6702dafac620)

**Additional Information (please complete the following information)**
 - Model Name [e.g. dreame.vacuum.p2028]: dreame d10s plus
 - Firmware Version [e.g. 1156]: 4.3.3_1201
 - Home Assistant Version: Home Assistant 2023.8.4
 - Configuration Type [With or without map support]: /
 - Errors or warnings shown in the HA logs (if applicable): 
 
   Logger: homeassistant.config_entries
   Source: config_entries.py:430
   First occurred: 18:43:50 (1 occurrences)
   Last logged: 18:43:50
   Config entry 'Bob' for dreame_vacuum integration not ready yet: list index out of range; Retrying in background

  Logger: homeassistant.config_entries
  Source: config_entries.py:952
  First occurred: 18:45:50 (1 occurrences)
  Last logged: 18:45:50
  Config entry 'Bob' for dreame_vacuum integration not ready yet: list index out of range; Retrying in background

  Logger: custom_components.dreame_vacuum
  Source: custom_components/dreame_vacuum/coordinator.py:476
  Integration: Dreame Vacuum (documentation, issues)
  First occurred: 18:43:50 (16 occurrences)
  Last logged: 18:55:34
  Integration start failed: list index out of range

**Comment by DavideBoschi** [comment]
Done, now I only have these two messages:

Logger: custom_components.dreame_vacuum
Source: custom_components/dreame_vacuum/coordinator.py:476
Integration: Dreame Vacuum (documentation, issues)
First occurred: 19:12:41 (4 occurrences)
Last logged: 19:13:25
Integration start failed: list index out of range

Logger: homeassistant.config_entries
Source: config_entries.py:952
First occurred: 19:12:41 (1 occurrences)
Last logged: 19:12:41
Config entry 'Bob' for dreame_vacuum integration not ready yet: list index out of range; Retrying in background

![Screenshot 2023-08-25 191329](https://github.com/Tasshack/dreame-vacuum/assets/128826158/da428d02-1af0-4a6c-a8b9-71cfe599a019)

I attached the full register file, if may be help

[home-assistant_2023-08-25T17-15-51.855Z.log](https://github.com/Tasshack/dreame-vacuum/files/12441988/home-assistant_2023-08-25T17-15-51.855Z.log)

**Comment by DavideBoschi** [comment]
Sorry, i didn't restart HA.
After the restart i got:


Logger: custom_components.dreame_vacuum
Source: custom_components/dreame_vacuum/coordinator.py:476
Integration: Dreame Vacuum (documentation, issues)
First occurred: 19:20:12 (2 occurrences)
Last logged: 19:20:19

Integration start failed: Traceback (most recent call last): File "/config/custom_components/dreame_vacuum/coordinator.py", line 471, in _async_update_data await self.hass.async_add_executor_job(self._device.update) File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1930, in update self.connect_device() File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1497, in connect_device self._request_properties() File "/config/custom_components/dreame_vacuum/dreame/device.py", line 461, in _request_properties return self._handle_properties(results) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/device.py", line 428, in _handle_properties callback[0](callback[1]) File "/config/custom_components/dreame_vacuum/coordinator.py", line 217, in _task_status_changed self._check_consumables() File "/config/custom_components/dreame_vacuum/coordinator.py", line 358, in _check_consumables self._check_consumable( File "/config/custom_components/dreame_vacuum/coordinator.py", line 323, in _check_consumable description = self._device.status.consumable_life_warning_description(property) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/device.py", line 6055, in consumable_life_warning_description if value != 0 and len(description[1]) > 1: ~~~~~~~~~~~^^^ IndexError: list index out of range

Logger: homeassistant.config_entries
Source: config_entries.py:430
First occurred: 19:20:12 (1 occurrences)
Last logged: 19:20:12

Config entry 'Bob' for dreame_vacuum integration not ready yet: list index out of range; Retrying in background

**Comment by DavideBoschi** [comment]
Ok, fantastic!! thank to you for your job!! 👍

**Comment by DavideBoschi** [comment]
Hi @Tasshack, any updates?

**Comment by DavideBoschi** [comment]
Just started testing, amazing!! Thank you very much! A coffee is coming!
