### ISSUE TITLE
Clean-spot and clean-segment services in 2.0.0beta2-3

### ISSUE THREAD

**Issue by chertvl** [Tasshack/dreame-vacuum#198]
**Describe the bug**
In 2.0.0beta2 and beta3  services eg. ```dreame_vacuum.vacuum_clean_spot``` and ```dreame_vacuum.vacuum_clean_segment``` doesnt works. Here are some log warnings attachet to this post.
I cant start clean from developer-tools page with call-service,  and from xiaomi-vacuum-map-card too.

**To Reproduce**
Try to use services.

**Additional Information (please complete the following information)**
 - Model Name [e.g. dreame.vacuum.p2028]: dreame.vacuum.p2187
 - Firmware Version [e.g. 1156]: 3.5.8_1010
 - Home Assistant Version: 2023.8.4
 - Configuration Type [With or without map support]: With map support.
 - Errors or warnings shown in the HA logs (if applicable):

Clean segment call try log:
<details>
`2023-08-26 17:00:17.772 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object has no attribute 'name'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
response_data = await self._async_run_long_action(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
return long_task.result()
^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 828, in handle_service
await service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
response_data = await _handle_entity_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
result = await task
^^^^^^^^^^
File "/config/custom_components/dreame_vacuum/vacuum.py", line 765, in async_clean_segment
await self._try_command(
File "/config/custom_components/dreame_vacuum/entity.py", line 167, in _try_command
await self.hass.async_add_executor_job(partial(func, *args, **kwargs))
File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dreame_vacuum/dreame/device.py", line 2853, in clean_segment
self._update_status(
File "/config/custom_components/dreame_vacuum/dreame/device.py", line 479, in _update_status
self._update_property(DreameVacuumProperty.TASK_STATUS, task_status.value)
File "/config/custom_components/dreame_vacuum/dreame/device.py", line 504, in _update_property
callback(current_value)
File "/config/custom_components/dreame_vacuum/coordinator.py", line 215, in _task_status_changed
self._fire_event(EVENT_TASK_STATUS, self._device.status.job)
^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dreame_vacuum/dreame/device.py", line 5858, in job
ATTR_CLEANING_MODE: self.cleaning_mode.name,
^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name'
2023-08-26 17:00:17.778 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139685990582592] Error handling message: Unknown error (unknown_error) chertvl from 192.168.1.40 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
await func(hass, connection, msg)
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 716, in handle_execute_script
response = await script_obj.async_run(msg.get("variables"), context=context)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1569, in async_run
return await asyncio.shield(run.async_run())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 420, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 470, in _async_step
self._handle_exception(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 493, in _handle_exception
raise exception
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
response_data = await self._async_run_long_action(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
return long_task.result()
^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 828, in handle_service
await service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
response_data = await _handle_entity_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
result = await task
^^^^^^^^^^
File "/config/custom_components/dreame_vacuum/vacuum.py", line 765, in async_clean_segment
await self._try_command(
File "/config/custom_components/dreame_vacuum/entity.py", line 167, in _try_command
await self.hass.async_add_executor_job(partial(func, *args, **kwargs))
File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dreame_vacuum/dreame/device.py", line 2853, in clean_segment
self._update_status(
File "/config/custom_components/dreame_vacuum/dreame/device.py", line 479, in _update_status
self._update_property(DreameVacuumProperty.TASK_STATUS, task_status.value)
File "/config/custom_components/dreame_vacuum/dreame/device.py", line 504, in _update_property
callback(current_value)
File "/config/custom_components/dreame_vacuum/coordinator.py", line 215, in _task_status_changed
self._fire_event(EVENT_TASK_STATUS, self._device.status.job)
^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dreame_vacuum/dreame/device.py", line 5858, in job
ATTR_CLEANING_MODE: self.cleaning_mode.name,
^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name'`
</details>

**Comment by chertvl** [comment]
> This is an issue with VSLAM vacuums not having a cleaning mode setting like the other vacuums.
> I will fix this and release v2.0.0b4.

Thank you, will try it.  Now 1.0.1 works good, thanks for the release.
Is my Dreame D9 Pro (with LDS) is VSLAM? )

**Comment by chertvl** [comment]
> https://github.com/Tasshack/dreame-vacuum/releases/tag/v2.0.0b4

Can confirm, it works!
Thank you.
