### ISSUE TITLE
Integration crashing on low water - L10S Ultra

### ISSUE THREAD

**Issue by MichelFR** [Tasshack/dreame-vacuum#206]
**Describe the bug**
When the water gets low the integration crashes and does not work anymore.

**To Reproduce**
Wait till the water is low.

**Expected behavior**
It should not crash and notify.

**Screenshots**
<img width="1723" alt="image" src="https://github.com/Tasshack/dreame-vacuum/assets/7061122/e97f6b44-5664-43d4-b195-f1a7f259f1e4">
<img width="926" alt="image" src="https://github.com/Tasshack/dreame-vacuum/assets/7061122/ba283d2c-9510-4731-a958-543c1043f452">

**Additional Information (please complete the following information)**
 - Model Name [e.g. dreame.vacuum.p2028]: L10S Ultra
 - Firmware Version [e.g. 1156]: 4.3.6_3018
 - Home Assistant Version: Home Assistant 2023.8.4
 - Configuration Type [With or without map support]: With map support
 - Errors or warnings shown in the HA logs (if applicable): Screenshots

**Comment by Zver5** [comment]
I fix the same problem

1. Model Name [e.g. dreame.vacuum.r2253]: X20 Pro plus
2. Firmware Version [e.g. 1156]: 4.3.6_1406
3. Home Assistant Version: Home Assistant 2023.9.2
4. Configuration Type [With or without map support]: With map support
5. Errors or warnings shown in the HA logs (if applicable): Log

2023-09-13 11:59:02.005 WARNING (MainThread) [custom_components.dreame_vacuum] Integration start failed: Traceback (most recent call last):
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 471, in _async_update_data
    await self.hass.async_add_executor_job(self._device.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1937, in update
    self.connect_device()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1497, in connect_device
    self._request_properties()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 461, in _request_properties
    return self._handle_properties(results)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 428, in _handle_properties
    callback[0](callback[1])
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 279, in _low_water_warning_changed
    low_water_warning = self._device.status.low_water_warning_description
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DreameVacuumDeviceStatus' object has no attribute 'low_water_warning_description'

2023-09-13 11:59:02.745 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Дюша Метёлкин' for dreame_vacuum integration not ready yet: 'DreameVacuumDeviceStatus' object has no attribute 'low_water_warning_description'; Retrying in background

**Comment by Zver5** [comment]
Adding water, rebooting the robot and Home assist solve the problem

**Comment by enkama** [comment]
Reappeared for me now.

```
2023-11-06 22:44:44.971 INFO (MainThread) [custom_components.dreame_vacuum] Integration loading: Dreamy
2023-11-06 22:44:44.972 INFO (MainThread) [custom_components.dreame_vacuum] Integration starting...
2023-11-06 22:44:47.855 WARNING (MainThread) [custom_components.dreame_vacuum] Integration start failed: Traceback (most recent call last):
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 471, in _async_update_data
    await self.hass.async_add_executor_job(self._device.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1990, in update
    self.connect_device()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1518, in connect_device
    self._request_properties()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 464, in _request_properties
    return self._handle_properties(results)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 431, in _handle_properties
    callback[0](callback[1])
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 282, in _low_water_warning_changed
    {EVENT_LOW_WATER: description[0], "code": low_water_warning.value},
                      ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'description' where it is not associated with a value
```

**Comment by DrBlokmeister** [comment]
> @enkama this will be fixed on `v2.0.0b7`.

ETA on release date? Rough estimate is OK (this week/next week/next month/early next year). This is something that my automations rely on, as my vacuums work based on area vacuumed today.

**Comment by DrBlokmeister** [comment]
It doesn't work for me. The integration doesn't crash, but the water level does not update after a refill. Restarting the integration does not work. I'll have a look later today to see how long it takes for the error to clear.
