### ISSUE TITLE
Service Calls with HA 2023.9.2 fail with "Call-service error. Device is not available"

### ISSUE THREAD

**Issue by baderas** [Tasshack/dreame-vacuum#219]
**Describe the bug**
With HA 2023.9.2 Service Calls to the dreame integration or dreame integration entities fail with "Call-service error. Device is not available", although the dreame vacuum is available.

An Example would be turn_off switch.roboname_customized_cleaning.

Works fine in 2023.9.1. Seems to be somehow introduced in version 2023.9.2.

**To Reproduce**
1) Upgrade HA to 2023.9.2
2) HA->Dev Tools -> Service
```
service: switch.turn_off
data: {}
target:
  entity_id: switch.roboname_customized_cleaning
```
-> won't work
3) Downgrade to 2023.9.1
4) try 2) again -> works

**Expected behavior**
Works in 2023.9.2 the same as in 2023.9.1

**Comment by baderas** [comment]
mhh.. I  see the same problems with 2023.9.1 now, I think the workaround might just to restart home assistant, I don't think its version dependant (sorry, I didn't get that at first). Or maybe due to downgrade some weird things happen.

Here are some snippets from my log:

service call:
```
homeassistant  | 2023-09-16 16:36:29.828 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139942563455936] Device is not available
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 227, in handle_call_service
homeassistant  |     await hass.services.async_call(
homeassistant  |   File "/usr/src/homeassistant/homeassistant/core.py", line 1969, in async_call
homeassistant  |     response_data = await coro
homeassistant  |                     ^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/core.py", line 2006, in _execute_service
homeassistant  |     return await target(service_call)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
homeassistant  |     return await service.entity_service_call(
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
homeassistant  |     response_data = await _handle_entity_call(
homeassistant  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
homeassistant  |     result = await task
homeassistant  |              ^^^^^^^^^^
homeassistant  |   File "/config/custom_components/dreame_vacuum/switch.py", line 454, in async_turn_off
homeassistant  |     await self.async_set_state(0)
homeassistant  |   File "/config/custom_components/dreame_vacuum/switch.py", line 474, in async_set_state
homeassistant  |     await self._try_command(
homeassistant  |   File "/config/custom_components/dreame_vacuum/entity.py", line 164, in _try_command
homeassistant  |     raise HomeAssistantError("Device is not available") from None
homeassistant  | homeassistant.exceptions.HomeAssistantError: Device is not available
```

I cannot recognize any other problems in the ha-logfile. In the journal I see that my vacuum sometime goes to unavailable (connection to dreame cloud lost maybe? reconnect of DSL?), but after few minutes ha recognizes its correct state again. But somehow at a service call ha still things its not available.
