### ISSUE TITLE
cannot access local variable 'description' where it is not associated with a value

### ISSUE THREAD

**Issue by sukesh1999** [Tasshack/dreame-vacuum#224]
**Describe the bug**
When the water tank level becomes 0, the integration is getting this local variable error and all the entities are becoming unavailable. 

**To Reproduce**
Insert an empty tank into the robot and it causes this issue. Fill up the tank and insert and this issue is gone

**Expected behavior**
A warning should appear saying the water tank is empty

**Additional Information (please complete the following information)**
 - Model Name : dreame.vacuum.r2253
 - Firmware Version : 4.3.6_1406
 - Home Assistant Version: Home Assistant 2023.9.2
 - Configuration Type :with map support dreame account - latest beta
 - Errors or warnings shown in the HA logs (if applicable):

2023-09-20 16:50:14.816 INFO (SyncWorker_9) [custom_components.dreame_vacuum.dreame.device] Property PET_FOCUSED_DETECTION Added: False
2023-09-20 16:50:14.816 INFO (SyncWorker_9) [custom_components.dreame_vacuum.dreame.device] Property AI_MACRO Added: False
2023-09-20 16:50:14.820 WARNING (MainThread) [custom_components.dreame_vacuum] Integration start failed: Traceback (most recent call last):
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 471, in _async_update_data
    await self.hass.async_add_executor_job(self._device.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1990, in update
    self.connect_device()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1518, in connect_device
    self._request_properties()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 464, in _request_properties
    return self._handle_properties(results)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 431, in _handle_properties
    callback[0](callback[1])
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 282, in _low_water_warning_changed
    {EVENT_LOW_WATER: description[0], "code": low_water_warning.value},
                      ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'description' where it is not associated with a value

**Comment by sukesh1999** [comment]
Hi @Tasshack , I would like to thank you a lot for your time and effort in developing this integration to this level. I would love to help you in testing new features and contributing to this integration.

**Comment by sukesh1999** [comment]
@Tasshack , i would love to donate and have tried to donate as well, but the 2 platforms ko-fe , paypal are not available in India. Can you check with them And provide an alternative and i will do the donation ASAP..
