### ISSUE TITLE
dreame.vacuum.r2210 support?

### ISSUE THREAD

**Issue by sephrioth** [Tasshack/dreame-vacuum#228]
**Describe the bug**
Can't rendering the map on HA.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Additional Information (please complete the following information)**
 - Model Name: dreame.vacuum.r2210
 - Firmware Version: Firmware: 4.3.6_1503
 - Home Assistant Version:  2023.09
 - Configuration Type : with map support
 - Errors or warnings shown in the HA logs (if applicable):
```
 Request map data from cloud failed https://cnbj2.fds.api.xiaomi.com/dreame.vacuum.mc1808.info/xxxxxx/1058468379/0?Expires=xxxxxx&GalaxyAccessKeyId=xxxxxx&Signature=xxxxxx&current=xxxxxx
Send request map failed: Unable to discover the device 192.168.199.34
Request map data from cloud failed https://cnbj2.fds.api.xiaomi.com/dreame.vacuum.mc1808.info/xxxxxx/1058468379/0?Expires=xxxxxx&GalaxyAccessKeyId=xxxxxx&Signature=xxxxxx&current=xxxxxx
Map data decompression failed: Error -3 while decompressing data: incorrect header check
Send request map failed: No response from the device
```

**Comment by yjamal01** [comment]
Experiencing the same issue. Can also no longer change selected map

**Comment by sephrioth** [comment]
@Tasshack Sorry to bother, I have installed the beta version but the map is still unavailable,  error log changed to :

`Map data decryption failed: Invalid IV size (0) for CBC.. Private key might be missing, please report this issue with your device model https://github.com/Tasshack/dreame-vacuum/issues/new?assignees=Tasshack&labels=bug&template=bug_report.md&title=Map%20data%20decryption%20failed`

**Comment by sephrioth** [comment]
Just updated to v2.0.0b6, but this still occurs.
`Map data decryption failed: Invalid IV size (0) for CBC.. Private key might be missing, please report this issue with your device model https://github.com/Tasshack/dreame-vacuum/issues/new?assignees=Tasshack&labels=bug&template=bug_report.md&title=Map%20data%20decryption%20failed`

**Comment by sephrioth** [comment]
Now it is completely unavailable in HA 2023.11.2 @Tasshack Please take a look, thanks!

`Integration start failed: Traceback (most recent call last): File "/config/custom_components/dreame_vacuum/coordinator.py", line 471, in _async_update_data await self.hass.async_add_executor_job(self._device.update) File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1990, in update self.connect_device() File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1518, in connect_device self._request_properties() File "/config/custom_components/dreame_vacuum/dreame/device.py", line 464, in _request_properties return self._handle_properties(results) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/device.py", line 431, in _handle_properties callback[0](callback[1]) File "/config/custom_components/dreame_vacuum/coordinator.py", line 282, in _low_water_warning_changed {EVENT_LOW_WATER: description[0], "code": low_water_warning.value}, ^^^^^^^^^^^ UnboundLocalError: cannot access local variable 'description' where it is not associated with a value`

**Comment by sephrioth** [comment]
Just updated to 2.0.0.b7,  the map is still not rendering

`Map render Failed: Traceback (most recent call last): File "/config/custom_components/dreame_vacuum/dreame/map.py", line 6122, in render_map image = self.render_objects( ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/map.py", line 6938, in render_objects cached_layers[layer] = self.render_charger( ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/map.py", line 7392, in render_charger icon_size = int(icon_size * 1.5) ^^^^^^^^^ UnboundLocalError: cannot access local variable 'icon_size' where it is not associated with a value`

**Comment by jcd420** [comment]
after new update. I can not install de botvac anymore. Before it worked with erros. now its like I dont have a botvac. erro I get is:

No supported devices found in this Xiaomi Miio cloud account on selected country.

but if I run python3 token_extractor.py . I get:

Devices found for server "cn" @ home "6001639705":
   ---------
   NAME:     Rose
   ID:       1058468772
   MAC:      70:C9:32:21:71:53
   IP:       192.168.100.141
   TOKEN:    42645935774434305a6b6d6570793 (the rest of token I removed for security reson on this site. HA is correct)
   MODEL:    dreame.vacuum.r2210
   ---------
