### ISSUE TITLE
Map Not availabe

### ISSUE THREAD

**Issue by cookie2512** [Tasshack/dreame-vacuum#229]
**Describe the bug**
The Integration is Not showing a map. Even in i try to reload oh reconfigure the Integration. 

**To Reproduce**
Permanent

**Expected behavior**
See the interactive map

**Screenshots**

https://ibb.co/mJ00y4g%0A
https://ibb.co/ZXSHKHB%0A
https://ibb.co/dt80s67%0A
https://ibb.co/QrdR83k%0A
https://ibb.co/w0HJDt3%0A
https://ibb.co/JKfgbwz
https://ibb.co/gM7x7tn

**Additional Information (please complete the following information)**
 - Model Name [e.g. dreame.vacuum.l10s ultra]:
 - Firmware Version [4.3.6_3030]:
 - Home Assistant Version: 2023.9.3
 - Configuration Type [Dreamehome Account]:
 - Errors or warnings shown in the HA logs (if applicable):

**Comment by cookie2512** [comment]
```

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.dreame_vacuum.dreame.map
Source: custom_components/dreame_vacuum/dreame/map.py:468
Integration: Dreame Vacuum (documentation, issues)
First occurred: 13:48:35 (1966 occurrences)
Last logged: 22:32:41

Request map data from cloud failed https://awsde0.fds.api.xiaomi.com/dreame-iot/dreame.vacuum.r2228o/SN038815/661348675/1?GalaxyAccessKeyId=EAKOK5QILPVZ6&Expires=1696194082710&Signature=JIqGLcBo82ZAVgLmc5lhZGruOWw=
Request map data from cloud failed https://awsde0.fds.api.xiaomi.com/dreame-iot/dreame.vacuum.r2228o/SN038815/661348675/9?GalaxyAccessKeyId=EAKOK5QILPVZ6&Expires=1696194098973&Signature=zeR663ihLNU/zHSURRum1s/eyjk=
Request map data from cloud failed https://awsde0.fds.api.xiaomi.com/dreame-iot/dreame.vacuum.r2228o/SN038815/661348675/1?GalaxyAccessKeyId=EAKOK5QILPVZ6&Expires=1696194114752&Signature=csMp8+3A6Fp0Ef5+Dy/zo/ZB7b0=
Request map data from cloud failed https://awsde0.fds.api.xiaomi.com/dreame-iot/dreame.vacuum.r2228o/SN038815/661348675/9?GalaxyAccessKeyId=EAKOK5QILPVZ6&Expires=1696194131050&Signature=Tkc4TW73A9rc2A+qlSIqSpBhK/Y=
Request map data from cloud failed https://awsde0.fds.api.xiaomi.com/dreame-iot/dreame.vacuum.r2228o/SN038815/661348675/1?GalaxyAccessKeyId=EAKOK5QILPVZ6&Expires=1696194146701&Signature=4scpTe/WpxxC4ZJ28QmOGHWezcw=

```

```

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.dreame_vacuum.dreame.protocol
Source: custom_components/dreame_vacuum/dreame/protocol.py:401
Integration: Dreame Vacuum (documentation, issues)
First occurred: 13:47:24 (5919 occurrences)
Last logged: 22:33:06

Unable to get file at https://awsde0.fds.api.xiaomi.com/dreame-iot/dreame.vacuum.r2228o/SN038815/661348675/9?GalaxyAccessKeyId=EAKOK5QILPVZ6&Expires=1696194155999&Signature=hwd4+YC49kHpHamyX6nEt8hpVgc=: HTTPSConnectionPool(host='awsde0.fds.api.xiaomi.com', port=443): Max retries exceeded with url: /dreame-iot/dreame.vacuum.r2228o/SN038815/661348675/9?GalaxyAccessKeyId=EAKOK5QILPVZ6&Expires=1696194155999&Signature=hwd4+YC49kHpHamyX6nEt8hpVgc= (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7efcd9d97fd0>: Failed to establish a new connection: [Errno -3] Try again'))
Unable to get file at https://awsde0.fds.api.xiaomi.com/dreame-iot/dreame.vacuum.r2228o/SN038815/661348675/9?GalaxyAccessKeyId=EAKOK5QILPVZ6&Expires=1696194155999&Signature=hwd4+YC49kHpHamyX6nEt8hpVgc=: HTTPSConnectionPool(host='awsde0.fds.api.xiaomi.com', port=443): Max retries exceeded with url: /dreame-iot/dreame.vacuum.r2228o/SN038815/661348675/9?GalaxyAccessKeyId=EAKOK5QILPVZ6&Expires=1696194155999&Signature=hwd4+YC49kHpHamyX6nEt8hpVgc= (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7efcd5713050>: Failed to establish a new connection: [Errno -3] Try again'))
Unable to get file at https://awsde0.fds.api.xiaomi.com/dreame-iot/dreame.vacuum.r2228o/SN038815/661348675/1?GalaxyAccessKeyId=EAKOK5QILPVZ6&Expires=1696194171541&Signature=d8+Rz7hDOaPph1u18A+jac44NcY=: HTTPSConnectionPool(host='awsde0.fds.api.xiaomi.com', port=443): Max retries exceeded with url: /dreame-iot/dreame.vacuum.r2228o/SN038815/661348675/1?GalaxyAccessKeyId=EAKOK5QILPVZ6&Expires=1696194171541&Signature=d8+Rz7hDOaPph1u18A+jac44NcY= (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7efcd5754f10>: Failed to establish a new connection: [Errno -3] Try again'))
Unable to get file at https://awsde0.fds.api.xiaomi.com/dreame-iot/dreame.vacuum.r2228o/SN038815/661348675/1?GalaxyAccessKeyId=EAKOK5QILPVZ6&Expires=1696194171541&Signature=d8+Rz7hDOaPph1u18A+jac44NcY=: HTTPSConnectionPool(host='awsde0.fds.api.xiaomi.com', port=443): Max retries exceeded with url: /dreame-iot/dreame.vacuum.r2228o/SN038815/661348675/1?GalaxyAccessKeyId=EAKOK5QILPVZ6&Expires=1696194171541&Signature=d8+Rz7hDOaPph1u18A+jac44NcY= (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7efcda042a90>: Failed to establish a new connection: [Errno -3] Try again'))
Unable to get file at https://awsde0.fds.api.xiaomi.com/dreame-iot/dreame.vacuum.r2228o/SN038815/661348675/1?GalaxyAccessKeyId=EAKOK5QILPVZ6&Expires=1696194171541&Signature=d8+Rz7hDOaPph1u18A+jac44NcY=: HTTPSConnectionPool(host='awsde0.fds.api.xiaomi.com', port=443): Max retries exceeded with url: /dreame-iot/dreame.vacuum.r2228o/SN038815/661348675/1?GalaxyAccessKeyId=EAKOK5QILPVZ6&Expires=1696194171541&Signature=d8+Rz7hDOaPph1u18A+jac44NcY= (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7efcdbbd9bd0>: Failed to establish a new connection: [Errno -3] Try again'))

```

**Comment by zipkiev** [comment]
Hi, I also have error with map, I have it today. Other buttons works. Vacuum .
Additional Information (please complete the following information)
Model Name dreame x20 pro plus [dreame.vacuum.r2253]:
Firmware Version [4.3.6_1406]:
Home Assistant Version: 2023.9.3
Configuration Type [Dreamehome Account]:
Errors or warnings shown in the HA logs (if applicable):


```
Logger: custom_components.dreame_vacuum.dreame.map
Source: custom_components/dreame_vacuum/dreame/map.py:5804
Integration: Dreame Vacuum ([documentation](https://github.com/Tasshack/dreame-vacuum), [issues](https://github.com/Tasshack/dreame-vacuum/issues))
First occurred: 23:17:29 (83 occurrences)
Last logged: 23:36:48

Map render Failed: Traceback (most recent call last): File "/config/custom_components/dreame_vacuum/dreame/map.py", line 5618, in render_map carpet = self.render_carpets( ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/map.py", line 8133, in render_carpets val = str(image[y_index, x_index]) ~~~~~^^^^^^^^^^^^^^^^^^ IndexError: index 442 is out of bounds for axis 0 with size 440
```

**Comment by cookie2512** [comment]
@Tasshack i'm Running HA in docker. Maybe this is the Problem. If I Open up the url in my Browser i can download the file.

**Comment by DIMMonchik** [comment]
I have another integration error - 
`Logger: custom_components.dreame_vacuum.dreame.protocol
Source: custom_components/dreame_vacuum/dreame/protocol.py:147
Integration: Dreame Vacuum (documentation, issues)
First occurred: 14:21:22 (1 occurrences)
Last logged: 14:21:22

Additional authentication required. Open following URL using device that has the same public IP, as your Home Assistant instance: https://account.xiaomi.com/identity/authStart?`

**Comment by marcocunha** [comment]
Hey,

I am also having problems showing the map (the other functions work properly, like start/stop cleaning).

Here is the log:
`
This error originated from a custom integration.

Logger: custom_components.dreame_vacuum.dreame.map
Source: custom_components/dreame_vacuum/dreame/map.py:3769
Integration: Dreame Vacuum (documentation, issues)
First occurred: September 28, 2023 at 11:45:57 (485 occurrences)
Last logged: 21:08:42

Map render Failed: Traceback (most recent call last): File "/config/custom_components/dreame_vacuum/dreame/map.py", line 3744, in render_map image = self.render_objects( ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/map.py", line 3938, in render_objects self._layers[MapRendererLayer.SEGMENTS][k] = self.render_segment( ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/map.py", line 4624, in render_segment tw, th = draw.textsize(text, text_font) ^^^^^^^^^^^^^ AttributeError: 'ImageDraw' object has no attribute 'textsize'`

**Comment by marcocunha** [comment]
> Hey,
> 
> I am also having problems showing the map (the other functions work properly, like start/stop cleaning).
> 
> Here is the log: ` This error originated from a custom integration.
> 
> Logger: custom_components.dreame_vacuum.dreame.map Source: custom_components/dreame_vacuum/dreame/map.py:3769 Integration: Dreame Vacuum (documentation, issues) First occurred: September 28, 2023 at 11:45:57 (485 occurrences) Last logged: 21:08:42
> 
> Map render Failed: Traceback (most recent call last): File "/config/custom_components/dreame_vacuum/dreame/map.py", line 3744, in render_map image = self.render_objects( ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/map.py", line 3938, in render_objects self._layers[MapRendererLayer.SEGMENTS][k] = self.render_segment( ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/map.py", line 4624, in render_segment tw, th = draw.textsize(text, text_font) ^^^^^^^^^^^^^ AttributeError: 'ImageDraw' object has no attribute 'textsize'`

Please ignore this, just updated to `v1.0.1` and the map is working again

**Comment by TRusselo** [comment]
this can happen if the robot dont recognize the room it starts in for some reason.
try running bot again, or if furniture/layout changes, re-run mapping process in vac app
