### ISSUE TITLE
[L10 Ultra/v2.0.0b6] Error when initializing L10 Ultra into the integration

### ISSUE THREAD

**Issue by PhilippeRaven** [Tasshack/dreame-vacuum#251]
**Describe the bug**
When adding my L10 ultra in HA, the connection with user/pass to the DreameHome account on EU servers seems ok, I validate the list of features I want, and then the initializing failed.

**Expected behavior**
Expect to add the L10 Ultra without problem.

**Screenshots**

**Screenshot of the integration's page :** 
![Screenshot from 2023-10-22 11-06-58](https://github.com/Tasshack/dreame-vacuum/assets/1235892/6096373e-a888-4eed-9eb4-165633ee777b)

**Two errors in the HA logs :** 

`This error originated from a custom integration.

Logger: custom_components.dreame_vacuum.dreame.protocol
Source: custom_components/dreame_vacuum/dreame/protocol.py:1265
Integration: Dreame Vacuum (documentation, issues)
First occurred: 11:00:16 AM (2 occurrences)
Last logged: 11:00:19 AM

Error while executing request: Read timed out. (read timeout=3): {"did":"638967545","id":1,"data":{"did":"638967545","id":1,"method":"get_properties","params":[{"did":"0","siid":2,"piid":1},{"did":"1","siid":2,"piid":2},{"did":"2","siid":3,"piid":1},{"did":"3","siid":3,"piid":2},{"did":"4","siid":4,"piid":1},{"did":"5","siid":4,"piid":2},{"did":"6","siid":4,"piid":3},{"did":"7","siid":4,"piid":4},{"did":"8","siid":4,"piid":5},{"did":"9","siid":4,"piid":6},{"did":"10","siid":4,"piid":7},{"did":"14","siid":4,"piid":11},{"did":"15","siid":4,"piid":12},{"did":"17","siid":4,"piid":14},{"did":"19","siid":4,"piid":16}]}}`

`This error originated from a custom integration.

Logger: custom_components.dreame_vacuum
Source: custom_components/dreame_vacuum/coordinator.py:476
Integration: Dreame Vacuum (documentation, issues)
First occurred: 11:00:19 AM (1 occurrences)
Last logged: 11:00:19 AM

Integration start failed: Traceback (most recent call last): File "/config/custom_components/dreame_vacuum/coordinator.py", line 471, in _async_update_data await self.hass.async_add_executor_job(self._device.update) File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1990, in update self.connect_device() File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1518, in connect_device self._request_properties() File "/config/custom_components/dreame_vacuum/dreame/device.py", line 459, in _request_properties result = self._protocol.get_properties(props[:15]) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 1265, in get_properties return self.send( ^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 1253, in send raise DeviceException( custom_components.dreame_vacuum.dreame.exceptions.DeviceException: Unable to discover the device over cloud`

**Additional Information (please complete the following information)**
 - Model Name : Should be dreame.vaccum.p2257 (L10 Ultra)
 - Firmware Version [e.g. 1156]: 4.3.3 1505
 - Home Assistant Version:  2023.7.3
 - Configuration Type : with map support
 - Errors or warnings shown in the HA logs (if applicable): cf above

**Comment by PhilippeRaven** [comment]
> Integration cannot reach to your device over the cloud and there is nothing I can do for that. Please check you can actually control the device from app and make sure there is nothing blocking the connection like a pihole.

Thanks for the quick reply.
The phone is connecting and perfectly controlling the device through the DreamHome app.

Can you confirm that the integration directly try to access the cloud account when I validate the user/pass and server region ?
If yes, so it can reach the cloud without a problem.
Does the "cannot access local variable 'description' where it is not associated with a value" message isn't a bit important ? Meaning something like "I can't retry a value from the cloud, then I can't initialize properly" ?

**Comment by PhilippeRaven** [comment]
Well, I just re-enabled the integration entry, and now it works ...
Guess there was a problem with the API earlier.

So sorry, and thanks for your work !
