### ISSUE TITLE
Errore since update

### ISSUE THREAD

**Issue by kisjeth** [Tasshack/dreame-vacuum#268]
I just updated the Core to 2023.11 and the vacuum cleaner is gone.

Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 21:51:23 (2 occurrences)
Last logged: 21:52:23

Error setting up entry Greg for dreame_vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/__init__.py", line 22, in async_setup_entry
    coordinator = DreameVacuumDataUpdateCoordinator(hass, entry=entry)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 125, in __init__
    persistent_notification.EVENT_PERSISTENT_NOTIFICATIONS_UPDATED,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'homeassistant.components.persistent_notification' has no attribute 'EVENT_PERSISTENT_NOTIFICATIONS_UPDATED'

**Comment by Tontze** [comment]
Same here :/

**Comment by HigxRBLX** [comment]
Same I thought it was just me and my vacuum was buggy or smth

**Comment by kisjeth** [comment]
Waiting for a solution I made a downgrade

**Comment by BrainStone** [comment]
Same issue for me.

**Comment by jpconfessor** [comment]
Looks like related to this change: https://github.com/home-assistant/core/pull/101975

**Comment by jpconfessor** [comment]
nevermind.. someone was faster! this is a duplicate of https://github.com/Tasshack/dreame-vacuum/issues/256

**Comment by TRusselo** [comment]
home-assistant\custom_components\dreame_vacuum\coordinator.py
change line 125 
From EVENT_PERSISTENT_NOTIFICATIONS_UPDATED
TO SIGNAL_PERSISTENT_NOTIFICATIONS_UPDATED
save file.
reboot home assistant.

working good for me now
