### ISSUE TITLE
Error setting up entry <name_vacuum> for dreame_vacuum

### ISSUE THREAD

**Issue by Gerritos2910** [Tasshack/dreame-vacuum#269]
Hi guys,

I am having trouble setting up my Dreame vacuum in my Home Assistant. It has been working before but I needed to redo all my Home Assistant setup. After implementing the Dreame-app and adding my vacuum via the Xiaomi-ID, I get the error message "Error setting up entry <name_vacuum> for dreame_vacuum".

The error logs show this:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/__init__.py", line 22, in async_setup_entry
    coordinator = DreameVacuumDataUpdateCoordinator(hass, entry=entry)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 125, in __init__
    persistent_notification.EVENT_PERSISTENT_NOTIFICATIONS_UPDATED,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'homeassistant.components.persistent_notification' has no attribute 'EVENT_PERSISTENT_NOTIFICATIONS_UPDATED'

Being an absolute n00b in Home Assistant, I have no idea what to do. Any suggestions from your side? :-/

Thanks in advance!

**Comment by jpconfessor** [comment]
duplicates #268
