### ISSUE TITLE
CONFIGURATION NOT WORKING

### ISSUE THREAD

**Issue by mattcrypps** [Tasshack/dreame-vacuum#270]
Today the Home Assistant dashboard tells me that the configuration is not working...
Is there anything you know?

**Comment by Henke19822** [comment]
Yes, I also get an error message, translated to English it states "Couldn't configure". All sensors are unavailable. 
Tried to restart the integration but no luck. 
The error might correlate to the last HA update (2023.11)

**Comment by gabry-ts** [comment]
me too, unfortunately there isnt much information about

**Comment by feinadam** [comment]
I have the same issue since yesterday HA update.

**Comment by Hiigaraa** [comment]
same here.

**Comment by Ot4eVash** [comment]
Same((

**Comment by Henke19822** [comment]
@Tasshack, maybe this should be categorized as an issue instead?

**Comment by oekinger** [comment]
Same for me, seems to be in correlation with HA update 2023.11

**Comment by adrien0595** [comment]
same here.

**Comment by delli87** [comment]
Same problem

**Comment by sajikur** [comment]
same here :(

**Comment by Savjee** [comment]
Seems indeed related to HA 2023.11.
Relevant log:

```
Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 12:35:08 (2 occurrences)
Last logged: 13:08:22

Error setting up entry Cinderella for dreame_vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/__init__.py", line 22, in async_setup_entry
    coordinator = DreameVacuumDataUpdateCoordinator(hass, entry=entry)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 125, in __init__
    persistent_notification.EVENT_PERSISTENT_NOTIFICATIONS_UPDATED,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'homeassistant.components.persistent_notification' has no attribute 'EVENT_PERSISTENT_NOTIFICATIONS_UPDATED'

```
