### ISSUE TITLE
Return a error.

### ISSUE THREAD

**Issue by djiesr** [Tasshack/dreame-vacuum#275]
After many month of good work, I got this error, some days ago.

Core 2023.11.0
Supervisor 2023.10.1
Operating System 11.1
Interface utilisateur 20231030.1

I Reinstall everting, but nothing work.

I can log on my account, but i only get that:

<img width="992" alt="image" src="https://github.com/Tasshack/dreame-vacuum/assets/31359825/eb9ee86d-348a-4813-b7a4-4498d029b89f">

Erreur:
2023-11-02 17:55:22.250 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Aspi for dreame_vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/__init__.py", line 22, in async_setup_entry
    coordinator = DreameVacuumDataUpdateCoordinator(hass, entry=entry)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 125, in __init__
    persistent_notification.EVENT_PERSISTENT_NOTIFICATIONS_UPDATED,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'homeassistant.components.persistent_notification' has no attribute 'EVENT_PERSISTENT_NOTIFICATIONS_UPDATED'

**Comment by djiesr** [comment]
Sorry, it's already signaled.
