### ISSUE TITLE
Can't start because of persistant notification ?

### ISSUE THREAD

**Issue by benavern** [Tasshack/dreame-vacuum#281]
**Describe the bug**
The dreame integration can't startup since (I have updated from raspberry2 to raspberry4 via a full backup & ) updated to the latest version of home assistant

**To Reproduce**
I can't tell if it is the hardware change or the ha update that produces the issue

**Expected behavior**
I would like to acces the entities again and be able to start vacuuming from ha & alexa again

**Screenshots**
![image](https://github.com/Tasshack/dreame-vacuum/assets/5999900/ba7bb500-0ba4-471d-b349-44ee86facd7f)

**Additional Information (please complete the following information)**
 - Model Name dreame.vacuum.p2008
 - Firmware Version 3.5.8_1050 (update available to 4.1.8_1107 but didn't update yet, should I ?)
 - Home Assistant Version: 
   - Core 2023.11.1
   - Supervisor 2023.10.1
   - Operating System 11.1
   - User interface 20231030.1
 - Configuration Type 
   - It was "without map", I tried to remove the integration and use "with map" but the error is the same
 - Errors or warnings shown in the HA logs

```
2023-11-04 20:11:04.717 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Don Dreame for dreame_vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/__init__.py", line 22, in async_setup_entry
    coordinator = DreameVacuumDataUpdateCoordinator(hass, entry=entry)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 125, in __init__
    persistent_notification.EVENT_PERSISTENT_NOTIFICATIONS_UPDATED,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by benavern** [comment]
OK, I just saw this PR after I published my issue.
Think the error is related ...

https://github.com/Tasshack/dreame-vacuum/pull/267

**Comment by benavern** [comment]
I updated to the beta version, it works like a charm.
Sorry for that and congrats to all the contributors ! 👍
