### ISSUE TITLE
Map cannot be updated live

### ISSUE THREAD

**Issue by rbforelle** [Tasshack/dreame-vacuum#3]
**Describe the bug**
Hi I can still not get my map live updated. The camera entity is updated every 3 seconds, but the map will only get updated after a long delay (several minutes). It doesn't help to restart HA or reset the device.

**Screenshots**
These 2 screenshots are taken nerely at the same time:
- Map from dreame-vacuum:
  <img src="https://user-images.githubusercontent.com/29765197/195392634-b8e6cc26-f1a2-4d0d-93bf-1d75255412cc.PNG" alt="Map from dreame-vacuum" width="150"/>
- Map from Xiaomi-Cloud-Map-Extractor:
  <img src="https://user-images.githubusercontent.com/29765197/195392654-3b279889-f5fd-4f68-a8a1-a49d7176232d.PNG" alt="Map from dreame-vacuum" width="150"/>
This map is updated with the following script every 5 seconds:
  ```
  service: xiaomi_miot.call_action
  data:
    entity_id: vacuum.dreame_p2027_27d7_robot_cleaner
    siid: 6
    aiid: 1
    params:
      - piid: 2
        value: "{\"req_type\":1,\"frame_type\":\"I\",\"force_type\":1}"
    throw: true
  ```
**Additional Information (please complete the following information)**
 - Model Name: dreame.vacuum.p2027
 - Firmware Version: 4.1.8_1092
 - Home Assistant Version: 20221010.0 - latest
 - Errors or warnings shown in the HA logs:
```
Logger: custom_components.dreame_vacuum.dreame.map
Source: custom_components/dreame_vacuum/dreame/map.py:435
Integration: Dreame Vacuum (documentation, issues)
First occurred: 16:55:51 (442 occurrences)
Last logged: 18:16:15

Map update Failed: get_device_property failed
Map update Failed: 'DreameVacuumDeviceStatus' object has no attribute 'silver_ion'
Send request map failed: No response from the device
```

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:515
First occurred: 16:54:47 (36 occurrences)
Last logged: 18:06:22

Update of camera.w10 is taking over 10 seconds
Update of sensor.cleargrass_dk1_bcd0_temperature_humidity_sensor is taking over 10 seconds
Update of sensor.lumi_v1_2624_temperature_humidity_sensor is taking over 10 seconds
Update of vacuum.dreame_p2027_27d7_robot_cleaner is taking over 10 seconds
```

```
Logger: custom_components.dreame_vacuum.dreame.protocol
Source: custom_components/dreame_vacuum/dreame/protocol.py:379
Integration: Dreame Vacuum (documentation, issues)
First occurred: 17:43:14 (2 occurrences)
Last logged: 17:43:27

Got error when receiving: timed out
```

```
Logger: root
Source: custom_components/dreame_vacuum/dreame/types.py:587
Integration: Dreame Vacuum ([documentation](https://github.com/Tasshack/dreame-vacuum), [issues](https://github.com/Tasshack/dreame-vacuum/issues))
First occurred: 16:55:12 (1 occurrences)
Last logged: 16:55:12

Uncaught thread exception
Traceback (most recent call last):
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 564, in _update_task
    self.update()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 939, in update
    raise DeviceUpdateFailedException(ex) from None
custom_components.dreame_vacuum.dreame.exceptions.DeviceUpdateFailedException: 'DreameVacuumDeviceStatus' object has no attribute 'silver_ion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 1378, in run
    self.function(*self.args, **self.kwargs)
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 570, in _update_task
    self._update_failed(ex)
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 557, in _update_failed
    self._error_callback(ex)
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 255, in async_set_update_error
    super().async_set_update_error(ex)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 292, in async_set_update_error
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/config/custom_components/dreame_vacuum/entity.py", line 112, in _handle_coordinator_update
    super()._handle_coordinator_update()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 348, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    available = self.available  # only call self.available once per update cycle
  File "/config/custom_components/dreame_vacuum/entity.py", line 147, in available
    return self.entity_description.available_fn(self.device)
  File "/config/custom_components/dreame_vacuum/dreame/types.py", line 587, in <lambda>
    DreameVacuumAction.RESET_SILVER_ION: lambda device: bool(device.status.silver_ion < 100),
AttributeError: 'DreameVacuumDeviceStatus' object has no attribute 'silver_ion'
```
```
Logger: custom_components.dreame_vacuum
Source: helpers/update_coordinator.py:290
Integration: Dreame Vacuum ([documentation](https://github.com/Tasshack/dreame-vacuum), [issues](https://github.com/Tasshack/dreame-vacuum/issues))
First occurred: 16:55:12 (1 occurrences)
Last logged: 16:55:12

Error requesting dreame_vacuum data: 'DreameVacuumDeviceStatus' object has no attribute 'silver_ion'
```
```
Logger: custom_components.dreame_vacuum.dreame.device
Source: custom_components/dreame_vacuum/dreame/device.py:567
Integration: Dreame Vacuum ([documentation](https://github.com/Tasshack/dreame-vacuum), [issues](https://github.com/Tasshack/dreame-vacuum/issues))
First occurred: 16:55:12 (1 occurrences)
Last logged: 16:55:12

Update Failed: 'DreameVacuumDeviceStatus' object has no attribute 'silver_ion'
```

**Comment by rbforelle** [comment]
Is map update still related to the cloud? Or it's updated locally? I have also seen some other warnings like:
```
Logger: custom_components.xiaomi_miot.vacuum
Source: custom_components/xiaomi_miot/__init__.py:1343
Integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues))
First occurred: 17:43:26 (2 occurrences)
Last logged: 18:01:56

w10(dreame.vacuum.p2027): Got MiioException while fetching the state: Unable to discover the device 192.168.1.130, mapping: {'vacuum.status': {'siid': 2, 'piid': 1}, 'vacuum.fault': {'siid': 2, 'piid': 2}, 'vacuum.mode': {'siid': 2, 'piid': 3}, 'clean_logs.first_clean_time': {'siid': 12, 'piid': 1}, 'clean_logs.total_clean_time': {'siid': 12, 'piid': 2}, 'clean_logs.total_clean_times': {'siid': 12, 'piid': 3}, 'clean_logs.total_clean_area': {'siid': 12, 'piid': 4}, 'audio.volume': {'siid': 7, 'piid': 1}, 'audio.voice_packet_id': {'siid': 7, 'piid': 2}, 'audio.voice_change_state': {'siid': 7, 'piid': 3}, 'audio.set_voice': {'siid': 7, 'piid': 4}, 'map.map_extend_data': {'siid': 6, 'piid': 4}, 'map.mult_map_state': {'siid': 6, 'piid': 7}, 'map.mult_map_info': {'siid': 6, 'piid': 8}, 'do_not_disturb.enable': {'siid': 5, 'piid': 1}, 'do_not_disturb.start_time': {'siid': 5, 'piid': 2}, 'do_not_disturb.end_time': {'siid': 5, 'piid': 3}, 'vacuum_extend.work_mode': {'siid': 4, 'piid': 1}, 'vacuum_extend.cleaning_time': {'siid': 4, 'piid': 2}, 'vacuum_extend.cleaning_area': {'siid': 4, 'piid': 3}, 'vacuum_extend.cleaning_mode': {'siid': 4, 'piid': 4}, 'vacuum_extend.mop_mode': {'siid': 4, 'piid': 5}, 'vacuum_extend.waterbox_status': {'siid': 4, 'piid': 6}, 'vacuum_extend.task_status': {'siid': 4, 'piid': 7}, 'vacuum_extend.clean_extend_data': {'siid': 4, 'piid': 10}, 'break_point_restart-4-11': {'siid': 4, 'piid': 11}, 'vacuum_extend.carpet_press': {'siid': 4, 'piid': 12}, 'vacuum_extend.serial_number': {'siid': 4, 'piid': 14}, 'vacuum_extend.remote_state': {'siid': 4, 'piid': 15}, 'vacuum_extend.clean_rags_tip': {'siid': 4, 'piid': 16}, 'vacuum_extend.keep_sweeper_time': {'siid': 4, 'piid': 17}, 'vacuum_extend.faults': {'siid': 4, 'piid': 18}, 'vacuum_extend.nation_matched': {'siid': 4, 'piid': 19}, 'vacuum_extend.relocation_status': {'siid': 4, 'piid': 20}, 'vacuum_extend.mop_status': {'siid': 4, 'piid': 25}, 'vacuum_extend.child_lock': {'siid': 4, 'piid': 27}, 'vacuum_extend.clean_cancel': {'siid': 4, 'piid': 30}, 'filter.filter_life_level': {'siid': 11, 'piid': 1}, 'filter.filter_left_time': {'siid': 11, 'piid': 2}, 'brush_left_time-10-1': {'siid': 10, 'piid': 1}, 'brush_life_level-10-2': {'siid': 10, 'piid': 2}, 'brush_cleaner.brush_left_time': {'siid': 9, 'piid': 1}, 'brush_cleaner.brush_life_level': {'siid': 9, 'piid': 2}, 'battery_level': {'siid': 3, 'piid': 1}, 'battery.charging_state': {'siid': 3, 'piid': 2}}, max_properties: 9/45
```
But the maps in app and from Xiaomi-Cloud-Map-Extractor can be updated relative stable and faster than dreame-vacuum integration.

**Comment by rbforelle** [comment]
Hi I have another small issue. Every time when I try to change robot settings such as suction level, I get this:
```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/dreame_vacuum/dreame/device.py:2495
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 2022年10月12日 23:01:35 (8 occurrences)
Last logged: 2022年10月12日 23:02:14

[1505654600] 'DreameVacuumDeviceStatus' object has no attribute 'wask_station_status'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 202, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 207, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 931, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 56, in async_select_option
    await entity.async_select_option(option)
  File "/config/custom_components/dreame_vacuum/select.py", line 598, in async_select_option
    await self._try_command(
  File "/config/custom_components/dreame_vacuum/entity.py", line 117, in _try_command
    await self.hass.async_add_executor_job(partial(func, *args, **kwargs))
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/dreame_vacuum/select.py", line 238, in <lambda>
    set_fn=lambda device, segment_id, value: device.set_segment_cleaning_times(
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1784, in set_segment_cleaning_times
    return self.set_cleanset(
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1705, in set_cleanset
    return self.update_map_data({"customeClean": cleanset})
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1500, in update_map_data
    self._property_changed()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 552, in _property_changed
    self._update_callback()
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 249, in async_set_updated_data
    super().async_set_updated_data(self.device)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 313, in async_set_updated_data
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/config/custom_components/dreame_vacuum/entity.py", line 112, in _handle_coordinator_update
    super()._handle_coordinator_update()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 348, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    available = self.available  # only call self.available once per update cycle
  File "/config/custom_components/dreame_vacuum/entity.py", line 147, in available
    return self.entity_description.available_fn(self.device)
  File "/config/custom_components/dreame_vacuum/button.py", line 131, in <lambda>
    device.status.washing_available or device.status.returning_to_wash_paused or device.status.washing_paused),
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 2525, in washing_available
    self.washing or
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 2495, in washing
    return bool(self.self_wash_base_available and self.wask_station_status is DreameVacuumSelfWashBaseStatus.WASHING)
AttributeError: 'DreameVacuumDeviceStatus' object has no attribute 'wask_station_status'
```

Is this something similar to the `silver_ion` before? w10 doesn't have a self-emptying function. Despite this error, the robot state can be updated on the map in like 5 seconds

**Comment by rbforelle** [comment]
The `wask_station_status` error doesn't occur anymore. Live map update also works without problem! Thanks for your update

**Comment by rbforelle** [comment]
The current delay is about 10 seconds, map on the app has a delay of ~4 seconds.

**Comment by rbforelle** [comment]
Yes the delay is measured without any external map refresh script. I do find some logs:
```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:533
First occurred: October 13, 2022 at 11:23:35 PM (1 occurrences)
Last logged: October 13, 2022 at 11:23:35 PM

Updating state for sensor.w10_cleaning_history (<class 'custom_components.dreame_vacuum.sensor.DreameVacuumSensorEntity'>) took 0.725 seconds. Please report it to the custom integration author.
```
```
This error originated from a custom integration.

Logger: custom_components.dreame_vacuum.dreame.protocol
Source: custom_components/dreame_vacuum/dreame/protocol.py:341
Integration: Dreame Vacuum (documentation, issues)
First occurred: October 13, 2022 at 7:11:25 PM (3 occurrences)
Last logged: October 13, 2022 at 11:11:08 PM

Got error when receiving: timed out
```
```
This error originated from a custom integration.

Logger: custom_components.dreame_vacuum
Source: helpers/update_coordinator.py:290
Integration: Dreame Vacuum (documentation, issues)
First occurred: October 13, 2022 at 2:25:20 PM (3 occurrences)
Last logged: October 13, 2022 at 11:10:33 PM

Error requesting dreame_vacuum data: get_device_property failed
Error requesting dreame_vacuum data: No response from the device
```
```
Logger: custom_components.dreame_vacuum.dreame.device
Source: custom_components/dreame_vacuum/dreame/device.py:569
Integration: Dreame Vacuum ([documentation](https://github.com/Tasshack/dreame-vacuum), [issues](https://github.com/Tasshack/dreame-vacuum/issues))
First occurred: October 13, 2022 at 7:11:25 PM (2 occurrences)
Last logged: October 13, 2022 at 11:10:33 PM

Update Failed: No response from the device
```
```
Logger: custom_components.dreame_vacuum.dreame.map
Source: custom_components/dreame_vacuum/dreame/map.py:921
Integration: Dreame Vacuum ([documentation](https://github.com/Tasshack/dreame-vacuum), [issues](https://github.com/Tasshack/dreame-vacuum/issues))
First occurred: October 13, 2022 at 10:06:34 PM (1 occurrences)
Last logged: October 13, 2022 at 10:06:34 PM

Send request map failed: No response from the device
```
I'm not sure if they are related to the issue since they didn't occur very often during cleaning. But the delay is somehow stable at around 10s, can also be up to 20s. You can tell me how to install the version with additional logs

**Comment by rbforelle** [comment]
Hi I have cloned the repo, checked out into test and copy the files in dreame_vacuum into config/custom_components/dreame_vacuum (old files were deleted at first). But I don't really see many logs.
The delay is always the same, about 8-10s, 4-5s slower than the app.

```
2022-10-14 23:17:23.443 WARNING (MainThread) [homeassistant.helpers.entity] Update of vacuum.dreame_p2027_27d7_robot_cleaner is taking over 10 seconds
2022-10-14 23:50:25.862 WARNING (MainThread) [homeassistant.helpers.entity] Update of vacuum.dreame_p2027_27d7_robot_cleaner is taking over 10 seconds
2022-10-14 23:50:44.613 ERROR (Thread-12775) [custom_components.dreame_vacuum.dreame.protocol] Got error when receiving: timed out
2022-10-14 23:52:57.434 WARNING (Thread-12835) [custom_components.dreame_vacuum.dreame.map] Map update Failed: get_device_property failed
2022-10-14 23:52:57.438 ERROR (Thread-12835) [custom_components.dreame_vacuum] Error requesting dreame_vacuum data: get_device_property failed
2022-10-14 23:56:54.820 WARNING (Thread-12954) [custom_components.dreame_vacuum.dreame.device] Update Failed: Unable to discover the device 192.168.1.130
2022-10-14 23:56:54.825 ERROR (Thread-12954) [custom_components.dreame_vacuum] Error requesting dreame_vacuum data: Unable to discover the device 192.168.1.130
2022-10-14 23:57:05.975 ERROR (Thread-12958) [custom_components.dreame_vacuum.dreame.protocol] Got error when receiving: timed out
2022-10-14 23:57:51.033 ERROR (Thread-12977) [custom_components.dreame_vacuum.dreame.protocol] Got error when receiving: timed out
2022-10-14 23:57:51.038 WARNING (Thread-12977) [custom_components.dreame_vacuum.dreame.device] Update Failed: No response from the device
2022-10-14 23:57:51.045 ERROR (Thread-12977) [custom_components.dreame_vacuum] Error requesting dreame_vacuum data: No response from the device
2022-10-14 23:58:27.367 WARNING (MainThread) [homeassistant.helpers.entity] Update of vacuum.dreame_p2027_27d7_robot_cleaner is taking over 10 seconds
2022-10-14 23:59:57.248 ERROR (Thread-13030) [custom_components.dreame_vacuum.dreame.protocol] Got error when receiving: timed out
2022-10-15 00:05:27.548 WARNING (MainThread) [homeassistant.helpers.entity] Update of vacuum.dreame_p2027_27d7_robot_cleaner is taking over 10 seconds
2022-10-15 00:05:34.815 ERROR (MainThread) [homeassistant.helpers.entity] Update for vacuum.dreame_p2027_27d7_robot_cleaner fails
2022-10-15 00:05:40.799 ERROR (Thread-13154) [custom_components.dreame_vacuum.dreame.protocol] Got error when receiving: timed out
2022-10-15 00:06:47.131 ERROR (Thread-13176) [custom_components.dreame_vacuum.dreame.protocol] Got error when receiving: timed out
2022-10-15 00:07:23.435 ERROR (Thread-13188) [custom_components.dreame_vacuum.dreame.protocol] Got error when receiving: timed out
2022-10-15 00:07:28.328 WARNING (MainThread) [homeassistant.helpers.entity] Update of vacuum.dreame_p2027_27d7_robot_cleaner is taking over 10 seconds
2022-10-15 00:08:27.873 WARNING (MainThread) [homeassistant.helpers.entity] Update of vacuum.dreame_p2027_27d7_robot_cleaner is taking over 10 seconds
2022-10-15 00:08:27.955 ERROR (MainThread) [custom_components.xiaomi_miot.vacuum] w10(dreame.vacuum.p2027): Got MiioException while fetching the state: Unable to discover the device 192.168.1.130, mapping: {'vacuum.status': {'siid': 2, 'piid': 1}, 'vacuum.fault': {'siid': 2, 'piid': 2}, 'vacuum.mode': {'siid': 2, 'piid': 3}, 'clean_logs.first_clean_time': {'siid': 12, 'piid': 1}, 'clean_logs.total_clean_time': {'siid': 12, 'piid': 2}, 'clean_logs.total_clean_times': {'siid': 12, 'piid': 3}, 'clean_logs.total_clean_area': {'siid': 12, 'piid': 4}, 'audio.volume': {'siid': 7, 'piid': 1}, 'audio.voice_packet_id': {'siid': 7, 'piid': 2}, 'audio.voice_change_state': {'siid': 7, 'piid': 3}, 'audio.set_voice': {'siid': 7, 'piid': 4}, 'map.map_extend_data': {'siid': 6, 'piid': 4}, 'map.mult_map_state': {'siid': 6, 'piid': 7}, 'map.mult_map_info': {'siid': 6, 'piid': 8}, 'do_not_disturb.enable': {'siid': 5, 'piid': 1}, 'do_not_disturb.start_time': {'siid': 5, 'piid': 2}, 'do_not_disturb.end_time': {'siid': 5, 'piid': 3}, 'vacuum_extend.work_mode': {'siid': 4, 'piid': 1}, 'vacuum_extend.cleaning_time': {'siid': 4, 'piid': 2}, 'vacuum_extend.cleaning_area': {'siid': 4, 'piid': 3}, 'vacuum_extend.cleaning_mode': {'siid': 4, 'piid': 4}, 'vacuum_extend.mop_mode': {'siid': 4, 'piid': 5}, 'vacuum_extend.waterbox_status': {'siid': 4, 'piid': 6}, 'vacuum_extend.task_status': {'siid': 4, 'piid': 7}, 'vacuum_extend.clean_extend_data': {'siid': 4, 'piid': 10}, 'break_point_restart-4-11': {'siid': 4, 'piid': 11}, 'vacuum_extend.carpet_press': {'siid': 4, 'piid': 12}, 'vacuum_extend.serial_number': {'siid': 4, 'piid': 14}, 'vacuum_extend.remote_state': {'siid': 4, 'piid': 15}, 'vacuum_extend.clean_rags_tip': {'siid': 4, 'piid': 16}, 'vacuum_extend.keep_sweeper_time': {'siid': 4, 'piid': 17}, 'vacuum_extend.faults': {'siid': 4, 'piid': 18}, 'vacuum_extend.nation_matched': {'siid': 4, 'piid': 19}, 'vacuum_extend.relocation_status': {'siid': 4, 'piid': 20}, 'vacuum_extend.mop_status': {'siid': 4, 'piid': 25}, 'vacuum_extend.child_lock': {'siid': 4, 'piid': 27}, 'vacuum_extend.clean_cancel': {'siid': 4, 'piid': 30}, 'filter.filter_life_level': {'siid': 11, 'piid': 1}, 'filter.filter_left_time': {'siid': 11, 'piid': 2}, 'brush_left_time-10-1': {'siid': 10, 'piid': 1}, 'brush_life_level-10-2': {'siid': 10, 'piid': 2}, 'brush_cleaner.brush_left_time': {'siid': 9, 'piid': 1}, 'brush_cleaner.brush_life_level': {'siid': 9, 'piid': 2}, 'battery_level': {'siid': 3, 'piid': 1}, 'battery.charging_state': {'siid': 3, 'piid': 2}}, max_properties: 9/45
2022-10-15 00:08:32.859 ERROR (Thread-13213) [custom_components.dreame_vacuum.dreame.protocol] Got error when receiving: timed out
2022-10-15 00:16:00.409 WARNING (Thread-13367) [custom_components.dreame_vacuum.dreame.map] Map update Failed: get_device_property failed
2022-10-15 00:24:50.681 WARNING (Thread-13475) [custom_components.dreame_vacuum.dreame.map] Map update Failed: get_device_property failed
```

**Comment by rbforelle** [comment]
[dreame_vacuum.log](https://github.com/Tasshack/dreame-vacuum/files/9792075/dreame_vacuum.log)

**Comment by rbforelle** [comment]
Yes I do set a xiaomi-vacuum-map-card to watch the run. I have also found that I used robot entity from Xiaomi Miot Auto before in the map card, but camera entity is from your integration. Maybe this affects the map update? I will disable robot entity from Xiaomi Miot Auto and test again today.

**Comment by rbforelle** [comment]
After disabled the robot entity from Xiaomi Miot Auto I get some perceptible performance improvements, the delay compared to the app is now reduced to 2-3s, the delay compared to the robot is 5-6s. This is quite acceptable for me 👍

**Comment by rbforelle** [comment]
Thanks for your update! Do I have to use the test or the master branch? I will check this out later today.

**Comment by rbforelle** [comment]
I have updated to the newest version, here are the logs. If you can't find anything wrong it's ok for me to close this issue.
[w10_b46af8b.log](https://github.com/Tasshack/dreame-vacuum/files/9815782/w10_b46af8b.log)
