### ISSUE TITLE
Current map stopt working

### ISSUE THREAD

**Issue by D43DBULL** [Tasshack/dreame-vacuum#305]
**Describe the bug**
Dream L10s Ultra current map won't reload. It stopt updating so i tried to disable it and eneble it again, but now it doesn't come back. Everything else works normal (so no connection issue). 

**To Reproduce**
I'm don't know much about programming, but in the log (see below) it looks like it got something to do with the carpet rendering. Which makes sense because it stopt updating when the vacuum was near/on carpet 

**Expected behavior**
Keep updating the current map

**Additional Information (please complete the following information)**
 - Model Name: dreame.vacuum.r2228o
 - Firmware Version : 4.3.9_3031
 - Home Assistant Version: core-2023.11.2
 - Configuration Type [With or without map support]: With map
 - Errors or warnings shown in the HA logs (if applicable):Logger: 
 
custom_components.dreame_vacuum.dreame.map
Source: custom_components/dreame_vacuum/dreame/map.py:6428
Integration: Dreame Vacuum ([documentation](https://github.com/Tasshack/dreame-vacuum), [issues](https://github.com/Tasshack/dreame-vacuum/issues))
First occurred: 11:37:56 (1 occurrences)
Last logged: 11:37:56

Map render Failed: Traceback (most recent call last): File "/config/custom_components/dreame_vacuum/dreame/map.py", line 5962, in render_map carpet = self.render_carpets( ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/map.py", line 8745, in render_carpets value = int(pixel_type[x, y]) ~~~~~~~~~~^^^^^^ IndexError: index 241 is out of

**Comment by Sakrapher** [comment]
Hi, i have the same Problem, disabeling Carpet Areas helped for now, thank you.
