### ISSUE TITLE
new model feature request

### ISSUE THREAD

**Issue by briiiian** [Tasshack/dreame-vacuum#307]
**Is your feature request related to a problem? Please describe.**
When I tried to log in to the app, the system prompted the following error message: “No supported devices found in this account on selected country.”

**Describe the solution you'd like**
I would like to add support for this device. I can provide the necessary information to help you test and add the device according to your needs.

**Additional context**
This is the device info
Model Name: dreame_vacuum_r9304
Firmware Version : 4.3.6_1207
Home Assistant Version: core-2023.11.2
Integration Version: v2.0.0b8

**Comment by briiiian** [comment]
I updated Integration Version to v2.0.0b8. and it can find my device, but after I complete the initial setup, it prompts me with “Unable to discover the device over cloud.”

this is log

Logger: custom_components.dreame_vacuum
Source: custom_components/dreame_vacuum/coordinator.py:495
Integration: Dreame Vacuum (documentation, issues)
First occurred: 16:54:23 (15 occurrences)
Last logged: 17:01:01

Integration start failed: Traceback (most recent call last): File "/config/custom_components/dreame_vacuum/coordinator.py", line 490, in _async_update_data await self.hass.async_add_executor_job(self._device.update) File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/device.py", line 2323, in update self.connect_device() File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1721, in connect_device self._request_properties() File "/config/custom_components/dreame_vacuum/dreame/device.py", line 541, in _request_properties result = self._protocol.get_properties(props[:15]) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 1295, in get_properties return self.send( ^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 1283, in send raise DeviceException( custom_components.dreame_vacuum.dreame.exceptions.DeviceException: Unable to discover the device over cloud

**Comment by briiiian** [comment]
yes, I can contral this device through app. btw, my device region is cn.

**Comment by briiiian** [comment]
yes, I've checked my network and it looks normal. and I find another error log.

此错误来自自定义集成。

Logger: custom_components.dreame_vacuum.dreame.protocol
Source: custom_components/dreame_vacuum/dreame/protocol.py:548
Integration: Dreame Vacuum (documentation, issues)
First occurred: 14:25:57 (28 occurrences)
Last logged: 14:37:16

Error while executing request: Read timed out. (read timeout=5): {"did":"760343054","id":986,"data":{"did":"760343054","id":986,"method":"get_properties","params":[{"did":"0","siid":2,"piid":1},{"did":"1","siid":2,"piid":2},{"did":"2","siid":3,"piid":1},{"did":"3","siid":3,"piid":2},{"did":"4","siid":3,"piid":3},{"did":"5","siid":4,"piid":1},{"did":"6","siid":4,"piid":2},{"did":"7","siid":4,"piid":3},{"did":"8","siid":4,"piid":4},{"did":"9","siid":4,"piid":5},{"did":"10","siid":4,"piid":6},{"did":"11","siid":4,"piid":7},{"did":"15","siid":4,"piid":11},{"did":"16","siid":4,"piid":12},{"did":"18","siid":4,"piid":14}]}}
Error while executing request: Read timed out. (read timeout=5): {"did":"760343054","id":350,"data":{"did":"760343054","id":350,"method":"get_properties","params":[{"did":"0","siid":2,"piid":1},{"did":"1","siid":2,"piid":2},{"did":"2","siid":3,"piid":1},{"did":"3","siid":3,"piid":2},{"did":"4","siid":3,"piid":3},{"did":"5","siid":4,"piid":1},{"did":"6","siid":4,"piid":2},{"did":"7","siid":4,"piid":3},{"did":"8","siid":4,"piid":4},{"did":"9","siid":4,"piid":5},{"did":"10","siid":4,"piid":6},{"did":"11","siid":4,"piid":7},{"did":"15","siid":4,"piid":11},{"did":"16","siid":4,"piid":12},{"did":"18","siid":4,"piid":14}]}}
Error while executing request: Read timed out. (read timeout=5): {"did":"760343054","id":975,"data":{"did":"760343054","id":975,"method":"get_properties","params":[{"did":"0","siid":2,"piid":1},{"did":"1","siid":2,"piid":2},{"did":"2","siid":3,"piid":1},{"did":"3","siid":3,"piid":2},{"did":"4","siid":3,"piid":3},{"did":"5","siid":4,"piid":1},{"did":"6","siid":4,"piid":2},{"did":"7","siid":4,"piid":3},{"did":"8","siid":4,"piid":4},{"did":"9","siid":4,"piid":5},{"did":"10","siid":4,"piid":6},{"did":"11","siid":4,"piid":7},{"did":"15","siid":4,"piid":11},{"did":"16","siid":4,"piid":12},{"did":"18","siid":4,"piid":14}]}}
Error while executing request: Read timed out. (read timeout=5): {"did":"760343054","id":166,"data":{"did":"760343054","id":166,"method":"get_properties","params":[{"did":"0","siid":2,"piid":1},{"did":"1","siid":2,"piid":2},{"did":"2","siid":3,"piid":1},{"did":"3","siid":3,"piid":2},{"did":"4","siid":3,"piid":3},{"did":"5","siid":4,"piid":1},{"did":"6","siid":4,"piid":2},{"did":"7","siid":4,"piid":3},{"did":"8","siid":4,"piid":4},{"did":"9","siid":4,"piid":5},{"did":"10","siid":4,"piid":6},{"did":"11","siid":4,"piid":7},{"did":"15","siid":4,"piid":11},{"did":"16","siid":4,"piid":12},{"did":"18","siid":4,"piid":14}]}}
Error while executing request: Read timed out. (read timeout=5): {"did":"760343054","id":449,"data":{"did":"760343054","id":449,"method":"get_properties","params":[{"did":"0","siid":2,"piid":1},{"did":"1","siid":2,"piid":2},{"did":"2","siid":3,"piid":1},{"did":"3","siid":3,"piid":2},{"did":"4","siid":3,"piid":3},{"did":"5","siid":4,"piid":1},{"did":"6","siid":4,"piid":2},{"did":"7","siid":4,"piid":3},{"did":"8","siid":4,"piid":4},{"did":"9","siid":4,"piid":5},{"did":"10","siid":4,"piid":6},{"did":"11","siid":4,"piid":7},{"did":"15","siid":4,"piid":11},{"did":"16","siid":4,"piid":12},{"did":"18","siid":4,"piid":14}]}}

**Comment by briiiian** [comment]
I reset device within app. and now it works. thx
