### ISSUE TITLE
Config flow could not be loaded

### ISSUE THREAD

**Issue by mzakharo** [Tasshack/dreame-vacuum#322]
**Describe the bug**
Unable to start Dreame Configuration flow
```
Error
Config flow could not be loaded: {"message":"Invalid handler specified"}
```

**To Reproduce**
Begin the configuration flow in Devices.

**Expected behavior**
No error/crash

**Screenshot**
![image](https://github.com/Tasshack/dreame-vacuum/assets/567867/37c6bd7e-0be2-42bf-8e31-cd86cdea5fbc)

**Additional Information (please complete the following information)**
 - Home Assistant Version:  2023.2.1
 - Errors or warnings shown in the HA logs (if applicable):
 ```
Unexpected exception importing platform custom_components.dreame_vacuum.config_flow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 749, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 766, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/dreame_vacuum/__init__.py", line 18, in <module>
    Platform.TIME,
  File "/usr/local/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: TIME
```

**Comment by ChessSpider** [comment]
try restarting home assistant and try again
