### ISSUE TITLE
integration can't load with 2023.12.0b0

### ISSUE THREAD

**Issue by ChristophCaina** [Tasshack/dreame-vacuum#328]
**Describe the bug**
running the current beta for HomeAssistant 2023.12 and the integration can't load.

**To Reproduce**
install current beta homeassistant 2023.12.0b0
this happens with v2.0.0b6 and v2.0.0b9

**Expected behavior**

**Screenshots**

**Additional Information (please complete the following information)**
```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.dreame_vacuum
Source: custom_components/dreame_vacuum/coordinator.py:476
Integration: Dreame Vacuum (documentation, issues)
First occurred: 10:18:15 (22 occurrences)
Last logged: 10:46:28

Integration start failed: Traceback (most recent call last): File "/config/custom_components/dreame_vacuum/coordinator.py", line 471, in _async_update_data await self.hass.async_add_executor_job(self._device.update) File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1990, in update self.connect_device() File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1518, in connect_device self._request_properties() File "/config/custom_components/dreame_vacuum/dreame/device.py", line 459, in _request_properties result = self._protocol.get_properties(props[:15]) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 1265, in get_properties return self.send( ^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 1253, in send raise DeviceException( custom_components.dreame_vacuum.dreame.exceptions.DeviceException: Unable to discover the device over cloud
Integration start failed: Traceback (most recent call last): File "/config/custom_components/dreame_vacuum/coordinator.py", line 471, in _async_update_data await self.hass.async_add_executor_job(self._device.update) File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1993, in update raise DeviceUpdateFailedException("Device cannot be reached") from None custom_components.dreame_vacuum.dreame.exceptions.DeviceUpdateFailedException: Device cannot be reached
```

**Comment by kirillovserg** [comment]
This problem occurred today at 09:27:17 GMT. It also appears on OS version 2023.11.1. Suddenly access was lost and it no longer connects. v2.0.0b9.

```
Logger: custom_components.dreame_vacuum
Source: custom_components/dreame_vacuum/coordinator.py:495
Integration: Dreame Vacuum (documentation, issues)
First occurred: 12:27:17 (19 occurrences)
Last logged: 13:16:00

Integration start failed: Traceback (most recent call last): File "/config/custom_components/dreame_vacuum/coordinator.py", line 490, in _async_update_data await self.hass.async_add_executor_job(self._device.update) File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/device.py", line 2329, in update self.connect_device() File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1727, in connect_device self._request_properties() File "/config/custom_components/dreame_vacuum/dreame/device.py", line 541, in _request_properties result = self._protocol.get_properties(props[:15]) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 1295, in get_properties return self.send( ^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 1283, in send raise DeviceException( custom_components.dreame_vacuum.dreame.exceptions.DeviceException: Unable to discover the device over cloud
```

**Comment by tpieczka** [comment]
The same...

**Comment by tpieczka** [comment]
Yes its working now

czw., 30.11.2023, 13:02 użytkownik kirillovserg ***@***.***>
napisał:

**Comment by ChristophCaina** [comment]
ok, yes, seems to be an issue with the cloud... was just a bad timing that it hit me after updating to the HA beta :D
