### ISSUE TITLE
[L10S Ultra] Fails to start integration when "Prefer cloud connection" is unchecked

### ISSUE THREAD

**Issue by MacDada** [Tasshack/dreame-vacuum#342]
When the `Prefer cloud connection` configuration option is **un**checked, the integration fails to start.
It's working when I do check this option (I'd prefer to get rid of the cloud entirely, BTW).

 - Model Name: dreame.vacuum.r2228o (L10s Ultra)
 - Firmware Version: 4.3.9_3031
 - Home Assistant Version: 2023.12.1
 - Configuration Type: With map support

Logs:

```
2023-12-13 03:45:39.917 WARNING (MainThread) [custom_components.dreame_vacuum] Integration start failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 193, in send
    data, addr = s.recvfrom(4096)
                 ^^^^^^^^^^^^^^^^
TimeoutError: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 193, in send
    data, addr = s.recvfrom(4096)
                 ^^^^^^^^^^^^^^^^
TimeoutError: timed out
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 326, in _async_update_data
    await self.hass.async_add_executor_job(self.device.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 996, in update
    self.connect_device()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 733, in connect_device
    self._request_properties()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 262, in _request_properties
    result = self._protocol.get_properties(props[:15])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 543, in get_properties
    return self.send("get_properties", parameters=parameters, retry_count=retry_count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 536, in send
    return self.device.send(method, parameters=parameters, retry_count=retry_count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 233, in send
    return self.send(
           ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 241, in send
    raise DeviceException("No response from the device") from ex
miio.exceptions.DeviceException: No response from the device
```

**Comment by MacDada** [comment]
> check the vacuum and HA is at the same network subnet

they are

> probably you have previously installed your device to the Dreamehome App for getting the firmware updates and then you have switched to the Mi Home app without hard resetting the device

yeah, i did just that. i mean, i did switch apps, resetted the vacuum with the pin - but i'm not sure if this is a "hard" reset (it erased maps for example)

> Device disables the local api when it is installed to the Dreamehome App and it does not re-enabled when reinstalled to the Mi Home app again. Only way to re-enable the local api is hard resetting the device.

👍 I will google _hard_ resetting and try again, thanks!

> closed this as [completed](https://github.com/Tasshack/dreame-vacuum/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [5 hours ago](https://github.com/Tasshack/dreame-vacuum/issues/342#event-11231742586)

I'd argue this is still a bug -> as there is no information for the user. If this situation can be somehow detected, it would be great to propose the user the solution. If not, than at least a warning next to the checkbox would be nice. Or at least some kind info in the README.md ;)

**Comment by MacDada** [comment]
> This issue can happen with multiple resons so there is no way to tell why the integration cannot reach to the device, it is same as like the device turned of completely.

ok, i was hoping that there could be some kind of artefact to detect -> like there would be a connection to the device, but with access revoked or sth -> so it would be distinguishable from a simple lack of connection (offline, etc).

> Not all vacuums can be installed to the Dreamehome app also switching between apps back and forth is not a normal user behaviour and not forseen even by Dreame engineers

That's actually a surprise to me o.O If the device can be used by both apps, then one must assume that ppl will be switching to check which one is better. I mean, they have to put some effort to develop it for 2 apps/envs anyway, then why bother, if nobody is supposed to be choosing between them :P

Dreame being bought by Xiaomi, etc. - history I guess.

Anyway, in my case it was like this:
1. bought device
2. installed the official Dreame app
3. decided to integrate with HomeAssistant
4. wtf that I need Xiaomi cloud for that :P
5. reseting device to Xiaomi app

> they did not test this and has forgotten to add to code for re-enabling the local api from the device firmware

"forgotten" xd i'm starting to create a conspiracy theory in my mind… xd

> Please do not forget that the warning you wanted to see must be short enough to fit to the mobile phone screen

I can only feel pity for people wanting to do anything more complicated than turning on a light using a smartphone :D Configuring integrations, automations, checking up the logs -> I do it on desktop. But, ok, I will keep them poor bastards in mind ;)

> Don't forget that integration also constantly sends requests to the cloud for getting the map data even you disable Prefer Cloud option so using Dreamehome app will also prevent that too even it requires constant cloud communication.

That's one of the reasons I'm planning on switching to Valetudo in the future ;)

Anyway, big thanks for your amazing work with this integration! Every time I see OSS like that I cannot believe how other programmers find courage and time to make a working project, and fight obstacles put by companies in the way!

**Comment by Shm1ks** [comment]
> Please check the vacuum and HA is at the same network subnet and if already is, probably you have previously installed your device to the Dreamehome App for getting the firmware updates and then you have switched to the Mi Home app without hard resetting the device. Device disables the local api when it is installed to the Dreamehome App and it does not re-enabled when reinstalled to the Mi Home app again. Only way to re-enable the local api is hard resetting the device.

Hello, how to hard resetting the device? (Dreamebot X10 pro)

**Comment by T-Grave** [comment]
I'm wondering this too. When I search Google for hard reset procedures all I can find is pressing the reset button (under cover) for 3 seconds. Which is what I die before I added it to the Mi app. It's on the same subnet, so the fact it isn't working probably means I'm not correctly resetting?

**Comment by Shm1ks** [comment]
Hell

> I'm wondering this too. When I search Google for hard reset procedures all I can find is pressing the reset button (under cover) for 3 seconds. Which is what I did before I added it to the Mi app. It's on the same subnet, so the fact it isn't working probably means I'm not correctly resetting?

Hello, did you succeed?

**Comment by ghmeister** [comment]
> I cannot confirm this but Dreame may have actually disabled the local Api from some devices. If that was the case, you wont be able to use this integration without `Prefer cloud connection` so I suggest switching to the Dreamehome App which works better with the integration instead of enabling cloud connection to Miio Api.

It seems that my latest firmware update (I was using the Xiomi Miio App before) indeed removed the local API. Is there anything I can do to reactivagte it (different firmware?)? I guess, switching to the Dreamehome App now won't make a difference anymore

**Comment by ghmeister** [comment]
> If you cannot enable the local api again switching to the Dreamehome will make difference because Dreamehome uses a socket api that would eliminate the requirement of sending periodic requests to cloud from integration. Also you can use the camera streaming feature with the Dreamehome (not with the integration yet).
> 
> Using Dreamehome is better for the integration than using Mi Home with `Prefer Cloud Connection`. Option is just there for the vacuums cannot be added to the Dreamehome cloud.

Thanks for the explanation. I switched to the Dreamehome app, but the Integration still does not work. I removed the old Dreame device and tried to set up a new one in HA. After the first screen (asking for my Xiami Cloud credentials), a second screen comes up, asking for the device's IP address and Token. It's already filled correctly (obviously stored by HA somewhere), but it won't let me connect ("Connection failed"). Any ideas?

**Comment by ghmeister** [comment]
Ahh, got it. Just installed it, and it works, thanks!

**Comment by StayPirate** [comment]
My L10s Ultra has always been connected to the Mi Home app (Xiaomi) and I've been using it with this integration (non-Beta) since the beginning. Last week I updated the firmware (the upgrade was provided within the Mi Home iOS app), after that the integration stopped to work. My best guess is that Xiaomi really killed local APIs with this update.

I now followed @Tasshack suggestion and connected the robot to the Dreame infrastructure, I updated the HA integration to the latest beta and everything started to work again :).

I do have a question, you mentioned that by using the Dreame login there would be an mqtt server support:

> Dreamehome cloud does not have local communication support but instead it has an mqtt server for supporting push messages so the integration does not need to send requests to the cloud constantly for getting updates.

Do I need to apply any manual configuration in order to get it work? Or would the beta version make use of it automatically?

**Comment by StayPirate** [comment]
Even though we all agree that fully local management is the holy grail... this mqtt quick update is interesting and a very good thing to have.

When you say

> When cloud gets a write request from vacuum it broadcasts it over mqtt

do you mean that when the vacuum sends a write request to the cloud, it also broadcasts it over mqtt in the LAN. Am I correct?

Thanks for all your support and the kind clarification 🙏🏼
