### ISSUE TITLE
On Dreame L20 Ultra Complete setting Cleaning Mode to "sweeping" doesn't work

### ISSUE THREAD

**Issue by martiesim** [Tasshack/dreame-vacuum#346]
**Describe the bug**
I have a Dreame L20 Ultra and when I set the entity Cleaning Mode to "sweeping" I get an error message:
"Cannot set sweeping while mop pads are installed"

**Expected behavior**
Since the robot automatically leaves the mops in the station if it doesn't need them, this setting should be accessible.

If I set this setting in the dreame home app, the entity correctly updates but if I change the entity to something else again, it won't allow me to change it back to "sweeping". I can only set that value via the dreame home app.

**Additional Information (please complete the following information)**
 - Model Name: dreame.vacuum.r2253c (L20 Ultra Complete)
 - Firmware Version: 4.3.6_1510
 - Home Assistant Version:
   - Core: 2023.12.3
   - Supervisor: 2023.11.6
   - Operating System: 11.2
   - Frontend: 20231208.2
 - Configuration Type: With map support
 - Errors or warnings shown in the HA logs (if applicable):
```
Source: custom_components/dreame_vacuum/entity.py:178
Unable to call Cannot set sweeping while mop pads are installed

Source: components/websocket_api/commands.py:238
[545240541376] Cannot set sweeping while mop pads are installed

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 878, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 106, in async_select_option
    await entity.async_select_option(option)
  File "/config/custom_components/dreame_vacuum/select.py", line 977, in async_select_option
    await self._try_command(
  File "/config/custom_components/dreame_vacuum/entity.py", line 179, in _try_command
    raise HomeAssistantError(str(exc)) from None
homeassistant.exceptions.HomeAssistantError: Cannot set sweeping while mop pads are installed
```

**Comment by martiesim** [comment]
Never mind, HACS just offered me an update for the integration and now it works. Should've checked that first, I guess. Sorry
