### ISSUE TITLE
Invalid Size For Cleaning Sequence

### ISSUE THREAD

**Issue by tango2590** [Tasshack/dreame-vacuum#350]
**Describe the bug**
When using the `dreame_vacuum.vacuum_set_cleaning_sequence` service, it fails regardless of the room numbers entered. I've tried entering all room numbers as mentioned in the docs with no success. I did merge a room after the integration was created, so Room 3 no longer exists, and it errors out when it's present in the segment list. Calling the service without Room 3 doesn't show an error on the screen (even Node-RED completes it without an issue), but the error is present in the logs. I have 8 rooms and all 8 rooms are listed in the segment list with no success.

**To Reproduce**
Attempt to set a cleaning sequence.

**Expected behavior**
Cleaning sequence should be set.

**Screenshots**

**Additional Information (please complete the following information)**
 - Model Name [e.g. dreame.vacuum.p2028]: dreame.vacuum.r2228o
 - Firmware Version [e.g. 1156]: 4.3.3_2401
 - Home Assistant Version: 2023.12.3
 - Configuration Type [With or without map support]: With map support
 - Errors or warnings shown in the HA logs (if applicable):

```
Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:468
First occurred: 15:14:09 (3 occurrences)
Last logged: 15:18:35

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Invalid size for cleaning sequence
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 833, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 878, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/vacuum.py", line 694, in async_set_cleaning_sequence
    await self._try_command(
  File "/config/custom_components/dreame_vacuum/entity.py", line 123, in _try_command
    raise ValueError(str(exc)) from None
ValueError: Invalid size for cleaning sequence

```

**Comment by tango2590** [comment]
I tried redownloading and using the latest beta with no luck. The service call doesn't fail anymore and no errors in the logs, but when I check the current state of `switch.dreamebot_cleaning_sequence`, it still shows an old sequence and not the new one.
