### ISSUE TITLE
Cannot perform initial setup of L10s Ultra with Beta 11 and Dreamehome Account

### ISSUE THREAD

**Issue by Vaskivskyi** [Tasshack/dreame-vacuum#369]
**Describe the bug**

Hello

Cannot add my new L10s Ultra in the latest beta 11 (using a Dreamehome account). This is my first usage of the integration, so I cannot say anything more. It just does not start after the setup. No entities were created as well

```
2024-01-16 18:13:39.280 INFO (MainThread) [custom_components.dreame_vacuum] Integration loading: Eve
2024-01-16 18:13:39.281 INFO (MainThread) [custom_components.dreame_vacuum] Integration starting...
2024-01-16 18:13:39.284 DEBUG (SyncWorker_4) [custom_components.dreame_vacuum.dreame.device] Device update: 5
2024-01-16 18:13:39.421 INFO (SyncWorker_4) [custom_components.dreame_vacuum.dreame.device] Connecting to device
2024-01-16 18:13:39.490 WARNING (MainThread) [custom_components.dreame_vacuum] Integration start failed: Traceback (most recent call last):
File "/home/homeassistant/.homeassistant/custom_components/dreame_vacuum/coordinator.py", line 491, in _async_update_data
await self.hass.async_add_executor_job(self._device.update)
File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/homeassistant/.homeassistant/custom_components/dreame_vacuum/dreame/device.py", line 2382, in update
self.connect_device()
File "/home/homeassistant/.homeassistant/custom_components/dreame_vacuum/dreame/device.py", line 1746, in connect_device
info = self._protocol.connect(self._message_callback, self._connected_callback)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/homeassistant/.homeassistant/custom_components/dreame_vacuum/dreame/protocol.py", line 1239, in connect
info = self.cloud.connect(message_callback, connected_callback)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/homeassistant/.homeassistant/custom_components/dreame_vacuum/dreame/protocol.py", line 232, in connect
info = self.get_device_info()
^^^^^^^^^^^^^^^^^^^^^^
File "/home/homeassistant/.homeassistant/custom_components/dreame_vacuum/dreame/protocol.py", line 349, in get_device_info
**response["data"][self._strings[31]][self._strings[32]],
~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'otcInfo'
2024-01-16 18:13:39.491 INFO (MainThread) [custom_components.dreame_vacuum.dreame.device] Disconnect
2024-01-16 18:13:39.493 DEBUG (MainThread) [custom_components.dreame_vacuum] Finished fetching dreame_vacuum data in 0.212 seconds (success: False)
```

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Additional Information (please complete the following information)**
 - Model Name [e.g. dreame.vacuum.p2028]: 
 - Firmware Version [e.g. 1156]: 4.3.9_3104
 - Home Assistant Version: 2024.1.0
 - Configuration Type [With or without map support]: with / Dreamehome account
 - Errors or warnings shown in the HA logs (if applicable):

**Comment by jtwhitlow** [comment]
Is the Dreame Account Setup working yet?  I keep getting asked to put in my Xioami account?  Is there something I am missing?

**Comment by Vaskivskyi** [comment]
Hey, @Tasshack, Thanks for your fast reply!

After several hours my device got connected. Maybe the cloud needs some time to process new device info (even though, it already shows that it exists and is connected to the account, so integration can set it up)

I tried adding the robot to the integration just ~2 hours after I got it (and set it up fully in the mobile app, of course). Apparently, this is the only reason for the issue. And maybe that's why you cannot reproduce it on a device which is already set up for some time.

In any case, thanks for your integration!

**Comment by jtwhitlow** [comment]
I understand it was only for beta. I had downloaded the beta. I had seen
that potentially it was a todo. Not sure that the response was necessary.
Good luck with your endeavors.

**Comment by jtwhitlow** [comment]
I apologize for bothering you.  I did fix the issue I had. Appreciate your
work.
