### ISSUE TITLE
Failed to call service select/select_option. Non-thread-safe operation invoked on an event loop other than the current one

### ISSUE THREAD

**Issue by Ar2rZ** [Tasshack/dreame-vacuum#384]
Can not control Dreame L20 from HA using this integration.
Currently i can see Map , Entities are visible, but can't control, it throwing error 
"Failed to call service select/select_option. Non-thread-safe operation invoked on an event loop other than the current one"

![image](https://github.com/Tasshack/dreame-vacuum/assets/14283948/0600652c-12ad-4869-9524-8aa813fcaf69)

if is needed more info, just let me know, i can assist..

**Comment by Ar2rZ** [comment]
Ok, as this is a bug, i noticed another thing - if vacuum cleaner is on, my HA instance start to hang.. and some times HA restarting also, i tough this is while L20 is not supported yet..  but looks like it some bug.. can you point me out direction where i can look at?  my HA instance is located via VMWare on mini pc. i downloaded snapshot of HAOS vm snapshot from official HA website. 
thanks in advance.
![image](https://github.com/Tasshack/dreame-vacuum/assets/14283948/6e37a00b-37ec-44b9-aec6-fe1f1f3ebde7)

**Comment by Ar2rZ** [comment]
in debug log, i have lot off these events related to dreame: 
`2024-02-01 09:52:55.066 INFO (Thread-1329 (_thread_main)) [custom_components.dreame_vacuum.dreame.map] Decode P map 1 1415
2024-02-01 09:52:55.147 ERROR (Thread-1329 (_thread_main)) [homeassistant] Error doing job: Task was destroyed but it is pending!:   File "/usr/local/lib/python3.11/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/pydev_monkey.py", line 1118, in __call__
    ret = self.original_func(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 215, in _on_client_message
    self._message_callback(response["data"])
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 412, in _message_callback
    self._map_manager.handle_properties(map_params)
  File "/config/custom_components/dreame_vacuum/dreame/map.py", line 1146, in handle_properties
    self._add_cloud_map_data(partial_map_data, object_name, timestamp)
  File "/config/custom_components/dreame_vacuum/dreame/map.py", line 669, in _add_cloud_map_data
    not self._add_map_data(
  File "/config/custom_components/dreame_vacuum/dreame/map.py", line 864, in _add_map_data
    self._map_data_changed()
  File "/config/custom_components/dreame_vacuum/dreame/map.py", line 467, in _map_data_changed
    self._update_callback()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1478, in _map_changed
    self._property_changed()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1409, in _property_changed
    self._update_callback()
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 538, in async_set_updated_data
    super().async_set_updated_data(self._device)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 426, in async_set_updated_data
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_update_listeners
    update_callback()
  File "/config/custom_components/dreame_vacuum/camera.py", line 566, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1129, in _async_write_ha_state
    hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1820, in async_set
    self._bus.async_fire(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1188, in async_fire
    self._hass.async_add_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 588, in async_add_hass_job
    task = self.loop.create_task(hassjob.target(*args), name=hassjob.name)
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 436, in create_task
    task = tasks.Task(coro, loop=self, name=name, context=context)`

**Comment by Ar2rZ** [comment]
@Tasshack how much memory you expect to HA WS should have to run your integration? even if there is issue with the memory(this can explain hanging while vacuum cleaner is cleaning) it does not explains why none of the functions in integration works, although these functions are available..

**Comment by Ar2rZ** [comment]
there is memory and processor % while vacuum cleaner is in progress to clean, do not see any issue described: 
![image](https://github.com/Tasshack/dreame-vacuum/assets/14283948/03216e12-5459-4ec7-9db7-29e5c6392139)

**Comment by Ar2rZ** [comment]
these are two errors recoded when i click on Auto drying slider:
`2024-02-02 08:17:58.358 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139859858698816] Non-thread-safe operation invoked on an event loop other than the current one
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2149, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2186, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 882, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 952, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/switch.py", line 514, in async_turn_on
    await self.async_set_state(1)
  File "/config/custom_components/dreame_vacuum/switch.py", line 530, in async_set_state
    await self._try_command(
  File "/config/custom_components/dreame_vacuum/entity.py", line 175, in _try_command
    await self.hass.async_add_executor_job(partial(func, *args, **kwargs))
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1949, in set_property
    return self.set_auto_switch_property(prop, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 4185, in set_auto_switch_property
    result = self.set_auto_switch_settings(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 4154, in set_auto_switch_settings
    self._property_changed()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1409, in _property_changed
    self._update_callback()
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 538, in async_set_updated_data
    super().async_set_updated_data(self._device)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 426, in async_set_updated_data
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_update_listeners
    update_callback()
  File "/config/custom_components/dreame_vacuum/entity.py", line 167, in _handle_coordinator_update
    super()._handle_coordinator_update()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 479, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1129, in _async_write_ha_state
    hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1820, in async_set
    self._bus.async_fire(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1188, in async_fire
    self._hass.async_add_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 588, in async_add_hass_job
    task = self.loop.create_task(hassjob.target(*args), name=hassjob.name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 436, in create_task
    task = tasks.Task(coro, loop=self, name=name, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 763, in call_soon
    self._check_thread()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 800, in _check_thread
    raise RuntimeError(
RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one`

`2024-02-02 08:17:55.263 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139859858698816] Non-thread-safe operation invoked on an event loop other than the current one
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2149, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2186, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 882, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 952, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/switch.py", line 510, in async_turn_off
    await self.async_set_state(0)
  File "/config/custom_components/dreame_vacuum/switch.py", line 530, in async_set_state
    await self._try_command(
  File "/config/custom_components/dreame_vacuum/entity.py", line 175, in _try_command
    await self.hass.async_add_executor_job(partial(func, *args, **kwargs))
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1949, in set_property
    return self.set_auto_switch_property(prop, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 4185, in set_auto_switch_property
    result = self.set_auto_switch_settings(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 4154, in set_auto_switch_settings
    self._property_changed()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1409, in _property_changed
    self._update_callback()
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 538, in async_set_updated_data
    super().async_set_updated_data(self._device)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 426, in async_set_updated_data
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_update_listeners
    update_callback()
  File "/config/custom_components/dreame_vacuum/entity.py", line 167, in _handle_coordinator_update
    super()._handle_coordinator_update()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 479, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1129, in _async_write_ha_state
    hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1820, in async_set
    self._bus.async_fire(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1188, in async_fire
    self._hass.async_add_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 592, in async_add_hass_job
    self.loop.call_soon(hassjob.target, *args)
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 763, in call_soon
    self._check_thread()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 800, in _check_thread
    raise RuntimeError(
RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one`

**Comment by Ar2rZ** [comment]
@Tasshack so, there for no solution or no direction what or how can find what is wrong?

**Comment by Ar2rZ** [comment]
@Tasshack   Auto drying it is switch type. i will add button type also.
`2024-02-04 10:16:20.359 DEBUG (SyncWorker_17) [custom_components.dreame_vacuum.dreame.device] Update Callback
2024-02-04 10:16:20.359 DEBUG (SyncWorker_17) [custom_components.dreame_vacuum] Manually updated dreame_vacuum data
2024-02-04 10:16:20.384 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140166384351936] Non-thread-safe operation invoked on an event loop other than the current one
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2149, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2186, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 882, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 952, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 132, in _async_press_action
    await self.async_press()
  File "/config/custom_components/dreame_vacuum/button.py", line 337, in async_press
    await self._try_command(
  File "/config/custom_components/dreame_vacuum/entity.py", line 175, in _try_command
    await self.hass.async_add_executor_job(partial(func, *args, **kwargs))
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/button.py", line 179, in <lambda>
    action_fn=lambda device: device.toggle_drying(),
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 3830, in toggle_drying
    return self.start_drying()
           ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 3835, in start_drying
    self._update_property(
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 613, in _update_property
    self._property_changed()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1409, in _property_changed
    self._update_callback()
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 538, in async_set_updated_data
    super().async_set_updated_data(self._device)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 426, in async_set_updated_data
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_update_listeners
    update_callback()
  File "/config/custom_components/dreame_vacuum/vacuum.py", line 648, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1129, in _async_write_ha_state
    hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1820, in async_set
    self._bus.async_fire(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1188, in async_fire
    self._hass.async_add_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 592, in async_add_hass_job
    self.loop.call_soon(hassjob.target, *args)
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 763, in call_soon
    self._check_thread()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 800, in _check_thread
    raise RuntimeError(
RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one
2024-02-04 10:16:25.397 DEBUG (Thread-5245) [custom_components.dreame_vacuum.dreame.device] Device update: 30`

**Comment by Ar2rZ** [comment]
this is elect event: 
`2024-02-04 10:18:49.507 DEBUG (SyncWorker_11) [custom_components.dreame_vacuum.dreame.device] Update Callback
2024-02-04 10:18:49.507 DEBUG (SyncWorker_11) [custom_components.dreame_vacuum] Manually updated dreame_vacuum data
2024-02-04 10:18:49.556 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140166384351936] Non-thread-safe operation invoked on an event loop other than the current one
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2149, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2186, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 882, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 952, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 195, in async_handle_select_option
    await self.async_select_option(option)
  File "/config/custom_components/dreame_vacuum/select.py", line 985, in async_select_option
    await self._try_command(
  File "/config/custom_components/dreame_vacuum/entity.py", line 175, in _try_command
    await self.hass.async_add_executor_job(partial(func, *args, **kwargs))
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1949, in set_property
    return self.set_auto_switch_property(prop, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 4185, in set_auto_switch_property
    result = self.set_auto_switch_settings(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 4154, in set_auto_switch_settings
    self._property_changed()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1409, in _property_changed
    self._update_callback()
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 538, in async_set_updated_data
    super().async_set_updated_data(self._device)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 426, in async_set_updated_data
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_update_listeners
    update_callback()
  File "/config/custom_components/dreame_vacuum/vacuum.py", line 648, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1129, in _async_write_ha_state
    hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1820, in async_set
    self._bus.async_fire(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1188, in async_fire
    self._hass.async_add_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 592, in async_add_hass_job
    self.loop.call_soon(hassjob.target, *args)
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 763, in call_soon
    self._check_thread()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 800, in _check_thread
    raise RuntimeError(
RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one`

**Comment by Ar2rZ** [comment]
@Tasshack any updates here? if you help me with dev environment i can try to debug...

**Comment by Ar2rZ** [comment]
@Tasshack just installed HAOS on physical WS and have same issue.

**Comment by Ar2rZ** [comment]
Thanks, really appreciated..

**Comment by Ar2rZ** [comment]
@Tasshack Thanks for FIX!! is working now as expected. and i can finally control on my vacuum cleaner via HA. thanks again for very good integration and support!!!!
