### ISSUE TITLE
Cannot set cleaning mode while vacuum is running on L10 Pro

### ISSUE THREAD

**Issue by llucax** [Tasshack/dreame-vacuum#390]
Sorry for the spam, but I have to say it, awesome integration! Thanks a lot!

**Describe the bug**
I cannot change the cleaning mode (sweeping + mopping / mopping only) while the vacuum is running. I get this error message:

> Failed to call service select/select_option. Cannot set cleaning mode while vacuum is running

**To Reproduce**
1. Install the mopping pad/container
2. Start a cleaning with one mode (let's say sweeping + mopping for this example but it could be the other way around)
3. Try to change the cleaning mode (to mopping only) while the robot is still running

**Expected behavior**
The cleaning mode is changed while the vacuum is running, as I can do that without any issues in the official Xiaomi Home app.

**Screenshots**
![image](https://github.com/Tasshack/dreame-vacuum/assets/1031485/b9a59899-316f-4abd-a6d4-c34fad5a66c3)

**Additional Information (please complete the following information)**
 - Model Name: dreame.vacuum.p2029
 - Firmware Version: 1138 (side note, I don't get any more updates, I've read that many people with this model have a firmware 1158)
 - Home Assistant Version: 2024.1.6
 - Configuration Type: with map support
 - Errors or warnings shown in the HA logs

With INFO level, at around the time I attempt to change the cleaning mode:
```
Feb 04 23:25:35 rock64 sh[515687]: 2024-02-04 23:25:35.145 INFO (Thread-1082) [custom_components.dreame_vacuum.dreame.map] New object name received: 6454357488/391946859/1
Feb 04 23:25:35 rock64 sh[515687]: 2024-02-04 23:25:35.193 INFO (Thread-1082) [custom_components.dreame_vacuum.dreame.map] Map ID Changed: 7 -> 8
Feb 04 23:25:35 rock64 sh[515687]: 2024-02-04 23:25:35.796 INFO (Thread-1084) [paramiko.transport] Connected (version 2.0, client dropbear_2020.81)
Feb 04 23:25:35 rock64 sh[515687]: 2024-02-04 23:25:35.802 INFO (Thread-1082) [custom_components.dreame_vacuum.dreame.map] Decode I map 8 0
Feb 04 23:25:35 rock64 sh[515687]: 2024-02-04 23:25:35.974 INFO (Thread-1082) [custom_components.dreame_vacuum.dreame.map] No new map data received, retrying
Feb 04 23:25:36 rock64 sh[515687]: 2024-02-04 23:25:36.101 INFO (Thread-1084) [paramiko.transport] Authentication (password) successful!
Feb 04 23:25:36 rock64 sh[515687]: 2024-02-04 23:25:36.919 INFO (Thread-1082) [custom_components.dreame_vacuum.dreame.map] Decode P map 8 1
Feb 04 23:25:38 rock64 sh[515687]: 2024-02-04 23:25:38.114 INFO (Thread-1086) [custom_components.dreame_vacuum.dreame.map] No new map data received, retrying
Feb 04 23:25:38 rock64 sh[515687]: 2024-02-04 23:25:38.887 INFO (Thread-1086) [custom_components.dreame_vacuum.dreame.map] No new map data received on second try
Feb 04 23:25:40 rock64 sh[515687]: 2024-02-04 23:25:40.144 INFO (MainThread) [custom_components.dreame_vacuum.dreame.map] Render frame: 8:1 took: 3.43
Feb 04 23:25:40 rock64 sh[515687]: 2024-02-04 23:25:40.519 INFO (MainThread) [custom_components.dreame_vacuum.dreame.map] Skip render frame, map data not changed
Feb 04 23:25:40 rock64 sh[515687]: 2024-02-04 23:25:40.948 INFO (Thread-1088) [custom_components.dreame_vacuum.dreame.map] Decode P map 8 2
Feb 04 23:25:44 rock64 sh[515687]: 2024-02-04 23:25:44.329 INFO (Thread-1090) [custom_components.dreame_vacuum.dreame.map] Decode P map 8 3
Feb 04 23:25:44 rock64 sh[515687]: 2024-02-04 23:25:44.424 INFO (MainThread) [custom_components.dreame_vacuum.dreame.map] Render frame: 8:2 took: 2.21
Feb 04 23:25:44 rock64 sh[515687]: 2024-02-04 23:25:44.820 ERROR (MainThread) [custom_components.dreame_vacuum] Unable to call Cannot set cleaning mode while vacuum is running
Feb 04 23:25:44 rock64 sh[515687]: 2024-02-04 23:25:44.875 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281472068049856] Cannot set cleaning mode while vacuum is running
Feb 04 23:25:44 rock64 sh[515687]: Traceback (most recent call last):
Feb 04 23:25:44 rock64 sh[515687]:   File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
Feb 04 23:25:44 rock64 sh[515687]:     response = await hass.services.async_call(
Feb 04 23:25:44 rock64 sh[515687]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 04 23:25:44 rock64 sh[515687]:   File "/usr/src/homeassistant/homeassistant/core.py", line 2149, in async_call
Feb 04 23:25:44 rock64 sh[515687]:     response_data = await coro
Feb 04 23:25:44 rock64 sh[515687]:                     ^^^^^^^^^^
Feb 04 23:25:44 rock64 sh[515687]:   File "/usr/src/homeassistant/homeassistant/core.py", line 2186, in _execute_service
Feb 04 23:25:44 rock64 sh[515687]:     return await target(service_call)
Feb 04 23:25:44 rock64 sh[515687]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 04 23:25:44 rock64 sh[515687]:   File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
Feb 04 23:25:44 rock64 sh[515687]:     return await service.entity_service_call(
Feb 04 23:25:44 rock64 sh[515687]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 04 23:25:44 rock64 sh[515687]:   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 882, in entity_service_call
Feb 04 23:25:44 rock64 sh[515687]:     single_response = await _handle_entity_call(
Feb 04 23:25:44 rock64 sh[515687]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 04 23:25:44 rock64 sh[515687]:   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 952, in _handle_entity_call
Feb 04 23:25:44 rock64 sh[515687]:     result = await task
Feb 04 23:25:44 rock64 sh[515687]:              ^^^^^^^^^^
Feb 04 23:25:44 rock64 sh[515687]:   File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 195, in async_handle_select_option
Feb 04 23:25:44 rock64 sh[515687]:     await self.async_select_option(option)
Feb 04 23:25:44 rock64 sh[515687]:   File "/config/custom_components/dreame_vacuum/select.py", line 571, in async_select_option
Feb 04 23:25:44 rock64 sh[515687]:     await self._try_command(
Feb 04 23:25:44 rock64 sh[515687]:   File "/config/custom_components/dreame_vacuum/entity.py", line 123, in _try_command
Feb 04 23:25:44 rock64 sh[515687]:     raise ValueError(str(exc)) from None
Feb 04 23:25:44 rock64 sh[515687]: ValueError: Cannot set cleaning mode while vacuum is running
```

**Comment by llucax** [comment]
Awesome, thanks for the quick fix! I'm pretty new to HA, HACS and this integration, so I'm not sure how the release process work. Will you do a final release eventually (how long does it usually takes?) and I will be able to upgrade via HACS if I installed the integration via HACS?

Thanks again, it's awesome to see how well integrated the vacuum cleaner is into HA!
