### ISSUE TITLE
Error when upgrading Dreame integration

### ISSUE THREAD

**Issue by RobertWojtowicz** [Tasshack/dreame-vacuum#417]
Hi,

Dreame Vacuum upgrade from v2.0.0b11 to v2.0.0b12 receive the following error:
```
ERROR (MainThread) [custom_components.hacs] <Integration Tasshack/dreame-vacuum> 'utf-8' codec can't decode byte 0xb2 in position 7167: invalid start byte
```

https://github.com/hacs/integration/issues/3484#issuecomment-1913709198

BR,
Robert

**Comment by b0arkz** [comment]
Hi,
Same Here !

```
Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 232, in hacs_repository_download
    await repository.update_repository(force=True)
  File "/config/custom_components/hacs/utils/decorator.py", line 28, in wrapper
    result = await function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/repositories/integration.py", line 115, in update_repository
    if not await self.common_update(ignore_issues, force) and not force:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/utils/decorator.py", line 28, in wrapper
    result = await function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/repositories/base.py", line 555, in common_update
    self.additional_info = await self.async_get_info_file_contents()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/repositories/base.py", line 747, in async_get_info_file_contents
    return await self.get_documentation(filename=info_files[0]) or ""
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/repositories/base.py", line 1353, in get_documentation
    result.decode(encoding="utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 7167: invalid start byte
```

**Comment by endyb66** [comment]
Same problem here.

**Comment by TrilIiard** [comment]
For me Hacs is not even able to read the available Versions of this Integration. Updating of a different Hacs Integration worked fine this morning.
