### ISSUE TITLE
update not possible (b11 to b12)

### ISSUE THREAD

**Issue by vulbas** [Tasshack/dreame-vacuum#429]
hello
the update to v2.0.0b12 does not want to be done.
Core
2024.2.2
Supervisor
2024.02.0
Operating System
11.5
I tried everything but it doesn't work I'm still in v2.0.0b11
the circle rotates constantly. 
![Capture d'écran 2024-02-22 143240](https://github.com/Tasshack/dreame-vacuum/assets/39675749/c3846895-5c55-4fca-bc06-b71b3cc01b6e)

**Comment by gabriele-latino** [comment]
same issue here 

```
[140523839011136] Error handling message: Unknown error (unknown_error) Gabriele from 91.223.179.253 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36)
Traceback (most recent call last):
  
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  
File "/config/custom_components/hacs/websocket/repository.py", line 232, in hacs_repository_download
    await repository.update_repository(force=True)
  
File "/config/custom_components/hacs/utils/decorator.py", line 28, in wrapper
    result = await function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
File "/config/custom_components/hacs/repositories/integration.py", line 115, in update_repository
    if not await self.common_update(ignore_issues, force) and not force:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
File "/config/custom_components/hacs/utils/decorator.py", line 28, in wrapper
    result = await function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
File "/config/custom_components/hacs/repositories/base.py", line 555, in common_update
    self.additional_info = await self.async_get_info_file_contents()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/config/custom_components/hacs/repositories/base.py", line 747, in async_get_info_file_contents
    return await self.get_documentation(filename=info_files[0]) or ""
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
File "/config/custom_components/hacs/repositories/base.py", line 1353, in get_documentation
    result.decode(encoding="utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 7167: invalid start byte
```

**Comment by greendog99** [comment]
Same for me. Can't update. Might try removing and re-adding the Integration...

**Comment by DEzaDez** [comment]
Same for me. Can't update. the circle rotates constantly.

**Comment by greendog99** [comment]
I removed the Dreame integration via HACS, then added it again via HACS (latest version), then restarted Home Assistant. It's working correctly, and my vacuum's cards and entities all still work. Probably easier to just do this re-install while the Integration is still in Beta.

**Comment by vulbas** [comment]
how do I know which version is installed?

**Comment by vulbas** [comment]
I completely uninstalled dreame vaccum. but it still offers me to update.
I cleared the cache, restarted HA
I even deleted the folder in custom_components, I don't know what to do anymore.
![Capture d'écran 2024-02-25 101032](https://github.com/Tasshack/dreame-vacuum/assets/39675749/5a1faf71-7013-4a11-9b3b-a1544fa832d8)

**Comment by feerlessleadr** [comment]
> mb [#226 (comment)](https://github.com/Tasshack/dreame-vacuum/issues/226#issuecomment-1734854503) can help you

Sorry for the stupid question, on HAOS, where would I execute these scripts? Just from the terminal? or from somewhere else?

**Comment by jove01** [comment]
also to .b013 is not possible
