### ISSUE TITLE
Integration does not work after inital successful configuration

### ISSUE THREAD

**Issue by Willow-Systems** [Tasshack/dreame-vacuum#43]
**Describe the bug**
I configured a new Dreame L10 pro with the xiaomi home app, then used the Xiaomi Cloud Tokens Extractor to retrieve my token. Then I added the robot to the dreame integration using the local (no maps) option via IP + Token. This worked, and created a new entity etc.

Now when I try to have HA do anything with the vacuum, I get logs similar to the following:

```
Traceback (most recent call last):
File "/config/custom_components/dreame_vacuum/dreame/device.py", line 610, in _update_task
self.update()
File "/config/custom_components/dreame_vacuum/dreame/device.py", line 973, in update
self.connect_device()
File "/config/custom_components/dreame_vacuum/dreame/device.py", line 648, in connect_device
self.info = DreameVacuumDeviceInfo(self._protocol.connect())
File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 482, in connect
response = self.send("miIO.info", retry_count=retry_count)
File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 514, in send
return self.device.send(method, parameters=parameters, retry_count=retry_count)
File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 161, in send
self.send_handshake()
File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 74, in send_handshake
raise DeviceException("Unable to discover the device %s" % self.ip)
miio.exceptions.DeviceException: Unable to discover the device 192.168.2.125
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.9/threading.py", line 1299, in run
self.function(*self.args, **self.kwargs)
File "/config/custom_components/dreame_vacuum/dreame/device.py", line 621, in _update_task
self._update_failed(ex)
File "/config/custom_components/dreame_vacuum/dreame/device.py", line 603, in _update_failed
self._error_callback(ex)
File "/config/custom_components/dreame_vacuum/coordinator.py", line 355, in async_set_update_error
super().async_set_update_error(ex)
AttributeError: 'super' object has no attribute 'async_set_update_error'
```

**Comment by Willow-Systems** [comment]
Both the robot and the home assistant server are on 192.168.2.X subnet, and I can ping the robot from the HA server.
