### ISSUE TITLE
Integration not loading after HA update (Unexpected exception importing platform custom_components.dreame_vacuum.config_flow)

### ISSUE THREAD

**Issue by xanox1** [Tasshack/dreame-vacuum#448]
Since i updated my home assistant instance, i get the following error:

```
Logger: homeassistant.config_entries
Source: config_entries.py:2444
First occurred: March 8, 2024 at 10:47:22 AM (1 occurrences)
Last logged: March 8, 2024 at 10:47:22 AM
Error occurred loading flow for integration dreame_vacuum: Exception importing custom_components.dreame_vacuum.config_flow
```

```
Logger: homeassistant.loader
Source: loader.py:1025
First occurred: March 8, 2024 at 10:47:22 AM (1 occurrences)
Last logged: March 8, 2024 at 10:47:22 AM

Unexpected exception importing platform custom_components.dreame_vacuum.config_flow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1025, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1058, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/dreame_vacuum/__init__.py", line 7, in <module>
    from .coordinator import DreameVacuumDataUpdateCoordinator
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 20, in <module>
    from .dreame import DreameVacuumDevice, DreameVacuumProperty
  File "/config/custom_components/dreame_vacuum/dreame/__init__.py", line 29, in <module>
    from .device import DreameVacuumDevice
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 101, in <module>
    from .resources import ERROR_IMAGE
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1124, in get_code
  File "<frozen importlib._bootstrap_external>", line 753, in _compile_bytecode
EOFError: marshal data too short
```

Can you help me find a resolution?
If you need any additional information, i would be happy to provide. 

Thank you in advance.

**Comment by xanox1** [comment]
Thank you! That was an easy fix.  
Great support 👍 ❤️
