### ISSUE TITLE
Map data decryption failed - Dreame L10s Pro

### ISSUE THREAD

**Issue by fpfuetsch** [Tasshack/dreame-vacuum#45]
**Describe the bug**
Map is not available

**Additional Information (please complete the following information)**
 - Model Name [e.g. dreame.vacuum.p2028]: dreame.vacuum.r2216o
 - Firmware Version: 4.3.3_1045
 - Home Assistant Version: 2022.11.4
 - Configuration Type [With or without map support]: with map
 - Errors or warnings shown in the HA logs (if applicable):
 
```
home-assistant  | --- Logging error ---
home-assistant  | Traceback (most recent call last):
home-assistant  |   File "/config/custom_components/dreame_vacuum/dreame/map.py", line 1980, in decode_map_partial
home-assistant  |     cipher = Cipher(algorithms.AES(key), modes.CBC(
home-assistant  |   File "/usr/local/lib/python3.10/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 92, in __init__
home-assistant  |     mode.validate_for_algorithm(algorithm)
home-assistant  |   File "/usr/local/lib/python3.10/site-packages/cryptography/hazmat/primitives/ciphers/modes.py", line 106, in _check_iv_and_key_length
home-assistant  |     _check_iv_length(self, algorithm)
home-assistant  |   File "/usr/local/lib/python3.10/site-packages/cryptography/hazmat/primitives/ciphers/modes.py", line 76, in _check_iv_length
home-assistant  |     raise ValueError(
home-assistant  | ValueError: Invalid IV size (0) for CBC.
home-assistant  |
home-assistant  | During handling of the above exception, another exception occurred:
home-assistant  |
home-assistant  | Traceback (most recent call last):
home-assistant  |   File "/usr/local/lib/python3.10/logging/handlers.py", line 1475, in emit
home-assistant  |     self.enqueue(self.prepare(record))
home-assistant  |   File "/usr/src/homeassistant/homeassistant/util/logging.py", line 43, in prepare
home-assistant  |     record = super().prepare(record)
home-assistant  |   File "/usr/local/lib/python3.10/logging/handlers.py", line 1457, in prepare
home-assistant  |     msg = self.format(record)
home-assistant  |   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
home-assistant  |     return fmt.format(record)
home-assistant  |   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
home-assistant  |     record.message = record.getMessage()
home-assistant  |   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
home-assistant  |     msg = msg % self.args
home-assistant  | TypeError: not enough arguments for format string
home-assistant  | Call stack:
home-assistant  |   File "/usr/local/lib/python3.10/threading.py", line 973, in _bootstrap
home-assistant  |     self._bootstrap_inner()
home-assistant  |   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
home-assistant  |     self.run()
home-assistant  |   File "/usr/local/lib/python3.10/threading.py", line 1378, in run
home-assistant  |     self.function(*self.args, **self.kwargs)
home-assistant  |   File "/config/custom_components/dreame_vacuum/dreame/map.py", line 464, in _update_task
home-assistant  |     self.update()
home-assistant  |   File "/config/custom_components/dreame_vacuum/dreame/map.py", line 986, in update
home-assistant  |     self._request_current_map()
home-assistant  |   File "/config/custom_components/dreame_vacuum/dreame/map.py", line 449, in _request_current_map
home-assistant  |     return self._request_i_map(map_request_time)
home-assistant  |   File "/config/custom_components/dreame_vacuum/dreame/map.py", line 362, in _request_i_map
home-assistant  |     self._add_map_data_file(object_name, self._last_robot_time)
home-assistant  |   File "/config/custom_components/dreame_vacuum/dreame/map.py", line 624, in _add_map_data_file
home-assistant  |     self._add_raw_map_data(response.decode(), timestamp, key)
home-assistant  |   File "/config/custom_components/dreame_vacuum/dreame/map.py", line 627, in _add_raw_map_data
home-assistant  |     return self._add_map_data(self._decode_map_partial(raw_map, timestamp, key))
home-assistant  |   File "/config/custom_components/dreame_vacuum/dreame/map.py", line 601, in _decode_map_partial
home-assistant  |     partial_map = DreameVacuumMapDecoder.decode_map_partial(raw_map, key)
home-assistant  |   File "/config/custom_components/dreame_vacuum/dreame/map.py", line 1985, in decode_map_partial
home-assistant  |     _LOGGER.error("Map data decryption failed: %s. Private key might be missing, please report this issue with your device model https://github.com/Tasshack/dreame-vacuum/issues/new?assignees=Tasshack&labels=bug&template=bug_report.md&title=Map%20data%20decryption%20failed", ex)
home-assistant  |   File "/usr/local/lib/python3.10/logging/__init__.py", line 1506, in error
home-assistant  |     self._log(ERROR, msg, args, **kwargs)
home-assistant  |   File "/usr/local/lib/python3.10/logging/__init__.py", line 1624, in _log
home-assistant  |     self.handle(record)
home-assistant  |   File "/usr/local/lib/python3.10/logging/__init__.py", line 1634, in handle
home-assistant  |     self.callHandlers(record)
home-assistant  |   File "/usr/local/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
home-assistant  |     hdlr.handle(record)
home-assistant  |   File "/usr/src/homeassistant/homeassistant/util/logging.py", line 62, in handle
home-assistant  |     self.emit(record)
home-assistant  | Message: 'Map data decryption failed: %s. Private key might be missing, please report this issue with your device model https://github.com/Tasshack/dreame-vacuum/issues/new?assignees=Tasshack&labels=bug&template=bug_report.md&title=Map%20data%20decryption%20failed'
home-assistant  | Arguments: (ValueError('Invalid IV size (0) for CBC.'),)
```

**Comment by fpfuetsch** [comment]
@Tasshack no, the vacuum is the only device I use, I just migrated it from the DreameHome App to the Xioami Home app to be able to use the integration.

What do you mean with 'give access to my Mi Home account'? I think i would prefer the logs option if you could provide instructions how to get them.

**Comment by fpfuetsch** [comment]
will do 👍

**Comment by fpfuetsch** [comment]
Sent

**Comment by fpfuetsch** [comment]
It works 💯 . Thank you so much for your great work again and for fixing this incredibly fast 🥇
