### ISSUE TITLE
Dreame Vacuum integration crash the home assistant core 2024.04

### ISSUE THREAD

**Issue by DIMMonchik** [Tasshack/dreame-vacuum#479]
Core 2024.4.1
Supervisor 2024.03.1
Operating System 12.1

Dreame Vacuum v2.0.0b13

After the update, the HA integration crashed at the start of the cleaning process. I tried removing and adding the integration again, but the device still didn't work. I disabled all relevant automations and templates, but that didn't solve the problem either.

`2024-04-08 11:29:10.613 WARNING (SyncWorker_15) [custom_components.dreame_vacuum] Waiting render complete
2024-04-08 11:29:10.619 WARNING (SyncWorker_49) [custom_components.dreame_vacuum] Waiting render complete
2024-04-08 11:29:10.624 WARNING (SyncWorker_15) [custom_components.dreame_vacuum] Waiting render complete
2024-04-08 11:29:24.677 WARNING (Thread-1694) [custom_components.dreame_vacuum.dreame.map] Map update Failed: Traceback (most recent call last):
  File "/config/custom_components/dreame_vacuum/dreame/map.py", line 1236, in update
    if not self._request_map_from_cloud():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/map.py", line 272, in _request_map_from_cloud
    self._add_cloud_map_data(partial_map_data, object_name, object_name_timestamp)
  File "/config/custom_components/dreame_vacuum/dreame/map.py", line 655, in _add_cloud_map_data
    return self._add_map_data(partial_map)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/map.py", line 965, in _add_map_data
    self._add_next_map_data()
  File "/config/custom_components/dreame_vacuum/dreame/map.py", line 972, in _add_next_map_data
    self._add_map_data(next_partial_map)
  File "/config/custom_components/dreame_vacuum/dreame/map.py", line 781, in _add_map_data
    map_data = DreameVacuumMapDecoder.decode_p_map_data_from_partial(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/map.py", line 3660, in decode_p_map_data_from_partial
    data[(combined_dimensions.width * (top_offset + y)) + left_offset + x] = current_map_data.data[
                                                                             ^^^^^^^^^^^^^^^^^^^^^^
IndexError: index out of range

2024-04-08 11:29:24.677 ERROR (Thread-1694) [custom_components.dreame_vacuum] Error requesting dreame_vacuum data: index out of range`

**Comment by DIMMonchik** [comment]
![image](https://github.com/Tasshack/dreame-vacuum/assets/38500475/7317543b-a73e-4e43-8bab-68781ab853fc)
I think that's enough

**Comment by g470258** [comment]
> @g470258 can you disable all notifications from the integration configuration to make sure this is related to that.

I can. And what will it do? Without them, there will be no trigger. Disabling automation. Notifications appear. The ha core works well.

**Comment by DdenBraver** [comment]
I just had exactly the same.
I installed the latest beta version, added my Dreame and 2minutes later HA crashed. Unable to get it working again - instant crashes after reboot. I had to delete the Dreame-vacuum folder to restore HA.

**Comment by msaphoto06** [comment]
Same problem with HA 2024.4.2

**Comment by Jack77777777** [comment]
My HA crashes as well when i switch the floors. Sometimes at the first change. At the least at the second. It is reproduceable.I have a Dreame L20. Hopefully the next release will come soon. 

Thanks to @Tasshack for this excellent integration.

**Comment by phil9309** [comment]
I have the same problem, I was just working on my Home Assistant when it crashed the second i started my L20. It's reproduceable on my end here too.

**Comment by formatBCE** [comment]
I'm on 1.0.3. Crashing.

**Comment by KSchmeeds** [comment]
I ended up needing to disable the integration completely in order to update to 2024.5.0.  If I try to enable it on 2024.5.0, Home Assistant Core crashes.

**Comment by KSchmeeds** [comment]
I'm trying to pull logs, but attached is what I see in the console when it crashes.

![image](https://github.com/Tasshack/dreame-vacuum/assets/3228499/797a4324-61db-4db0-8b24-ea65b3c55f3a)

**Comment by formatBCE** [comment]
> I ended up needing to disable the integration completely in order to update to 2024.5.0.  If I try to enable it on 2024.5.0, Home Assistant Core crashes.

Same here, I posted issue, but it was closed as there's not enough information about bug...

**Comment by KSchmeeds** [comment]
I'm running Home Assistant OS with 8GB of RAM on x86.  Integration works fine on 2024.4.4

**Comment by g470258** [comment]
> Proving or telling that your HA is not working with the integration is not enough for me understanding and fixing the underlying issue because I cannot reproduce it on my setup.

On the forums they write that the kernel is not being updated to 2024.5.0 when using integration 1.0.3.  When using the beta version this problem does not exist.
