### ISSUE TITLE
L10s Ultra Firmware 4.3.9_3204 Cause Integration to Fail to Start

### ISSUE THREAD

**Issue by KSchmeeds** [Tasshack/dreame-vacuum#482]
**Describe the bug**
Integration does not load on Dreame L10s Ultra Vacuum firmware 4.3.9_3204

**To Reproduce**
Update the L10s Ultra to firmware 4.3.9_3204 from the MiHome App

**Additional Information (please complete the following information)**
 - Model Name [e.g. dreame.vacuum.p2028]:  dreame.vacuum.r2228o
 - Firmware Version [e.g. 1156]: 4.3.9_3204
 - Home Assistant Version: 2024.4.2
 - Configuration Type [With or without map support]: With Map Support
 - Errors or warnings shown in the HA logs (if applicable):
 
 Debug log

`2024-04-08 22:57:51.746 WARNING (MainThread) [custom_components.dreame_vacuum] Integration start failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/miio/miioprotocol.py", line 193, in send
    data, addr = s.recvfrom(4096)
                 ^^^^^^^^^^^^^^^^
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/miio/miioprotocol.py", line 193, in send
    data, addr = s.recvfrom(4096)
                 ^^^^^^^^^^^^^^^^
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 326, in _async_update_data
    await self.hass.async_add_executor_job(self.device.update)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 996, in update
    self.connect_device()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 733, in connect_device
    self._request_properties()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 262, in _request_properties
    result = self._protocol.get_properties(props[:15])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 543, in get_properties
    return self.send("get_properties", parameters=parameters, retry_count=retry_count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 536, in send
    return self.device.send(method, parameters=parameters, retry_count=retry_count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/miio/miioprotocol.py", line 233, in send
    return self.send(
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/miio/miioprotocol.py", line 241, in send
    raise DeviceException("No response from the device") from ex
miio.exceptions.DeviceException: No response from the device`

**Comment by KSchmeeds** [comment]
It looks like checking the box "Prefer Cloud Connection" allows it to connect again.
