### ISSUE TITLE
DreameBot L20 Ultra Current Map data decryption failed

### ISSUE THREAD

**Issue by glarizza** [Tasshack/dreame-vacuum#496]
**Describe the bug**
Last night I installed version 2.0.0b14 of the dreame vacuum custom component into Home Assistant (Docker container version, running on Synology NAS) and used my Dreamhome app credentials with map support to load in my new Dreamebot L20 ultra and its map. It worked great last night, and I was able to view the map in HA.  This morning when I went to view the Dreame integration in HA, all the entities were showing as unavailable. I reloaded the integration and all the values for the entities came back. When I tried to click on the current map entity (which does get updated), the image has a question mark and isn't being displayed.  When I went into the container logs for HA, I noticed the following log entry being repeated:

```
[31m2024-04-17 12:53:02.555 ERROR (Thread-6833 (_thread_main)) [custom_components.dreame_vacuum.dreame.map] Map data decryption failed: Invalid IV size (0) for CBC.. Private key might be missing, please report this issue with your device model https://github.com/Tasshack/dreame-vacuum/issues/new?assignees=Tasshack&labels=bug&template=bug_report.md&title=Map%20data%20decryption%20failed[0m
```

**To Reproduce**
- Install version 2.0.0b14 of the component
- Connect to Dreamehome app via login credentials
- Connect to L20 Ultra
- Wait overnight
- Reload integration
- Open current map entity

**Expected behavior**
I expected the current map entity to display the same map I'm seeing in my dreamehome app.

**Screenshots**
<img width="403" alt="Screenshot 2024-04-17 at 1 07 19 PM" src="https://github.com/Tasshack/dreame-vacuum/assets/139824/fa8b484f-6d6e-413c-8b68-44864eb34b16">
<img width="595" alt="Screenshot 2024-04-17 at 1 07 23 PM" src="https://github.com/Tasshack/dreame-vacuum/assets/139824/7dd8f5cd-eeba-4fa3-a60c-45c078b40dd5">
<img width="1531" alt="Screenshot 2024-04-17 at 12 57 54 PM" src="https://github.com/Tasshack/dreame-vacuum/assets/139824/85ac585a-7461-438d-afa5-73f7b65ce7df">

**Additional Information (please complete the following information)**
 - Model Name [e.g. dreame.vacuum.p2028]: **dreame.vacuum.r2253b (L20 Ultra)**
 - Firmware Version [e.g. 1156]: **1518**
 - Home Assistant Version: **Core: 2024.4.3 Frontend: 20240404.2**
 - Configuration Type [With or without map support]: **With Map support**
 - Errors or warnings shown in the HA logs (if applicable):

**Comment by glarizza** [comment]
I tried to reload the integration, and that didn't help the issue (same problem and errors). So I did a restart of Home Assistant, waited for everything to load, and then tried to display the map (but hit the same problem).  Here's what was in the logs:

```
2024/04/17 13:40:42	stdout	[20:40:42] INFO: [32mHome Assistant Core finish process exit code 100[0m
2024/04/17 13:40:38	stdout	RuntimeError: can't create new thread at interpreter shutdown[0m
2024/04/17 13:40:38	stdout	    _start_new_thread(self._bootstrap, ())
2024/04/17 13:40:38	stdout	  File "/usr/local/lib/python3.12/threading.py", line 992, in start
2024/04/17 13:40:38	stdout	    self._update_timer.start()
2024/04/17 13:40:38	stdout	  File "/config/custom_components/dreame_vacuum/dreame/map.py", line 1199, in schedule_update
2024/04/17 13:40:38	stdout	    self.schedule_update(max(self._update_interval - (time.time() - start), 1))
2024/04/17 13:40:38	stdout	  File "/config/custom_components/dreame_vacuum/dreame/map.py", line 470, in _update_task
2024/04/17 13:40:38	stdout	    self.function(*self.args, **self.kwargs)
2024/04/17 13:40:38	stdout	  File "/usr/local/lib/python3.12/threading.py", line 1431, in run
2024/04/17 13:40:38	stdout	    self.run()
2024/04/17 13:40:38	stdout	  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
2024/04/17 13:40:38	stdout	Traceback (most recent call last):
2024/04/17 13:40:38	stdout	[31m2024-04-17 13:40:38.696 ERROR (Thread-8892) [root] Uncaught thread exception
2024/04/17 13:40:35	stdout	RuntimeError: can't create new thread at interpreter shutdown[0m
2024/04/17 13:40:35	stdout	    _start_new_thread(self._bootstrap, ())
2024/04/17 13:40:35	stdout	  File "/usr/local/lib/python3.12/threading.py", line 992, in start
2024/04/17 13:40:35	stdout	    self._update_timer.start()
2024/04/17 13:40:35	stdout	  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1961, in schedule_update
2024/04/17 13:40:35	stdout	    self.schedule_update(self._update_interval)
2024/04/17 13:40:35	stdout	  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1588, in _update_task
2024/04/17 13:40:35	stdout	    self.function(*self.args, **self.kwargs)
2024/04/17 13:40:35	stdout	  File "/usr/local/lib/python3.12/threading.py", line 1431, in run
2024/04/17 13:40:35	stdout	    self.run()
2024/04/17 13:40:35	stdout	  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
2024/04/17 13:40:35	stdout	Traceback (most recent call last):
2024/04/17 13:40:35	stdout	[31m2024-04-17 13:40:35.109 ERROR (Thread-8894) [root] Uncaught thread exception
2024/04/17 13:40:34	stdout	Found 3 non-daemonic threads.
2024/04/17 13:39:51	stdout	[31m2024-04-17 13:39:51.650 ERROR (Thread-6833 (_thread_main)) [custom_components.dreame_vacuum.dreame.map] Map data decryption failed: Invalid IV size (0) for CBC.. Private key might be missing, please report this issue with your device model https://github.com/Tasshack/dreame-vacuum/issues/new?assignees=Tasshack&labels=bug&template=bug_report.md&title=Map%20data%20decryption%20failed[0m
2024/04/17 13:39:47	stdout	[31m2024-04-17 13:39:47.620 ERROR (Thread-6833 (_thread_main)) [custom_components.dreame_vacuum.dreame.map] Map data decryption failed: Invalid IV size (0) for CBC.. Private key might be missing, please report this issue with your device model https://github.com/Tasshack/dreame-vacuum/issues/new?assignees=Tasshack&labels=bug&template=bug_report.md&title=Map%20data%20decryption%20failed[0m
2024/04/17 13:39:42	stdout	[31m2024-04-17 13:39:42.629 ERROR (Thread-6833 (_thread_main)) [custom_components.dreame_vacuum.dreame.map] Map data decryption failed: Invalid IV size (0) for CBC.. Private key might be missing, please report this issue with your device model https://github.com/Tasshack/dreame-vacuum/issues/new?assignees=Tasshack&labels=bug&template=bug_report.md&title=Map%20data%20decryption%20failed[0m
```

**Comment by glarizza** [comment]
> Need full model number

Is that the dreame.vacuum.r2253b value I provided or is there another model number I’m missing somewhere?

**Comment by glarizza** [comment]
All good, just wanted to make sure that was the right piece of data :)

Okay, I went to Settings -> Integrations -> Dreame and then clicked on the three dots to the right of the DreameBot L20 Ultra device, and deleted it.

I then went to Settings -> Integrations -> Add Integration and added the Dreame integration again. I used my Dreamehome app creds and selected the `us` country code, then selected all the defaults for the L20 Ultra device it discovered. 

I went down to select the Current Map entity, and it's still empty (question mark icon).

I restarted Home Assistant, waited for it to come back up, and then checked the Current Map entity, but it's the same problem.

Here's what was in the logs:

```
2024/04/18 09:33:52	stdout	RuntimeError: can't create new thread at interpreter shutdown[0m
2024/04/18 09:33:52	stdout	    _start_new_thread(self._bootstrap, ())
2024/04/18 09:33:52	stdout	  File "/usr/local/lib/python3.12/threading.py", line 992, in start
2024/04/18 09:33:52	stdout	    self._update_timer.start()
2024/04/18 09:33:52	stdout	  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1961, in schedule_update
2024/04/18 09:33:52	stdout	    self.schedule_update(self._update_interval)
2024/04/18 09:33:52	stdout	  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1588, in _update_task
2024/04/18 09:33:52	stdout	    self.function(*self.args, **self.kwargs)
2024/04/18 09:33:52	stdout	  File "/usr/local/lib/python3.12/threading.py", line 1431, in run
2024/04/18 09:33:52	stdout	    self.run()
2024/04/18 09:33:52	stdout	  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
2024/04/18 09:33:52	stdout	Traceback (most recent call last):
2024/04/18 09:33:52	stdout	[31m2024-04-18 09:33:52.166 ERROR (Thread-9203) [root] Uncaught thread exception
2024/04/18 09:33:47	stdout	Found 3 non-daemonic threads.
```

I don't get the "Map data decryption failed" message anymore, just that stack trace and nothing showing up for the Current Map entity.

**Comment by glarizza** [comment]
What's interesting is that the icon picture of the map entity IS correct - I have changed the map in the dreamehome app since yesterday and the colors and layout in that icon do reflect those changes.  But when I click on that entity I still get a missing image.

<img width="368" alt="Screenshot 2024-04-18 at 9 47 38 AM" src="https://github.com/Tasshack/dreame-vacuum/assets/139824/e80f5386-0c4e-4b5e-ad2e-df540fcf9552">
<img width="656" alt="Screenshot 2024-04-18 at 9 49 21 AM" src="https://github.com/Tasshack/dreame-vacuum/assets/139824/8236eb9d-25e3-4e6b-bf3d-64f2f189187e">

**Comment by glarizza** [comment]
Okay, removing the integration from HACS and re-adding it has fixed the problem. I'll monitor it for a day, and if the problem doesn't come back again we can close the issue tomorrow.

**Comment by glarizza** [comment]
Still looking good the next day, so I'm going to close the issue.
