### ISSUE TITLE
Scripts for rooms cleaning stopped working after last HA update

### ISSUE THREAD

**Issue by DavideBoschi** [Tasshack/dreame-vacuum#541]
Hello, on my HA I have some scripts to start the cleaning of the different house rooms through alexa. Since the last update of HA, every time I try to run one of this script I get this error:

Invocazione del servizio script/s01_bob_pulizia_bagno non riuscita. Detected that custom integration 'dreame_vacuum' calls async_write_ha_state from a thread at custom_components/dreame_vacuum/vacuum.py, line 648: self.async_write_ha_state(). Please report it to the author of the 'dreame_vacuum' custom integration

I report the code of one of the scripts mentioned above:

`alias: S01 - BOB, PULIZIA BAGNO
sequence:
  - service: dreame_vacuum.vacuum_clean_segment
    data:
      segments: 2
    target:
      device_id: 730679107eb17cdc050a5bff1df636b1
  - if:
      - condition: state
        entity_id: vacuum.bob
        state: cleaning
    then:
      - delay:
          hours: 0
          minutes: 0
          seconds: 8
          milliseconds: 0
      - service: notify.alexa_media_echo_dot_cucina
        data:
          message: Bob inizia la pulizia del bagno
mode: single
icon: mdi:robot-vacuum`

Some other details about the error from HA logs:

S01 - BOB, PULIZIA BAGNO: Error executing script. Unexpected error for call_service at pos 1: Detected that custom integration 'dreame_vacuum' calls async_write_ha_state from a thread at custom_components/dreame_vacuum/vacuum.py, line 648: self.async_write_ha_state(). Please report it to the author of the 'dreame_vacuum' custom integration.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 501, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 736, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 699, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/vacuum.py", line 794, in async_clean_segment
    await self._try_command(
  File "/config/custom_components/dreame_vacuum/entity.py", line 175, in _try_command
    await self.hass.async_add_executor_job(partial(func, *args, **kwargs))
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 3419, in clean_segment
    self._update_status(
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 579, in _update_status
    self._update_property(DreameVacuumProperty.STATE, new_state.value)
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 613, in _update_property
    self._property_changed()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1409, in _property_changed
    self._update_callback()
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 538, in async_set_updated_data
    super().async_set_updated_data(self._device)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 450, in async_set_updated_data
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/config/custom_components/dreame_vacuum/vacuum.py", line 648, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in async_write_ha_state
    self.hass.verify_event_loop_thread("async_write_ha_state")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'dreame_vacuum' calls async_write_ha_state from a thread at custom_components/dreame_vacuum/vacuum.py, line 648: self.async_write_ha_state(). Please report it to the author of the 'dreame_vacuum' custom integration

[545829458240] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 654, in _service_handler
    response = await self._async_start_run(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 612, in _async_start_run
    script_result = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 643, in _async_run
    return await self.script.async_run(script_vars, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1731, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 503, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 533, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 501, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 736, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 699, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/vacuum.py", line 794, in async_clean_segment
    await self._try_command(
  File "/config/custom_components/dreame_vacuum/entity.py", line 175, in _try_command
    await self.hass.async_add_executor_job(partial(func, *args, **kwargs))
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 3419, in clean_segment
    self._update_status(
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 579, in _update_status
    self._update_property(DreameVacuumProperty.STATE, new_state.value)
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 613, in _update_property
    self._property_changed()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1409, in _property_changed
    self._update_callback()
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 538, in async_set_updated_data
    super().async_set_updated_data(self._device)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 450, in async_set_updated_data
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/config/custom_components/dreame_vacuum/vacuum.py", line 648, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in async_write_ha_state
    self.hass.verify_event_loop_thread("async_write_ha_state")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'dreame_vacuum' calls async_write_ha_state from a thread at custom_components/dreame_vacuum/vacuum.py, line 648: self.async_write_ha_state(). Please report it to the author of the 'dreame_vacuum' custom integration.

Info about my currently HA installation:

Core: 2024.5.3
Supervisor: 2024.05.1
Operating System: 12.3
Frontend: 20240501.1

I'm running HA on a raspberry Pi 4.

Thank you in advance for the help!

**Comment by PlayFaster** [comment]
Hi. You need to install the latest version of the Dreame Integration, currently v2.0.0b14 , even if it does not show as needing to be updated. Several people, including myself have experianced this, see some of the recent closed issues such as [#529](https://github.com/Tasshack/dreame-vacuum/issues/529)

**Comment by DavideBoschi** [comment]
> Hi. You need to install the latest version of the Dreame Integration, currently v2.0.0b14 , even if it does not show as needing to be updated. Several people, including myself have experianced this, see some of the recent closed issues such as [#529](https://github.com/Tasshack/dreame-vacuum/issues/529)

Hello, thank you very much for the help, yes I confirm, problem solved after version update!!
