### ISSUE TITLE
Zones, pin & go, and Rooms (segments) don't work with X10

### ISSUE THREAD

**Issue by markoskocic** [Tasshack/dreame-vacuum#569]
**Describe the bug**
I have Xiaomi Robot Vacuum X10 vacuum that I have successfully added to my HA using this integration. Using custom:xiaomi-vacuum-map-card card I can add it to my dashboard. Everything* works except sending it to clean in the selected rooms, zones or to goto to a specified location using pin & go. In "Mi Home" app I am able to select one or two rooms and send it to clean. Not using this integration.

* I can send it to clean the entire home, stop it, send it back to base, read statuses of sensors, etc.

**To Reproduce**
Vacuum configured using Mi Home app, map exists, rooms labeled
Configure custom:xiaomi-vacuum-map-card card on the dashboard in HA
Edit card
Use "generate room config" feature in the card view and save
Select "Rooms" from the dropdown (below the map)
Click the Play button on the right of Rooms (not the one below)
An error message is shown after 2-3s 

**Expected behavior**
Vacuum will go to that room and start cleaning

**Screenshots**
![image](https://github.com/Tasshack/dreame-vacuum/assets/2571051/14ca8f7a-f83a-409d-b5c2-bc316a50b312)
![image](https://github.com/Tasshack/dreame-vacuum/assets/2571051/09cac473-0998-421e-bb2d-48e9f6a7b7be)

**Additional Information (please complete the following information)**
 - Model Name: Xiaomi Robot Vacuum X10 vacuum (I believe this is dreame.vacuum.r2215)
 - Firmware Version [e.g. 1156]: 4.3.9_1308
 - Home Assistant Version: 2024.5.5
 - Configuration Type [With or without map support]: with map support
 - Errors or warnings shown in the HA logs (if applicable): see below
------------------------------------------------------
 Warning:
------------------------------------------------------
 This error originated from a custom integration.

Logger: custom_components.dreame_vacuum.dreame.protocol
Source: custom_components/dreame_vacuum/dreame/protocol.py:331
integration: Dreame Vacuum (documentation, issues)
First occurred: 7:21:59 PM (8 occurrences)
Last logged: 7:45:54 PM

Error while executing request: https://de.api.io.mi.com/app/v2/home/rpc/1052084517 HTTPSConnectionPool(host='de.api.io.mi.com', port=443): Read timed out. (read timeout=3)

------------------------------------------------------
 Error (follows immediately after):
------------------------------------------------------
 Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:239
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 7:22:02 PM (4 occurrences)
Last logged: 7:45:54 PM

[139728102344128] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/vacuum.py", line 734, in async_send_command
    await self._try_command(
  File "/config/custom_components/dreame_vacuum/entity.py", line 126, in _try_command
    raise HomeAssistantError(str(exc)) from None
homeassistant.exceptions.HomeAssistantError: Unable to discover the device over cloud

**Comment by markoskocic** [comment]
And a popup of the message that I didn't capture in the shared screenshots
![image](https://github.com/Tasshack/dreame-vacuum/assets/2571051/6a1b10de-4228-471f-aa3e-15f3b1b2f9d5)

PS. I've also tried with v2.0.0b14, but faced the same issue

**Comment by markoskocic** [comment]
Thank you, this was it and I apologize for missing it in the readme section. :( Please keep up the good work!
