### ISSUE TITLE
Integration stopped working after HA update

### ISSUE THREAD

**Issue by exSnake** [Tasshack/dreame-vacuum#583]
```
2024-06-08 18:01:53.103 INFO (SyncWorker_8) [custom_components.dreame_vacuum.dreame.device] Property STREAM_SPACE Added: {"operType":"get_properties","operation":"start","result":0,"status":0}
2024-06-08 18:01:53.109 WARNING (SyncWorker_8) [homeassistant.helpers.frame] Detected that integration 'persistent_notification' calls async_dispatcher_send from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_dispatcher_send at homeassistant/components/persistent_notification/__init__.py, line 114: async_dispatcher_send(, please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+persistent_notification%22
2024-06-08 18:01:53.114 WARNING (MainThread) [custom_components.dreame_vacuum] Integration start failed: Traceback (most recent call last):
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 490, in _async_update_data
    await self.hass.async_add_executor_job(self._device.update)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 2329, in update
    self.connect_device()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1727, in connect_device
    self._request_properties()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 546, in _request_properties
    return self._handle_properties(results)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 471, in _handle_properties
    callback[0](callback[1])
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 215, in _task_status_changed
    self._check_consumables()
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 361, in _check_consumables
    self._check_consumable(
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 327, in _check_consumable
    self._create_persistent_notification(
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 427, in _create_persistent_notification
    persistent_notification.async_create(
  File "/usr/src/homeassistant/homeassistant/components/persistent_notification/__init__.py", line 114, in async_create
    async_dispatcher_send(
  File "/usr/src/homeassistant/homeassistant/helpers/dispatcher.py", line 214, in async_dispatcher_send
    hass.verify_event_loop_thread("async_dispatcher_send")
  File "/usr/src/homeassistant/homeassistant/core.py", line 447, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 159, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 197, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that integration 'persistent_notification' calls async_dispatcher_send from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_dispatcher_send at homeassistant/components/persistent_notification/__init__.py, line 114: async_dispatcher_send(. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+persistent_notification%22.

2024-06-08 18:01:53.114 INFO (MainThread) [custom_components.dreame_vacuum.dreame.device] Disconnect
```

Home Assistant:
Core 2024.6.1
Supervisor 2024.06.0
Operating System 12.3

**Comment by SkillersInc** [comment]
Also having this issue. currently running v2.0.0b11. I have an identical error.
