### ISSUE TITLE
Dreame X40 Ultra various functions and the map no longer work

### ISSUE THREAD

**Issue by o0shojo0o** [Tasshack/dreame-vacuum#590]
**Describe the bug**
Suddenly various functions and the map no longer work.
There was a firmware update, but I'm not sure if that's the reason. 

**Expected behavior**
That the options and map work again 

**Screenshots**
![image](https://github.com/Tasshack/dreame-vacuum/assets/19333515/62fdbd07-4361-43ab-8613-7bea663ef4c7)
![image](https://github.com/Tasshack/dreame-vacuum/assets/19333515/bb790425-02bd-48c5-b663-46f1c1852072)

**Additional Information (please complete the following information)**
 - Model Name: dreame.vacuum.r2449a
 - Firmware Version: 4.3.9_1392
 - Home Assistant Version: 2024.6.2
 - Integration Version: v2.0.0b15
 - Configuration Type: With map support
 - Errors or warnings shown in the HA logs (if applicable):
```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.dreame_vacuum.dreame.map
Quelle: custom_components/dreame_vacuum/dreame/map.py:6284
Integration: Dreame Vacuum (Dokumentation, Probleme)
Erstmals aufgetreten: 19:25:51 (1 Vorkommnisse)
Zuletzt protokolliert: 19:25:51

Map render Failed: Traceback (most recent call last): File "/config/custom_components/dreame_vacuum/dreame/map.py", line 6040, in render_map image = self.render_objects(cached_layers, map_data, robot_status, station_status, image, object_scale) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/map.py", line 6588, in render_objects cached_layers[MapRendererLayer.SEGMENT][k] = self.render_segment( ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/map.py", line 7681, in render_segment self.color_scheme.segment[segment.color_index][1] ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^ TypeError: tuple indices must be integers or slices, not NoneType
```

**Comment by o0shojo0o** [comment]
The problem is also present with v2.0.0b14

**Comment by loebi-ch** [comment]
See #591 with a quick hack for the map.

No idea about the various functions...

**Comment by o0shojo0o** [comment]
Yes, it fixed all the problems, but it's strange that it worked before...
Or does the latest firmware update of the X40 have something to do with it?
