### ISSUE TITLE
Have to manually install updates

### ISSUE THREAD

**Issue by albaintor** [Tasshack/dreame-vacuum#598]
For an unknown reason, the integration won't update by itself : when a new version is detected, I ask to install it but it never ends.
I have to download the release and upload it to home assistant custom_components folder
![image](https://github.com/Tasshack/dreame-vacuum/assets/118518828/76772af0-459e-4a45-a698-4614672220ab)

There is an error during the download, don't know why, here are the HA logs :
```
2024-06-16 08:29:50.521 ERROR (MainThread) [custom_components.hacs] <Integration Tasshack/dreame-vacuum> 'utf-8' codec can't decode byte 0xb2 in position 7167: invalid start byte
2024-06-16 08:29:51.307 ERROR (MainThread) [custom_components.hacs] <Integration Tasshack/dreame-vacuum> 'utf-8' codec can't decode byte 0xb2 in position 7167: invalid start byte
2024-06-16 08:29:54.303 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281471151907472] Error handling message: Unknown error (unknown_error) Damien from 192.168.1.26 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 232, in hacs_repository_download
    await repository.update_repository(force=True)
  File "/config/custom_components/hacs/utils/decorator.py", line 28, in wrapper
    result = await function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/repositories/integration.py", line 115, in update_repository
    if not await self.common_update(ignore_issues, force) and not force:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/utils/decorator.py", line 28, in wrapper
    result = await function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/repositories/base.py", line 555, in common_update
    self.additional_info = await self.async_get_info_file_contents()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/repositories/base.py", line 747, in async_get_info_file_contents
    return await self.get_documentation(filename=info_files[0]) or ""
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/repositories/base.py", line 1353, in get_documentation
    result.decode(encoding="utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 7167: invalid start byte
```

Thank you for your support

**Comment by albaintor** [comment]
Thank you, resolved !

De : Tasshack ***@***.***>
Envoyé : dimanche 16 juin 2024 18:01
À : Tasshack/dreame-vacuum ***@***.***>
Cc : albaintor ***@***.***>; Author ***@***.***>
Objet : Re: [Tasshack/dreame-vacuum] Have to manually install updates (Issue #598)


Sorry wrong one.
#429<https://github.com/Tasshack/dreame-vacuum/issues/429>

-
