### ISSUE TITLE
Integration does not start: unable to login to device over cloud

### ISSUE THREAD

**Issue by Cikkajes** [Tasshack/dreame-vacuum#602]
**Describe the bug**
All of a sudden, in the last 2 days the integration does not start with the message: setting failed, unable to login to device over cloud

**To Reproduce**
N/A

**Expected behavior**
Integration should start normally

**Screenshots**
N/A

**Additional Information (please complete the following information)**
 - Model Name [e.g. dreame.vacuum.p2028]: dreame.vacuum.r2253w
 - Firmware Version [e.g. 1156]: 4.3.6_1639
 - Home Assistant Version: 2024.6.3
 - Configuration Type [With or without map support]: with map support
 - Errors or warnings shown in the HA logs (if applicable):
```
2024-06-18 09:42:57.390 WARNING (MainThread) [custom_components.dreame_vacuum] Integration start failed: Traceback (most recent call last):

  File "/config/custom_components/dreame_vacuum/coordinator.py", line 326, in _async_update_data
    await self.hass.async_add_executor_job(self.device.update)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 996, in update
    self.connect_device()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 725, in connect_device
    self.info = DreameVacuumDeviceInfo(self._protocol.connect())
                                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 495, in connect
    response = self.send("miIO.info", retry_count=retry_count)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 521, in send
    raise DeviceException("Unable to login to device over cloud")
custom_components.dreame_vacuum.dreame.exceptions.DeviceException: Unable to login to device over cloud


2024-06-18 09:44:45.405 INFO (MainThread) [custom_components.dreame_vacuum.dreame.device] Disconnect
2024-06-18 09:44:45.410 DEBUG (MainThread) [custom_components.dreame_vacuum] Finished fetching dreame_vacuum data in 0.593 seconds (success: False)
```

**Comment by Cikkajes** [comment]
I tried removing and re adding both device and integration, but nothing solves it. Now I cannot add anything as it gives me error at setup. I do not understand why it can't connect, no passwords were changed, nothing was changed. How can it have stopped connecting all of a sudden? Nothing changed for the network either.

**Comment by Cikkajes** [comment]
Solved by installing the latest beta version. Not sure what the issue was. Thanks

________________________________
