### ISSUE TITLE
Memory leak / Causing HA to freeze

### ISSUE THREAD

**Issue by StahlTim** [Tasshack/dreame-vacuum#74]
**Describe the bug**
The integration produces error messages in a regular basis (few minutes / couple of seconds apart). Furthermore, the RAM and SWAP of the system steadily gets filled up. Once it reaches 100%, the system does not respond anymore.

**To Reproduce**
Disconnect the robot (power off the robot or toggle WIFI off)

**Expected behavior**

**Screenshots / Log**
```
2022-12-26 09:47:38.054 ERROR (MainThread) [custom_components.dreame_vacuum] Update failed: Traceback (most recent call last):
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 314, in _async_update_data
    await self.hass.async_add_executor_job(self.device.update)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 982, in update
    self.connect_device()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 714, in connect_device
    self.info = DreameVacuumDeviceInfo(self._protocol.connect())
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 482, in connect
    response = self.send("miIO.info", retry_count=retry_count)
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 509, in send
    raise DeviceException("Unable to discover the device over cloud") from None
custom_components.dreame_vacuum.dreame.exceptions.DeviceException: Unable to discover the device over cloud

2022-12-26 09:48:59.728 ERROR (MainThread) [custom_components.dreame_vacuum] Update failed: Traceback (most recent call last):
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 314, in _async_update_data
    await self.hass.async_add_executor_job(self.device.update)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 982, in update
    self.connect_device()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 714, in connect_device
    self.info = DreameVacuumDeviceInfo(self._protocol.connect())
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 482, in connect
    response = self.send("miIO.info", retry_count=retry_count)
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 509, in send
    raise DeviceException("Unable to discover the device over cloud") from None
custom_components.dreame_vacuum.dreame.exceptions.DeviceException: Unable to discover the device over cloud

2022-12-26 09:50:21.339 ERROR (MainThread) [custom_components.dreame_vacuum] Update failed: Traceback (most recent call last):
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 314, in _async_update_data
    await self.hass.async_add_executor_job(self.device.update)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 982, in update
    self.connect_device()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 714, in connect_device
    self.info = DreameVacuumDeviceInfo(self._protocol.connect())
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 482, in connect
    response = self.send("miIO.info", retry_count=retry_count)
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 509, in send
    raise DeviceException("Unable to discover the device over cloud") from None
custom_components.dreame_vacuum.dreame.exceptions.DeviceException: Unable to discover the device over cloud

2022-12-26 09:51:43.060 ERROR (MainThread) [custom_components.dreame_vacuum] Update failed: Traceback (most recent call last):
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 314, in _async_update_data
    await self.hass.async_add_executor_job(self.device.update)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 982, in update
    self.connect_device()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 714, in connect_device
    self.info = DreameVacuumDeviceInfo(self._protocol.connect())
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 482, in connect
    response = self.send("miIO.info", retry_count=retry_count)
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 509, in send
    raise DeviceException("Unable to discover the device over cloud") from None
custom_components.dreame_vacuum.dreame.exceptions.DeviceException: Unable to discover the device over cloud

2022-12-26 09:53:04.939 ERROR (MainThread) [custom_components.dreame_vacuum] Update failed: Traceback (most recent call last):
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 314, in _async_update_data
    await self.hass.async_add_executor_job(self.device.update)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 982, in update
    self.connect_device()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 714, in connect_device
    self.info = DreameVacuumDeviceInfo(self._protocol.connect())
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 482, in connect
    response = self.send("miIO.info", retry_count=retry_count)
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 509, in send
    raise DeviceException("Unable to discover the device over cloud") from None
custom_components.dreame_vacuum.dreame.exceptions.DeviceException: Unable to discover the device over cloud

2022-12-26 09:54:26.638 ERROR (MainThread) [custom_components.dreame_vacuum] Update failed: Traceback (most recent call last):
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 314, in _async_update_data
    await self.hass.async_add_executor_job(self.device.update)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 982, in update
    self.connect_device()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 714, in connect_device
    self.info = DreameVacuumDeviceInfo(self._protocol.connect())
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 482, in connect
    response = self.send("miIO.info", retry_count=retry_count)
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 509, in send
    raise DeviceException("Unable to discover the device over cloud") from None
custom_components.dreame_vacuum.dreame.exceptions.DeviceException: Unable to discover the device over cloud

2022-12-26 09:55:48.313 ERROR (MainThread) [custom_components.dreame_vacuum] Update failed: Traceback (most recent call last):
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 314, in _async_update_data
    await self.hass.async_add_executor_job(self.device.update)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 982, in update
    self.connect_device()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 714, in connect_device
    self.info = DreameVacuumDeviceInfo(self._protocol.connect())
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 482, in connect
    response = self.send("miIO.info", retry_count=retry_count)
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 509, in send
    raise DeviceException("Unable to discover the device over cloud") from None
custom_components.dreame_vacuum.dreame.exceptions.DeviceException: Unable to discover the device over cloud
```

**Additional Information (please complete the following information)**
 - Model Name: dreame_bot_w10
 - Firmware Version [e.g. 1156]:
 - Home Assistant Version: 2022.12.8
 - Configuration Type [With or without map support]: with map - cloud preferred
 - Errors or warnings shown in the HA logs (if applicable): (see above)

**Comment by StahlTim** [comment]
Exactly, it uses more and more memory over time (as described in the issue). See also screenshot.

After a couple of hours, the HA becomes unresponsive, once it reaches 100% (arrow). If the plugin is disabled and HA restarted, the memory stays constant.

![IMG-20221226-WA0000-01](https://user-images.githubusercontent.com/10382649/209586561-1451d0ed-50c1-4577-b369-8057227d28cc.jpeg)

**Comment by StahlTim** [comment]
> I think this issue is related to the `Force Cloud` feature. If your device is at the same network with HA you don't need to enable this feature until i fix it.

Actually (sadly) I have to stick to "force cloud", since the robot is on another network.

**Comment by antoniolanza1996** [comment]
Hello @Tasshack, I'm using a RPI3 with 1 GB of RAM and I'm also having these issues (also related to #52 and other duplicated issues).

Some more detailed info:
1. With default swap memory my system will start rebooting as soon as I try to add my robot.
2. I've increased swap memory to 2 GB. Then, I have been able to integrate my robot (117 entities, wow, kudos :smile:) and add a [Xiaomi Vacuum Map Card](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card). However, after few minutes of usage, HA is unusable, then it will start rebooting.

I think this is a very important point to analyze, also considering that a lot of people have installed HA on RPIs. Then, all of us will use your amazing work done on reverse engineering the official Mi Home.

Btw I'll follow the updates on https://github.com/Tasshack/dreame-vacuum/issues/52#issuecomment-1380478994. Let's consider that I am totally available for any further clarification on my setup.

**Comment by antoniolanza1996** [comment]
I tried the integration without map support. It found out around 50 entities and no problem at all. I'm using HA without any trouble.

**Comment by antoniolanza1996** [comment]
@Tasshack i'm still using the integration without map support and no problem at all. As supposed, map is the problem here.

I'm for further support if needed.

**Comment by Shadow941** [comment]
I have a hang-up problem with my RPI4  when I turn on to display "path" on map. everything works perfectly without this parameter

**Comment by tjuanma** [comment]
> @StahlTim @antoniolanza1996 can you test this issue on the latest beta version.
> 
> https://github.com/Tasshack/dreame-vacuum/releases/tag/v2.0.0b5

problem persists on beta 2.0.0b5 with rpi3

**Comment by ImpieYay** [comment]
I have the same issue on a Raspberry Pi 4 (4 GB) with v1.0.1. It started when I was moving furniture about and placed the robot (dreame.vacuum.p2028) upside down, causing the integration setup to fail (after reboot). Memory leak is a bit over 100 MiB/hour. 

I reckon the repro steps are:
1. Disconnect the robot (e.g. by placing it upside down)
2. Reboot Home Assistant (to get integration in setup attempt loop)

The log is spammed roughly every 90 seconds with the message below. I'll try beta 2.0.0b5 to see if anything changes. 

```
ERROR (MainThread) [custom_components.dreame_vacuum] Update failed: Traceback (most recent call last):
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 314, in _async_update_data
    await self.hass.async_add_executor_job(self.device.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 995, in update
    self.connect_device()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 725, in connect_device
    self.info = DreameVacuumDeviceInfo(self._protocol.connect())
                                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 487, in connect
    response = self.send("miIO.info", retry_count=retry_count)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 519, in send
    return self.device.send(method, parameters=parameters, retry_count=retry_count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 161, in send
    self.send_handshake()
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 74, in send_handshake
    raise DeviceException("Unable to discover the device %s" % self.ip)
``` 
![image](https://github.com/Tasshack/dreame-vacuum/assets/88806024/948ea82f-e8dc-489c-b5d2-25c5379889cd)

**Comment by ImpieYay** [comment]
This was with stable release v1.0.1 - but I'm currently testing beta 2.0.0b6.

**Comment by HAisibora** [comment]
Same problem here with 2.0.0b6 on a Debian HA core installation: After starting HA with my Dreame D10 Plus offline, the HA log is spammed with the message quoted above by @ImpieYay. This creates more and more stale CLOSE_WAIT TCP-sessions leading to a HA crash after a few hours. Low resolution map on or off doesn't make a difference here.
There must be a way to stop spamming the log and to regularly close these sessions, thus avoiding the crash - I hope ;-)

**Comment by kdefarge** [comment]
Hi, same problem for me with 2.0.0b6.

i have raspberry 3b on last raspbian light with HA 2023.10.5 core 2023.10.5.

Have an error when i add integration in version 2.0.0b6 => ": {« message »:« Invalid handler specified »}"
```shell
Error occurred loading flow for integration dreame_vacuum: No module named 'paho'
``` 
So i install paho-mqtt in my virtual python environnement
```shell
pip3 install paho-mqtt
``` 
(dont know if should setup https://www.home-assistant.io/integrations/mqtt/)

Now i can add my entitie, i setup with my Dreame credentials but have a memory problem : 
![memory usage](https://github.com/Tasshack/dreame-vacuum/assets/1819360/2728ea92-7021-4378-826e-88babeabfe19)

And it's strange but when i desactivate my vacuum entity , the memory stay high and i should restart HA for fix the memory.

So i have more 400 MiB when i use service + vacuum entity with Dreame credentials.

When have time, i will look the code if i can help too. It's goog project.
