### ISSUE TITLE
AttributeError: object has no attribute '_webrtc_provider'

### ISSUE THREAD

**Issue by tjorim** [Tasshack/dreame-vacuum#778]
**Describe the bug**
Getting the following webrtc error since the introduction in HA 2024.11

**To Reproduce**
Update HA core to 2024.11.0b0 and check the logs.

**Expected behavior**
No errors in the log.

**Additional Information (please complete the following information)**
 - Model Name [e.g. dreame.vacuum.p2028]: n/a
 - Firmware Version [e.g. 1156]: n/a
 - Home Assistant Version: 2024.11
 - Configuration Type [With or without map support]: with map
 - Errors or warnings shown in the HA logs (if applicable):
```
Logger: homeassistant.components.camera
Source: helpers/entity_platform.py:599
integration: Camera (documentation, issues)
First occurred: 20:54:52 (3 occurrences)
Last logged: 20:54:59

Error adding entity camera.d10s_pro_map for domain camera with platform dreame_vacuum
Error adding entity camera.d10s_pro_map_1 for domain camera with platform dreame_vacuum
Error adding entity camera.d10s_pro_map_2 for domain camera with platform dreame_vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 599, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 918, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1366, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 782, in async_internal_added_to_hass
    await self.async_refresh_providers(write_state=False)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 790, in async_refresh_providers
    old_provider = self._webrtc_provider
                   ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DreameVacuumCameraEntity' object has no attribute '_webrtc_provider'
```

Confirmed as not a core issue https://github.com/home-assistant/core/issues/129532.
"The issue is in the CC not initializing the Camera Entity by calling the parent class init method when defining its own init method."

**Comment by melianor** [comment]
Hi @Tasshack , 
Your comment below referenced issue #779 and in the issue itself, sounds a bit like #779 will not be merged. 
Could you please clarify? 
Should it be closed, will this update also make it into the next pre-release version?

Thanks a lot for all your efforts and the pre-release version for the new Dreame vacuuums
Cheers, Mel

**Comment by taifunk** [comment]
To resolve the issue temporarily, I added the missing attributes to the DreameVacuumCameraEntity class in the camera.py file of the integration. Specifically, I added the following lines to the class:

```
_webrtc_provider = None
_legacy_webrtc_provider = None
_supports_native_sync_webrtc = False
_supports_native_async_webrtc = False
```
After adding these attributes, the errors stopped appearing in the logs, and the integration started working as expected.

**Comment by melianor** [comment]
> _webrtc_provider = None
> _legacy_webrtc_provider = None
> _supports_native_sync_webrtc = False
> _supports_native_async_webrtc = False

Hi @taifunk, thanks that worked nicely. 
Maybe this can make it into a future release?

**Comment by auanasgheps** [comment]
Hi there, can you please tell exactly where I should add those values in the camera.py file?

**Comment by kovacsla** [comment]
> Hi there, can you please tell exactly where I should add those values in the camera.py file?

![image](https://github.com/user-attachments/assets/02016de9-38aa-4341-8001-0a6419631e38)

**Comment by auanasgheps** [comment]
Thanks, working! 
Since you deserve the credit, you should create a PR to fix this

**Comment by mertcanyalhi** [comment]
@taifunk when will you be creating a PR for the fix?

**Comment by wernerhp** [comment]
Dreame L10 Prime doesn't have a camera.
```
2024-11-23 17:56:15.455 ERROR (MainThread) [homeassistant.components.camera] Error adding entity camera.dreamebot_l10_prime_map for domain camera with platform dreame_vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 599, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 918, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1366, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 791, in async_internal_added_to_hass
    await self.async_refresh_providers(write_state=False)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 799, in async_refresh_providers
    old_provider = self._webrtc_provider
                   ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DreameVacuumCameraEntity' object has no attribute '_webrtc_provider'
2024-11-23 17:56:15.487 ERROR (MainThread) [homeassistant.components.camera] Error adding entity camera.dreamebot_l10_prime_map_data for domain camera with platform dreame_vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 599, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 918, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1366, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 791, in async_internal_added_to_hass
    await self.async_refresh_providers(write_state=False)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 799, in async_refresh_providers
    old_provider = self._webrtc_provider
                   ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DreameVacuumCameraEntity' object has no attribute '_webrtc_provider'
2024-11-23 17:56:19.159 ERROR (MainThread) [homeassistant.components.camera] Error adding entity camera.dreamebot_l10_prime_map_1 for domain camera with platform dreame_vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 599, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 918, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1366, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 791, in async_internal_added_to_hass
    await self.async_refresh_providers(write_state=False)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 799, in async_refresh_providers
    old_provider = self._webrtc_provider
                   ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DreameVacuumCameraEntity' object has no attribute '_webrtc_provider'
```

**Comment by RykovDC** [comment]
The problem still persists on the Home Assistant Core 2024.11.3?

**Comment by alexsotoaguilera** [comment]
> The problem still persists on the Home Assistant Core 2024.11.3?

yes

**Comment by kovacsla** [comment]
> Dreame L10 Prime doesn't have a camera.
> 
> ```
> 2024-11-23 17:56:15.455 ERROR (MainThread) [homeassistant.components.camera] Error adding entity camera.dreamebot_l10_prime_map for domain camera with platform dreame_vacuum
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 599, in _async_add_entities
>     await coro
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 918, in _async_add_entity
>     await entity.add_to_platform_finish()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1366, in add_to_platform_finish
>     await self.async_internal_added_to_hass()
>   File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 791, in async_internal_added_to_hass
>     await self.async_refresh_providers(write_state=False)
>   File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 799, in async_refresh_providers
>     old_provider = self._webrtc_provider
>                    ^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'DreameVacuumCameraEntity' object has no attribute '_webrtc_provider'
> 2024-11-23 17:56:15.487 ERROR (MainThread) [homeassistant.components.camera] Error adding entity camera.dreamebot_l10_prime_map_data for domain camera with platform dreame_vacuum
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 599, in _async_add_entities
>     await coro
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 918, in _async_add_entity
>     await entity.add_to_platform_finish()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1366, in add_to_platform_finish
>     await self.async_internal_added_to_hass()
>   File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 791, in async_internal_added_to_hass
>     await self.async_refresh_providers(write_state=False)
>   File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 799, in async_refresh_providers
>     old_provider = self._webrtc_provider
>                    ^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'DreameVacuumCameraEntity' object has no attribute '_webrtc_provider'
> 2024-11-23 17:56:19.159 ERROR (MainThread) [homeassistant.components.camera] Error adding entity camera.dreamebot_l10_prime_map_1 for domain camera with platform dreame_vacuum
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 599, in _async_add_entities
>     await coro
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 918, in _async_add_entity
>     await entity.add_to_platform_finish()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1366, in add_to_platform_finish
>     await self.async_internal_added_to_hass()
>   File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 791, in async_internal_added_to_hass
>     await self.async_refresh_providers(write_state=False)
>   File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 799, in async_refresh_providers
>     old_provider = self._webrtc_provider
>                    ^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'DreameVacuumCameraEntity' object has no attribute '_webrtc_provider'
> ```

This is the solution:
https://github.com/Tasshack/dreame-vacuum/issues/778#issuecomment-2471687143

**Comment by Ich79** [comment]
Unfortunately still not merged into v2.0.0b16. Issue persists without manual fix mentioned above

**Comment by mertcanyalhi** [comment]
@Ich79 have you tried turning it off and on again? Last month, I had a gas leak in my kitchen. When I turned my oven off and on again, the gas leak was resolved. I wouldn't believe it if it hadn't solved my issue; sometimes the most unexpected solutions can come from the easiest actions. I now try to turn everything off and on again.
