### ISSUE TITLE
Can't control vacuum (Dreame L10 Ultra), can't install v2.0.0b16

### ISSUE THREAD

**Issue by Maetzi87** [Tasshack/dreame-vacuum#824]
**Describe the bug**
Vacuum control is broken, installation of v2.0.0b16 was never possible.

**To Reproduce**
I just tried to start the device, result:
![Unbenannt2](https://github.com/user-attachments/assets/8d611482-5088-49b0-a155-26594ed2423f)
Tried to install update, result:
![Unbenannt](https://github.com/user-attachments/assets/58892f57-1fa7-443a-9896-3b2f06b44c35)

**Additional Information (please complete the following information)**
 - Model Name: dreame.vacuum.r2257o
 - Firmware Version: 4.3.9_1618
 - Home Assistant Version: 
 - Configuration Type: with map support
 - Errors or warnings shown in the HA logs (if applicable): see pictures

**Comment by Maetzi87** [comment]
Sorry, didn't saw that before. My fault.

**Comment by Maetzi87** [comment]
ok, I reinstalled the integration, now getting these two errors:


Logger: homeassistant.components.camera
Quelle: helpers/entity_platform.py:599
Integration: Kamera (Dokumentation, Probleme)
Erstmals aufgetreten: 18:22:09 (3 Vorkommnisse)
Zuletzt protokolliert: 18:22:10

Error adding entity camera.dreama_map for domain camera with platform dreame_vacuum
Error adding entity camera.dreama_map_erdgeschoss for domain camera with platform dreame_vacuum
Error adding entity camera.dreama_wifi_map_1 for domain camera with platform dreame_vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 599, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 918, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1366, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 791, in async_internal_added_to_hass
    await self.async_refresh_providers(write_state=False)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 799, in async_refresh_providers
    old_provider = self._webrtc_provider
                   ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DreameVacuumCameraEntity' object has no attribute '_webrtc_provider'


and





Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: root
Quelle: custom_components/dreame_vacuum/dreame/protocol.py:1206
Integration: Dreame Vacuum (Dokumentation, Probleme)
Erstmals aufgetreten: 18:22:08 (1 Vorkommnisse)
Zuletzt protokolliert: 18:22:08

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 112, in _api_task
    item[0](self._api_call(item[1], item[2], item[3]))
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 388, in <lambda>
    lambda api_response: callback(
                         ^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 1206, in cloud_callback
    raise DeviceException("Unable to discover the device over cloud") from None
custom_components.dreame_vacuum.dreame.exceptions.DeviceException: Unable to discover the device over cloud



any idea?

**Comment by Maetzi87** [comment]
oh, and that:

Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: custom_components.dreame_vacuum.dreame.map
Quelle: custom_components/dreame_vacuum/dreame/map.py:294
Integration: Dreame Vacuum (Dokumentation, Probleme)
Erstmals aufgetreten: 18:22:07 (1 Vorkommnisse)
Zuletzt protokolliert: 18:22:07

Send request map failed: Unable to discover the device over cloud

**Comment by Maetzi87** [comment]
device is reachable over dreame app without problems
